/**
 * Every line the app says (D-046), looked up by key. Written well, in full sentences, in the voice of a
 * told tale (Dan: "think J. R. R. Tolkien", 2026-09-24, D-073); buttons and settings stay short and plain. {name} marks a value filled in by the screen.
 */
export const copy = {
  /* Today */
  'today.ahead': 'Ahead',
  'today.next': 'Next',
  'today.teaser.avoided': 'This is the task you have been putting off, and something waits for you on the far side of it.',
  'today.teaser.delve': 'The passage runs on from where you last set down your lamp.',
  'today.teaser.away': 'This one is done out in the world, away from the phone. Come back when it is finished, and say so.',
  'today.begin': 'Begin',
  'today.delve': 'Delve',
  'today.swap': 'Swap',
  'today.cantStart': 'I can’t start',
  'today.underWay': 'Under way',
  'today.underWay.say': 'The road will keep until you return. When the work is done, come back and mark it so.',
  'today.unbegin': 'I haven’t started',
  'today.aside.said': 'Taken off today.',
  'today.putBack': 'Put it back',
  'today.stillToCome': 'Still to come: {what}.',
  'today.done': 'Done',
  'today.carry': 'Carry on with {job}',
  'today.carry.left': 'You have {min} left in this delve.',
  'today.carry.go': 'Carry on',
  'today.finishHere': 'Finish here',
  'today.label': 'Today',
  'today.enough': 'The day’s work is done, and it was enough.',
  'today.reached': 'You came at last to {place}.',
  'today.camped': 'You made your camp at {place}.',
  'today.look': 'See where you are',
  'today.keepGoing': 'Keep going',
  'row.done': 'done',
  'row.underWay': 'under way',
  'row.delves': '{n}, {len} minutes each',
  'row.delve': 'a delve',
  'row.about': 'about {len}',
  'nav.proto': 'Trial',

  /* the run set-up (the dial) */
  'set.label': 'Delves',
  'set.minutes': 'minutes',
  'set.towards': 'Towards {place}',
  'set.to': 'To {place}',
  'set.onward': 'Further in',
  'set.nextPlace': 'the next place',
  'set.count': '{n} of {len}',
  'set.ends': 'finishing around {end}',
  'set.enoughAt': 'enough by around {at}',
  'set.enoughAndEnds': 'enough by around {at}, finishing around {end}',
  'set.here': 'here',
  'set.enough': 'enough',
  'set.side': 'a side chamber',
  'set.less': 'One delve fewer',
  'set.more': 'One more delve',
  'set.length': 'Length of each delve',
  'set.begin': 'Begin',

  /* the delve */
  'delve.towards': 'Towards',
  'delve.further': 'Further in',
  'delve.moves': 'While you work, the expedition goes on beneath the hill.',
  'delve.left': 'left of {len} minutes',
  'delve.single': 'one delve',
  'delve.ofRun': 'the {ord} of {card} delves',
  'delve.enoughAfter': 'This one takes you to enough for today.',
  'delve.more': 'This one is extra: the {ord} delve.',
  'delve.away.locked': 'Lock the phone and put it away: the delve goes on, and a sound will call you back when it is over. Going into another app pauses it.',
  'delve.away.noAlerts': 'Alerts are turned off for this app in Settings, so no sound will come while the phone is locked. Keep an eye on the time, or turn them on in Settings, then Notifications.',
  'delve.away.web': 'Set the phone down and leave this page open: a chime will call you back. Leaving the page pauses the delve.',
  'delve.stepAway': 'Pause',
  'delve.paused': 'Paused',
  'delve.finishHere': 'Finish here',
  'delve.breather': 'A breather',
  'delve.breather.done': 'The {ord} delve is behind you.',
  'delve.breather.say': 'Rest a while and draw breath. The next delve will begin on its own.',
  'delve.breather.enough': 'You have done enough for today. You asked for more, and so the next delve will begin on its own.',
  'delve.startNow': 'Start it now',
  'delve.held.say': 'Your minutes are safe. The delve will wait for you, even if you close the app.',
  'delve.back': 'Back to the delve',
  'delve.back.left': '{min} left',
  'delve.awayLabel': 'Paused while you were away',
  'delve.away.say': 'You went into another app, so the delve waited for you. The time away does not count, and nothing you did is lost.',
  'delve.carryOn': 'Carry on',
  'delve.label': 'The delve',
  'delve.enoughLabel': 'Enough',
  'delve.doneOne': 'The delve is ended, and your lamp still burns.',
  'delve.doneRun': 'The long run is ended.',
  'delve.sessionComplete': 'Your {job} is done for the day.',
  'delve.enoughSay': 'It is enough, and more would be a gift, not a debt.',
  'delve.finished': 'You spent {min} on {job}.',
  'delve.ask': 'Is it done?',
  'delve.yes': 'Done',
  'delve.notYet': 'Not yet',
  'delve.yesSay': 'It is done, and the day goes on.',
  'delve.kept': 'Every minute counts: {min} so far.',
  'delve.keptSay': 'Nothing is lost. It will be waiting when you come back to it.',
  'delve.toToday': 'Back to today',
  'delve.see': 'See where you are',
  'delve.today': 'Today',

  /* the step, for a job done away from the phone */
  'step.label': 'Done',
  'step.done': '{job}',
  'step.key': 'You kept up one of your repeating jobs and earned a Key. Where a Key lands, notches in the dark fill with light. When a whole row is lit, whatever it kept shut opens.',
  'find.label': 'A find',
  'guess.label': 'A symbol',
  'guess.from': 'One of the symbols you saw at {place}.',
  'arrive.marksLater': 'Not every symbol here can be read yet. You will be asked about them further on, and the Symbols page keeps them until then.',
  'guess.ask': 'What do you think it means?',
  'guess.kept': 'You guessed {guess}. In time the place itself will tell you whether you were right.',
  'records.label': 'Records',
  'records.title': 'What you’ve found',
  'records.none': 'You have found nothing yet. Records lie further in, for those who go looking.',
  'records.her': 'Her sheet',
  'records.read': 'Read it',
  'records.done': 'Done reading',
  'records.tapMark': 'Tap a symbol to see what you know of it.',
  'records.nav': 'Records',

  /* the marks (SCRIPT §9; mock-up record.html) */
  'marks.nav': 'Symbols',
  'marks.label': 'Symbols',
  'marks.title': 'What you can read',
  'marks.none': 'You have no symbols yet. They are cut on walls and records further in.',
  'marks.this': 'This symbol',
  'marks.new': 'new',
  'marks.aName': 'a name',
  'marks.unknown': 'Seen, but not known yet',
  'marks.held': 'You know this one now: it means {word}. The place itself told you.',
  'marks.guess': 'You guessed {word}. In time the place itself will tell you whether you were right.',
  'marks.open': 'You have not met this symbol before. What do you think it means?',
  'marks.seen': 'You have seen this symbol, but its meaning is still hidden from you.',
  'marks.ring': 'This is a name, cut inside a ring. You cannot read it yet, but you will know it when you meet it again.',
  'marks.part': 'Only part of it has come to light so far: {part}. The rest lies further in.',
  'marks.keep': 'Keep {word}',
  'marks.change': 'Change it',
  'marks.else': 'What else might it mean?',
  'marks.struck': 'You guessed {word}.',
  'settle.held': 'Your guess held true: {word}.',
  'part.label': 'Part of a symbol',
  'part.hook': 'a hook, open',
  'part.wedge': 'a wedge',
  'guess.part': 'You have seen part of this one before: {part}.',

  /* the word: cutting it (the story job's §7; mock-up cut.html), and the stair beyond (stair.html, D-039) */
  'cut.label': 'The word',
  'cut.ask': 'Cut the word: the two symbols you know, in the right order.',
  'cut.hint.rod': 'Tap the blank to set the rod’s edge in it.',
  'cut.hint.first': 'Tap the first symbol to cut it.',
  'cut.hint.second': 'Now tap the second.',
  'cut.hint.lock': 'Tap the rod to lock the word.',
  'cut.through': 'Go through',
  'cut.later': 'Later',
  'stair.label': 'Beyond the lintel',
  'stair.say': 'From here, every delve takes you further down into the deep.',
  'stair.down': 'Go down',
  'map.nav': 'Map',
  'map.label': 'The map',
  'map.regionLabel': 'The first region',
  'map.regionName': 'The Quiet',
  'map.here': 'you are here',
  'map.hereLabel': 'You are here',
  'map.walked': 'Walked',
  'map.walkedSealed': 'Walked · something sealed here',
  'map.reached': 'Reached',
  'map.wayIn': 'The way you came in.',
  'map.sealed': 'sealed',
  'map.sealedLabel': 'Sealed · in view',
  'map.sealedSay': 'It is shut. Keep up a repeating job to earn a Key. A Key fills the notches on it with light, and then it opens.',
  'map.ahead': 'ahead',
  'map.aheadLabel': 'Not reached yet',
  'map.aheadName': 'Somewhere ahead',
  'map.aheadSay': 'Its name comes when you get there.',
  'map.forecast': '{day} · forecast',
  'map.forecastLabel': 'Forecast',
  'map.forecastSay': 'If the week goes as planned, the next place is reached on {day}. A forecast, not a promise.',

  /* day complete and the arrival */
  'arrive.label': 'Arrived',
  'words.hide': 'Hide the words',
  'words.show': 'Read on',
  'arrive.camp': 'Camp',
  'arrive.enough': 'The day’s work is done.',
  'arrive.keyOpens': 'The Key you earned from a repeating job lands here.',
  'arrive.enough2': 'Rest now.',
  'arrive.rest': 'Rest here for today',
  'arrive.onward': 'Back to today',

  /* I can't start */
  'cant.label': 'Just ahead',
  'cant.first': 'Start with one small thing:',
  'cant.ten': 'Try ten minutes?',
  'cant.notNow': 'Not now',
  'cant.fallback': 'The passage runs on, and a cool draught comes up from somewhere further in.',

  /* the prototype's own controls (temporary; PROTOTYPE_NOTES.md) */
  'proto.label': 'Prototype',
  'proto.title': 'The first playable, being built',
  'proto.about': 'This save is a trial run: it starts afresh when the test begins. The paintings are stand-ins until each place is painted.',
  'proto.rehearsal': 'Rehearsal: minutes pass 60 times faster',
  'proto.rehearsal.on': 'Rehearsal is on. A 25-minute delve takes 25 seconds. It has its own save, which starts afresh each time.',
  'proto.rehearsal.off': 'Real time. Use it on real jobs.',
  'proto.rehearsal.start': 'Start a rehearsal',
  'proto.rehearsal.stop': 'Back to real time',
  'proto.reset': 'Start this save again',
  'proto.reset.confirm': 'Tap again to wipe it',
  'proto.close': 'Close',
  'proto.badge': 'Rehearsal ×60',
  'proto.leave.title': 'Locking, or another app?',
  'proto.leave.about': 'To test the pause (D-094): start a delve, lock the phone for half a minute, and come back. Then go into another app for half a minute, and come back. Each time shows here with how the phone read it.',
  'proto.leave.locked': 'Locked: the delve went on',
  'proto.leave.left': 'Another app: paused',
  'proto.leave.unsure': 'Back within 15 seconds, no sign of a lock: the delve went on',
  'proto.leave.none': 'Nothing yet.',

  /* the week and the gaps (slice 4) */
  'today.tonight': 'Tonight',
  'today.bedtime': 'Bed by',
  'today.tonight.say': 'Press Go to sleep as you get into bed, then put the phone down. In bed by {bedtime}, and tomorrow begins a little further in, with something waiting for you.',
  'today.deep': 'It is a great day. Will you push deeper?',
  'today.deep.say': 'Once a normal day’s jobs are done, the route goes deeper.',
  'today.deep.call': 'Push deeper',
  'today.deep.called': 'You will push deeper today. When a normal day’s work is done, the way goes further down.',
  'nav.satchel': 'Satchel', 'nav.week': 'Week', 'nav.daybook': 'Daybook', 'nav.back': 'Back',
  'row.at': 'at {time}',
  'row.room': '{enough} · up to {len}',
  'row.oneOff': 'one-off',

  /* choosing what to do: any job, any time (D-077) */
  'row.notToday': 'Not today',
  'today.notToday': 'Not today',
  'oops.say': 'Something went wrong on this screen. Your save is safe.',
  'today.running.say': 'Your delve is still going. The timer keeps time whether you watch it or not.',
  'today.running.go': 'Back to the delve',
  'today.else': 'Something else…',
  'today.clear': 'Nothing more is on today’s list.',
  'today.clear.say': 'Choose something else to delve on, or rest. The road will keep.',
  'choose.label': 'Choose a delve',
  'choose.say': 'Any job can be a delve. Pick one, or name something new.',
  'choose.today': 'On today’s list',
  'choose.other': 'Your other jobs',
  'choose.all': 'Your jobs',
  'choose.satchel': 'From your satchel',
  'choose.new': 'Something else',
  'choose.new.hint': 'Name it',
  'choose.new.go': 'Delve on it',
  'choose.aside': 'set aside today',

  'camp.bedtime': 'Bedtime',
  'camp.change': 'Change',
  'camp.earlier': 'Earlier',
  'camp.later': 'Later',
  'camp.sleep.kept': 'You are in bed on time. Tomorrow begins a little further in, with something waiting for you. Put the phone down now.',
  'camp.sleep.late': 'Sleep well. The head start is for nights you are in bed by {bedtime}. Nothing is lost.',
  'morning.headStart': 'You went to sleep on time, so the day begins a little further in.',
  'camp.goodnight': 'Go to sleep',
  'camp.night': 'Goodnight.',

  'morning.label': 'In the morning',
  'morning.title': 'Something was waiting for you at camp.',
  'morning.read': 'Read the record again',
  'morning.go': 'On to today',

  'welcome.label': 'Where you were',
  'welcome.at': 'You were at {place}.',
  'welcome.ahead': 'Ahead of you: {thing}.',
  'welcome.record': 'Read the last record',
  'welcome.go': 'Back to today',
  'welcome.say': 'You have been away, but the road has waited for you. One small task is enough to take it up again.',

  'daybook.label': 'The daybook',
  'daybook.week': 'Week {n}',
  'daybook.written': 'Written for you as the week drew to its close.',
  'daybook.none': 'The pages are still blank. At the end of each week in which you do something, a page will be written here for you.',
  'daybook.held': 'The week held',
  'daybook.times': '{job} {n}',
  'daybook.once': 'once', 'daybook.twice': 'twice', 'daybook.many': '{n} times',
  'daybook.reached': 'You reached {places}.',
  'daybook.went': 'Where you went',
  'daybook.camped': 'It was a week of camps and short roads, and every step of it still counts.',
  'daybook.learned': 'Learned',
  'daybook.soFar': 'So far',
  'daybook.next': 'Next week',
  'daybook.count': 'At {where}, a row of notches filled with light, and what it kept shut opened.',
  'daybook.offer': 'Shall the week ahead be planned for you?',
  'daybook.planIt': 'Plan it for me',
  'daybook.notNow': 'Not now',
  'daybook.close': 'Close',
  'daybook.earlier': 'Earlier',
  'daybook.later': 'Later',
  'and': 'and',

  'week.label': 'This week',
  'week.next': 'Next week',
  'week.this': 'This week',
  'week.forecast': 'The plan points to {what}.',
  'week.forecast.one': 'the next place around {day}',
  'week.forecast.then': 'and the one after around {day}',
  'week.none': 'There is no plan for this week.',
  'week.none.next': 'There is no plan for next week yet.',
  'week.none.say': 'Today works well enough without one. If you like, the week can be laid out for you, and you may change whatever looks wrong.',
  'week.plan': 'Plan my week',
  'week.rhythms': 'What repeats',
  'week.add': 'Add',
  'week.addTo': 'Add to {day}',
  'week.moveTo': 'Move to',
  'week.at': 'At {time}',
  'week.addPlaceholder': 'For example, the dentist',
  'week.time': 'Time',
  'week.anyTime': 'Any time',
  'week.setTime': 'Set a time',
  'week.asideNote': 'not today',
  'week.fold.done': '{n} done', 'week.fold.left': '{n} to do',
  'week.putBack': 'Back on today',
  'week.off': 'Not this week',
  'week.today': 'today',

  'rhythms.label': 'What repeats',
  'rhythms.say': 'These are the things you do again and again. You may change any of them, at any time.',
  'rhythms.add': 'Add one',
  'rhythms.editing': 'Change it', 'rhythms.adding': 'A new one',
  'rhythms.name': 'What',
  'rhythms.often': 'How often',
  'rhythms.aWeek': 'A week', 'rhythms.setDays': 'Set days', 'rhythms.fortnight': 'Fortnightly',
  'rhythms.nWeek': '{n} a week',
  'rhythms.timesWeek': '{n} times a week',
  'rhythms.onceWeek': 'Once a week',
  'rhythms.every2': 'every 2 weeks',
  'rhythms.every2long': 'Once every 2 weeks',
  'rhythms.each': 'Each time',
  'rhythms.enough': 'Enough at',
  'rhythms.all': 'All of it',
  'rhythms.runs': 'How it runs',
  'rhythms.delves': 'As delves', 'rhythms.noTimer': 'No timer',
  'rhythms.asDelves': 'as delves',
  'rhythms.enoughRoom': '{enough} is enough, with room for {len}',
  'rhythms.newNumber': 'A changed number counts from next week, but you can plan with it straight away.',
  'rhythms.save': 'Save', 'rhythms.cancel': 'Cancel',
  'rhythms.stop': 'Stop repeating',
  'rhythms.less': 'Fewer', 'rhythms.more': 'More', 'rhythms.shorter': 'Shorter', 'rhythms.longer': 'Longer',
  'days.short.0': 'Sun', 'days.short.1': 'Mon', 'days.short.2': 'Tue', 'days.short.3': 'Wed', 'days.short.4': 'Thu', 'days.short.5': 'Fri', 'days.short.6': 'Sat',
  'days.plural.0': 'Sundays', 'days.plural.1': 'Mondays', 'days.plural.2': 'Tuesdays', 'days.plural.3': 'Wednesdays', 'days.plural.4': 'Thursdays', 'days.plural.5': 'Fridays', 'days.plural.6': 'Saturdays',

  'satchel.label': 'The satchel',
  'satchel.say': 'For the days that come with a list.',
  'satchel.add': 'Add a line',
  'satchel.addMany': 'Write one item per line. You can paste in a whole list.',
  'satchel.put': 'Put it in',
  'satchel.more': 'Show the rest',
  'satchel.less': 'Hide the rest',
  'satchel.someday': 'Someday',
  'satchel.today': 'Put on today',
  'satchel.onToday': 'on today’s list',
  'satchel.letGo': 'Let it go',
  'satchel.empty': 'Your satchel is empty. When a day comes with a list, it belongs here, not on the opening screen.',
  'satchel.tick': 'Tick {name}',

  'month.1': 'January', 'month.2': 'February', 'month.3': 'March', 'month.4': 'April', 'month.5': 'May', 'month.6': 'June',
  'month.7': 'July', 'month.8': 'August', 'month.9': 'September', 'month.10': 'October', 'month.11': 'November', 'month.12': 'December',

  /* the phone's alerts */
  'notify.delveEnd.title': 'The delve is over',
  'notify.delveEnd.body': 'Come back up when you are ready.',
  'notify.breatherEnd.title': 'The next delve is starting',
  'notify.breatherEnd.body': 'Your breather is over.',

  /* the delve's panel on the lock screen and in the Dynamic Island (D-095): read at a glance, so short */
  'panel.paused': 'Your minutes are safe.',
  'panel.breather.line': 'The {ord} delve will begin on its own.',
  'panel.breather.left': 'of the breather',
  'panel.goesOn': 'The run goes on',
  'panel.goesOn.line': 'It goes on by itself, and ends at {end}.',
  'panel.goesOn.left': 'left of the run',

  /* words for numbers and times */
  'min.one': '1 minute', 'min.many': '{n} minutes', 'hour.one': '1 hour', 'hour.many': '{n} hours',
  'min.short': '{n} min', 'hour.short': '{n} h',
  'ord.1': 'first', 'ord.2': 'second', 'ord.3': 'third', 'ord.4': 'fourth', 'ord.5': 'fifth', 'ord.6': 'sixth', 'ord.7': 'seventh', 'ord.8': 'eighth',
  'card.1': 'one', 'card.2': 'two', 'card.3': 'three', 'card.4': 'four', 'card.5': 'five', 'card.6': 'six', 'card.7': 'seven', 'card.8': 'eight',
  'delves.one': '1 delve', 'delves.many': '{n} delves',
  'day.0': 'Sunday', 'day.1': 'Monday', 'day.2': 'Tuesday', 'day.3': 'Wednesday', 'day.4': 'Thursday', 'day.5': 'Friday', 'day.6': 'Saturday',
} as const;

export type CopyKey = keyof typeof copy;
export const t = (k: CopyKey, vars?: Record<string, string | number>): string =>
  vars ? copy[k].replace(/\{(\w+)\}/g, (_, v) => String(vars[v] ?? '')) : copy[k];

/** "25 minutes", "1 hour 20 minutes" */
export function minutesWords(m: number): string {
  if (m < 60) return t(m === 1 ? 'min.one' : 'min.many', { n: m });
  const h = Math.floor(m / 60), r = m % 60;
  return t(h === 1 ? 'hour.one' : 'hour.many', { n: h }) + (r ? ' ' + t(r === 1 ? 'min.one' : 'min.many', { n: r }) : '');
}
/** "50 min", "3 h", "1 h 20 min": for a note that must stay on one line */
export function minutesShort(m: number): string {
  if (m < 60) return t('min.short', { n: m });
  const h = Math.floor(m / 60), r = m % 60;
  return t('hour.short', { n: h }) + (r ? ' ' + t('min.short', { n: r }) : '');
}
export const ord = (k: number) => copy[`ord.${Math.min(8, Math.max(1, k))}` as CopyKey];
export const card = (k: number) => copy[`card.${Math.min(8, Math.max(1, k))}` as CopyKey];
export const delves = (n: number) => t(n === 1 ? 'delves.one' : 'delves.many', { n });
/** A place's name inside a sentence: "You reached the Rib Gallery." */
export const inSentence = (name: string) => name.replace(/^The /, 'the ');
/** "Monday", from a game day. */
export const dayName = (day: string) => copy[`day.${new Date(`${day}T00:00:00Z`).getUTCDay()}` as CopyKey];
/** "once", "twice", "4 times" */
export const timesWords = (n: number) => n === 1 ? copy['daybook.once'] : n === 2 ? copy['daybook.twice'] : t('daybook.many', { n });
/** "a, b and c" */
export function listWords(xs: string[]): string {
  return xs.length <= 1 ? xs.join('') : `${xs.slice(0, -1).join(', ')} ${copy.and} ${xs[xs.length - 1]}`;
}
/** "21 – 27 September" */
export function weekDates(monday: string): string {
  const a = new Date(`${monday}T00:00:00Z`), b = new Date(a.getTime() + 6 * 864e5);
  const m = (d: Date) => copy[`month.${d.getUTCMonth() + 1}` as CopyKey];
  return a.getUTCMonth() === b.getUTCMonth() ? `${a.getUTCDate()} – ${b.getUTCDate()} ${m(b)}` : `${a.getUTCDate()} ${m(a)} – ${b.getUTCDate()} ${m(b)}`;
}
