/**
 * SEALED STORY CONTENT (D-015). Never shown to Dan outside the game.
 * Transcribed from docs/narrative/sealed/ (ARRIVALS_REGION1.md weeks 1-5, ARRIVALS_REGION2.md weeks 6-7,
 * MVP_CONTENT.md §0-§3). Those files are authoritative; fix them first, then this.
 */
import type { Beat } from '../../core/story-types';

/** Story beats (ARR rows; `o` = the row's position in its week's ARR table, teaser rows counted but not included), then the 15 `pl-` places (`o` = route position, MVP_CONTENT §2). */
export const beats: Beat[] = [
  // ---- Week 1 ----
  {
    id: "b-w1.morning",
    kind: "morning",
    w: 1,
    o: 1,
    line: "You are standing in a field on the side of a hill. Among the grass lies an iron cap the size of a table. Its padlock is on the ground beside it, cut.",
    req: [],
    stretch: "st-mouth",
  },
  {
    id: "b-1.1",
    kind: "step",
    w: 1,
    o: 2,
    line: "The shaft cap has been lifted aside. Its padlock lies next to it, the shackle cut clean through. Two notices remain fixed to the cap: an old enamel one, its name worn away to nothing, saying DANGER OF FALLING, and a new laminated one with a phone number. Below them, eleven metres of ladder descend into dry air.",
    req: [],
    stretch: "st-mouth",
  },
  {
    id: "b-1.2",
    kind: "step",
    w: 1,
    o: 3,
    line: "At the foot of the ladder the brickwork ends and a passage begins. Floor and walls run together in a single curve, like the inside of a pipe; nowhere is there a tool-mark. Twenty paces on, the passage widens.",
    req: [],
    stretch: "st-mouth",
  },
  {
    id: "b-1.A",
    kind: "arrival",
    w: 1,
    o: 4,
    name: "The Lamp Hall",
    line: "The hall rises long and high, its edges rounded like the inside of a shell. At the near end, on a ledge, a clay lamp is burning. It was lit when you came down. There is no oil in it. Cups are cut into both walls at head height, one every few paces, all empty. Marks cover every surface within reach, with rings among them. At the far end, beyond the light, a door occupies most of the wall.",
    choice: ["Look at the lamp", "look at the wall"],
    req: [],
    stretch: "st-hall",
    painting: "pt-b-1.A",
    carries: {"records": ["rec-l1", "rec-k1"], "seen": ["mk-ring"]},
  },
  {
    id: "b-1.3",
    kind: "step",
    w: 1,
    o: 5,
    line: "Close to the lamp, the wall resolves into deliberate cuts. A lamp is carved there, shaped like the one on the ledge, with a single mark beside it. Below it is a carved flame, and beside the flame another mark.",
    req: ["b-1.A"],
    stretch: "st-hall",
    carries: {"records": ["rec-l1"], "guess": ["mk-lamp"]},
  },
  {
    id: "b-1.4",
    kind: "step",
    w: 1,
    o: 6,
    line: "Seen close, the flame’s mark is two cuts that spread apart from a single point. The lamp’s mark has the same two cuts, set inside a cup.",
    req: ["b-1.A"],
    stretch: "st-hall",
    carries: {"records": ["rec-l1"], "guess": ["mk-fire"]},
  },
  {
    id: "b-1.B",
    kind: "arrival",
    w: 1,
    o: 7,
    name: "The corner",
    line: "At the turn of the hall, two long troughs have been worn into the floor a stride apart. Beside them the wall is polished smooth to the shoulder height of a man, if that man were twice your size; the marks there have been rubbed faint. Past the turn another gallery opens. The air smells of salt.",
    req: [],
    stretch: "st-hall",
    painting: "pt-b-1.B",
  },
  {
    id: "b-1.5",
    kind: "step",
    w: 1,
    o: 8,
    line: "This is the Salt Gallery, where the hill’s rock salt meets the cut stone. The salt face is split from the top to knee height, the opening packed from the other side with stones and salt. A line of marks runs the length of the gallery, all cut by one hand. Beside it, loose sheets of paper have been tucked into a crack and dated in pencil: Day 1, Day 4, Day 9.",
    choice: ["Look at the wall", "Look at her sheets"],
    req: ["b-1.B"],
    stretch: "st-salt",
    carries: {"records": ["rec-s1"]},
  },
  {
    id: "b-1.6",
    kind: "stepKey",
    w: 1,
    o: 9,
    line: "Where the first stretch of the line ends, a row of strokes is cut directly into the salt. The first stroke is full of light now. Beyond it the marks continue into darkness.",
    seal: "seal-1-1",
    req: [],
    stretch: "st-salt",
  },
  // NOTE: inView includes seal-1-4 (her boots: seen, not sealed, NICHES 1.4) as well as the tin box.
  {
    id: "b-1.C",
    kind: "arrival",
    w: 1,
    o: 10,
    name: "The Survey Cut",
    line: "Someone lived in this side chamber. A camp cot stands against the wall; beneath it, a pair of dry, laced boots have been placed neatly side by side, ready for morning. On the cot are a notebook with a pencil tucked into it and a tin box whose lid carries a row of cut strokes. A stone rod rests on the shelf, forearm-long, one edge finer than a knife’s.",
    choice: ["Open the notebook", "look at the shelf"],
    req: [],
    stretch: "st-camp",
    painting: "pt-b-1.C",
    carries: {"records": ["rec-l2"], "inView": ["seal-1-4", "seal-2-1"]},
  },
  // NOTE: deep beats take the steps rule (nearest arrival above) as their req.
  {
    id: "b-1.7",
    kind: "deep",
    w: 1,
    o: 11,
    line: "On the lamp’s side, away from the three marks on its base, a hook, open, is cut on its own. The rest of the cell is bare.",
    req: ["b-1.C"],
    stretch: "st-hall",
    carries: {"seen": ["mk-give"], "partial": "hook"},
  },
  {
    id: "b-w1.camp",
    kind: "camp",
    w: 1,
    o: 12,
    line: "You sit beside the lamp. When the flame moves, the rings on the wall behind it take the light one by one.",
    req: [],
    stretch: "st-hall",
    morning: "a line of the salt tally re-rendered with your two guesses",
  },
  {
    id: "b-w1.close",
    kind: "close",
    w: 1,
    o: 14,
    line: "A lintel stands on the side wall, but beneath it there is no doorway: only stone. Two marks are cut beside it with a blank between them. One is the flame’s.",
    req: [],
    stretch: "st-hall",
  },
  // ---- Week 2 ----
  // NOTE: stepKey beats take no arrival req; their seal being in view (Key rule, MVP_CONTENT §0.2) governs them.
  {
    id: "b-2.1",
    kind: "stepKey",
    w: 2,
    o: 1,
    line: "On the cot, the count cut into the tin box’s lid fills. The lid lifts. Inside are more sheets; on one, four marks have been drawn large. Three have pencilled words beneath them. Beneath the fourth is only a question mark.",
    seal: "seal-2-1",
    req: [],
    stretch: "st-camp",
    carries: {"guess": ["mk-person", "mk-one", "mk-me"]},
  },
  {
    id: "b-2.2",
    kind: "step",
    w: 2,
    o: 2,
    line: "At the side-wall lintel, two marks flank a blank. One is the flame’s mark. The other is a hook, and a drop leaving it. Under the lintel there is still no door, only stone.",
    req: ["seal-2-1"],
    stretch: "st-hall",
    carries: {"guess": ["mk-give"]},
  },
  {
    id: "b-2.A",
    kind: "arrival",
    w: 2,
    o: 3,
    name: "The Salt Gallery, further in",
    line: "Beyond the inner count the tally continues in the same hand. Above it, set apart and larger than the others, is a single ring. Her sheets do not cover the next stretch.",
    choice: ["Read the tally", "look at the ring"],
    req: [],
    stretch: "st-salt",
    painting: "pt-b-2.A",
    carries: {"records": ["rec-s2"]},
  },
  {
    id: "b-2.3",
    kind: "step",
    w: 2,
    o: 4,
    line: "You open the notebook at Day 3.",
    req: ["b-2.A"],
    stretch: "st-camp",
    carries: {"records": ["rec-l3"]},
  },
  {
    id: "b-2.4",
    kind: "stepKey",
    w: 2,
    o: 5,
    line: "The count on the tally-stick’s niche fills. Inside is a stick notched in fives. Beside it, a short line in the tally’s hand has been cut into the wall, with a number among the marks.",
    seal: "seal-2-2",
    req: [],
    stretch: "st-salt",
    carries: {"records": ["rec-x-daughter"]},
  },
  {
    id: "b-2.B",
    kind: "arrival",
    w: 2,
    o: 6,
    name: "The rod",
    line: "You lift the rod from the shelf. It is warm, and heavier than its size suggests. A line of marks runs along the handle in a hand unlike the tally’s; in the corner of the last cell is a hook with a tail. Beneath the shelf, in pencil: For the next one. Cut the two marks on the lintel. Don’t be precious about it.",
    req: ["b-2.1"],
    stretch: "st-camp",
    painting: "pt-b-2.B",
    carries: {"records": ["rec-l4"]},
  },
  {
    id: "b-w2.camp",
    kind: "camp",
    w: 2,
    o: 7,
    line: "The cups run away from the lamp at head height, one after another into the dark. In every one, the flame’s mark remains unlit.",
    req: [],
    stretch: "st-hall",
    morning: "the mark on the map: the lintel marked as a door",
  },
  {
    id: "b-w2.close",
    kind: "close",
    w: 2,
    o: 9,
    line: "The blank in the lintel is exactly the width of the rod’s edge.",
    req: [],
    stretch: "st-hall",
  },
  // ---- Week 3 ----
  // NOTE: for this word, `line` is the wake shown after the fourth tap (no field for "after the taps").
  {
    id: "b-3.A",
    kind: "word",
    w: 3,
    o: 1,
    name: "The lintel",
    line: "Then the lamp-cups take fire one after another: a hand of them, then more, running the length of the hall and round the corner. The stone beneath the lintel is gone. Beyond it lies a landing and a stair descending from it. The landing is already lit. You did not light it.",
    taps: ["You set the rod’s edge in the blank.", "You cut the first mark, the flame’s.", "You cut the second, the hook and the drop.", "Light runs through the cuts. The rod rings once, low, like a struck pipe."],
    req: ["b-2.B", "mk-give"],
    stretch: "st-hall",
    painting: "pt-b-3.A",
    carries: {"word": "wd-light"},
  },
  {
    id: "b-3.1",
    kind: "step",
    w: 3,
    o: 2,
    line: "Farther along the Salt Gallery, beyond the last of her sheets, the tally continues. Halfway down this unread stretch, the flame’s mark and the hook-and-drop are cut together in one cell.",
    req: ["b-3.A"],
    stretch: "st-salt",
    carries: {"records": ["rec-s3"], "inView": ["seal-3-2"]},
  },
  {
    id: "b-3.2",
    kind: "step",
    w: 3,
    o: 3,
    line: "You open the notebook at Day 6.",
    req: ["b-3.1"],
    stretch: "st-camp",
    carries: {"records": ["rec-l5"]},
  },
  // NOTE: req b-3.A is physical access (the Stair lies beyond the lintel), added so the skip rule cannot play it first.
  {
    id: "b-3.B",
    kind: "arrivalKey",
    w: 3,
    o: 4,
    name: "The head of the Stair",
    line: "The landing is broad. A niche beside it carries a count, and the count fills. The top flight drops away into light already burning below. On the niche lid, a small tablet shows a carved doorway beside one mark and a carved bar beside another. Inside stands a second clay lamp, unlit, its glaze unchipped.",
    seal: "seal-3-1",
    req: ["b-3.A"],
    stretch: "st-stair",
    painting: "pt-b-3.B",
    carries: {"guess": ["mk-here", "mk-door"]},
  },
  {
    id: "b-3.3",
    kind: "step",
    w: 3,
    o: 5,
    line: "With the hall lit, you examine the lamp on the ledge again. Its base carries the flame, the hook-and-drop and a bar with a tick; in the corner is a hook closed on a dot.",
    req: ["b-3.B"],
    stretch: "st-hall",
    carries: {"records": ["rec-k1"]},
  },
  // NOTE: req b-3.A is physical access, as for b-3.B.
  {
    id: "b-3.C",
    kind: "arrival",
    w: 3,
    o: 6,
    name: "The top flight",
    line: "The stair is wide enough for three people abreast, but each step rises higher than a step should. At the first turn, a rail has been cut from the wall itself and worn smooth along the top. Beside it is another niche with a count.",
    choice: ["Go down", "go back to the tally"],
    req: ["b-3.A"],
    stretch: "st-stair",
    painting: "pt-b-3.C",
    carries: {"inView": ["seal-4-1"]},
  },
  {
    id: "b-3.4",
    kind: "deep",
    w: 3,
    o: 7,
    line: "A small counted door stands on the second flight. It is shut; a finger’s width of darkness shows along one edge. Beside it, among rings worn smooth, one ring is newly sharp. The stair continues below, and farther on a wedge is cut alone into the wall.",
    req: ["b-3.C"],
    stretch: "st-flight2",
    carries: {"records": ["rec-k2"], "seen": ["mk-deep"], "partial": "wedge"},
  },
  {
    id: "b-w3.camp",
    kind: "camp",
    w: 3,
    o: 8,
    line: "The hall is lit now as far as the corner. Beyond the turn, the glow lies across the salt.",
    req: [],
    stretch: "st-hall",
    morning: "S1 re-rendered with HERE and DOOR",
  },
  {
    id: "b-w3.close",
    kind: "close",
    w: 3,
    o: 10,
    line: "On the second flight below, a small door carries a count.",
    req: [],
    stretch: "st-stair",
  },
  // ---- Week 4 ----
  {
    id: "b-4.1",
    kind: "step",
    w: 4,
    o: 1,
    line: "You descend the top flight to its first turn. A second flight continues below, with a small counted door set into it. Beneath the next turn is a recess with a count of its own.",
    req: [],
    stretch: "st-stair",
    carries: {"inView": ["seal-5-1"]},
  },
  {
    id: "b-4.2",
    kind: "stepKey",
    w: 4,
    o: 2,
    line: "At the first turn, the count on the second niche fills. A tablet rests on its lid: a wedge beside the picture of a well.",
    seal: "seal-4-1",
    req: [],
    stretch: "st-stair",
    carries: {"guess": ["mk-deep"]},
  },
  {
    id: "b-4.3",
    kind: "step",
    w: 4,
    o: 3,
    line: "You open the notebook at Day 9.",
    req: [],
    stretch: "st-camp",
    carries: {"records": ["rec-l6"]},
  },
  {
    id: "b-4.A",
    kind: "arrival",
    w: 4,
    o: 4,
    name: "The sheet dated Day 9",
    line: "You follow the tally beyond the lone ring until it passes beneath a crust of salt carrying a count. Her Day 9 sheet belongs to this stretch. In pencil: …go home… he held me… go… lamp… gave… went up… salt… stones…",
    req: ["b-3.1"],
    stretch: "st-salt",
    painting: "pt-b-4.A",
    carries: {"records": ["rec-s4"], "inView": ["seal-5-2"]},
  },
  {
    id: "b-4.4",
    kind: "step",
    w: 4,
    o: 5,
    line: "Every record along the tally carries a hook closed on a dot in its corner; the same mark is cut on the lamp’s base. She copied it onto her sheet and wrote: signature? The corner mark on the wall by the lamp is not this hook.",
    req: ["b-4.A"],
    stretch: "st-salt",
    carries: {"seen": ["mk-hand"]},
  },
  {
    id: "b-4.B",
    kind: "arrivalKey",
    w: 4,
    o: 6,
    name: "The salt block",
    line: "Past the split, a niche bears a count. When it fills, a block of salt is revealed inside. Cut into its face is a hook closed on a dot, the size of a thumbnail. A short line in the tally’s hand is cut into the wall beside it.",
    seal: "seal-4-2",
    req: [],
    stretch: "st-salt",
    painting: "pt-b-4.B",
    carries: {"records": ["rec-x-neighbour"]},
  },
  // NOTE: inView seal-4-4 (the Lower Door's count: seen, not sealed, NICHES 4.4).
  {
    id: "b-4.C",
    kind: "arrival",
    w: 4,
    o: 7,
    name: "The Lower Door, close",
    line: "The great door fills the far end of the hall. Every stroke of its count is empty. Beside a blank are two marks: the bar-with-a-drop and two drops parted. Beneath the count is another mark, like a path doubling back.",
    req: [],
    stretch: "st-hall",
    painting: "pt-b-4.C",
    carries: {"inView": ["seal-4-4"]},
  },
  {
    id: "b-w4.camp",
    kind: "camp",
    w: 4,
    o: 8,
    line: "By the lamp, you turn its base towards the light. Three marks are cut there. One is the mark that begins every line of the tally.",
    req: [],
    stretch: "st-hall",
    morning: "the different hook on the wall by the lamp, highlighted once",
  },
  {
    id: "b-w4.close",
    kind: "close",
    w: 4,
    o: 10,
    line: "The Lower Door carries two marks beside a count whose every stroke is empty.",
    req: [],
    stretch: "st-hall",
  },
  // ---- Week 5 ----
  {
    id: "b-5.0",
    kind: "step",
    w: 5,
    o: 1,
    line: "On the second flight, every stroke of the little door’s count is full. The door remains shut. Beside it, among thousands of rings worn smooth, one ring still has sharp edges.",
    req: [],
    stretch: "st-flight2",
    carries: {"records": ["rec-k2"]},
  },
  {
    id: "b-5.1",
    kind: "stepKey",
    w: 5,
    o: 2,
    line: "The count on the recess beneath the second turn fills. Inside is a tablet: a bar-and-tick beside a setting sun, a bar-with-a-drop beside a road, and the same bar again with its drop at the far end.",
    seal: "seal-5-1",
    req: [],
    stretch: "st-flight2",
    carries: {"guess": ["mk-once", "mk-path", "mk-go"]},
  },
  {
    id: "b-5.A",
    kind: "arrival",
    w: 5,
    o: 3,
    name: "The tally, from the head",
    line: "Every record in the tally begins with the same sequence: a bar with a tick, a ring, a single drop. The line on the wall by the lamp is different. There, the bar with a tick comes second.",
    choice: ["Look at the first stretch again", "look at the wall by the lamp"],
    req: ["seal-5-1"],
    stretch: "st-salt",
    painting: "pt-b-5.A",
  },
  {
    id: "b-5.2",
    kind: "step",
    w: 5,
    o: 4,
    line: "You open the notebook at Day 14.",
    req: ["b-5.A"],
    stretch: "st-camp",
    carries: {"records": ["rec-l7"]},
  },
  {
    id: "b-5.B",
    kind: "arrival",
    w: 5,
    o: 5,
    name: "Through a gap",
    line: "At shoulder height on the second flight, a gap has been cut through the wall. Beyond it is another gallery, where square-cut stone meets the rounded work of the stair. A record in the tally’s hand is cut on the square wall. It begins with the same three marks, except that where the tally has one drop, this has two.",
    req: [],
    stretch: "st-flight2",
    painting: "pt-b-5.B",
    carries: {"records": ["rec-v1"]},
  },
  {
    id: "b-5.3",
    kind: "stepKey",
    w: 5,
    o: 6,
    line: "The count on the salt crust fills, exposing another stretch of the tally. Three marks stand together there: the lamp’s, the flame’s and the hook-and-drop’s. No doorway-shape is anywhere near them.",
    seal: "seal-5-2",
    req: [],
    stretch: "st-salt",
    carries: {"records": ["rec-s5"]},
  },
  {
    id: "b-w5.camp",
    kind: "camp",
    w: 5,
    o: 7,
    line: "The lamp burns at your side. On its base: the flame, the hook-and-drop, the bar with a tick.",
    req: [],
    stretch: "st-hall",
    morning: "L8 next",
  },
  {
    id: "b-w5.close",
    kind: "close",
    w: 5,
    o: 9,
    line: "Below, the stair meets a gallery made of square-cut stone.",
    req: [],
    stretch: "st-flight2",
  },
  // ---- Week 6 ----
  {
    id: "b-6.A",
    kind: "arrival",
    w: 6,
    o: 1,
    name: "The side passage",
    line: "A low doorway at the Stair’s second landing opens into the gallery you saw through the gap. Here the walls meet at corners. Where square stone meets rounded stone, the two works have been cut into one another like clasped hands. Up close, the square-wall record reads: …way [ ] [ ] here [ ] once… person [ ] went deep [ ]; fire. One went deep. A lamp, lit. One other.",
    choice: ["Read it", "go on"],
    req: ["b-5.B"],
    stretch: "st-square",
    painting: "pt-b-6.A",
    carries: {"records": ["rec-v1"]},
  },
  {
    id: "b-6.1",
    kind: "step",
    w: 6,
    o: 2,
    line: "You open the notebook at Day 20. Small chips of stone lie in the gutter between the pages.",
    req: ["b-6.A"],
    stretch: "st-camp",
    carries: {"records": ["rec-l8"]},
  },
  {
    id: "b-6.2",
    kind: "stepKey",
    w: 6,
    o: 3,
    line: "At the Salt Gallery’s last hidden stretch, the count on the crust fills. Behind it lies a tablet. A doorway is carved beside two drops parted; beside a loaf is a hook closed on a drop over a bar. Beyond the tablet, the tally continues.",
    seal: "seal-6-1",
    req: [],
    stretch: "st-salt",
    carries: {"guess": ["mk-open", "mk-eat"]},
  },
  {
    id: "b-6.B",
    kind: "arrivalKey",
    w: 6,
    o: 4,
    name: "The crew's wall",
    line: "A second record, longer than the first, is cut into the square wall in the tally’s hand: …one ate [ ], person [ ]… [ ] [ ] one: way [ ] [ ] [ ]… gave [ ] [ ] [ ]; door open… person [ ] gave [ ]. One span appears on her sheets: …he held us…. Beneath the record is a counted niche. It fills. Inside lies a wax tablet gone hard, ruled into rows, a ring at the head of each.",
    choice: ["Read the record", "look at the tablet"],
    seal: "seal-6-2",
    req: [],
    stretch: "st-square",
    painting: "pt-b-6.B",
    carries: {"records": ["rec-v2", "rec-x-foreman"]},
  },
  {
    id: "b-6.3",
    kind: "step",
    w: 6,
    o: 5,
    line: "A mule-shoe lies on the gallery floor. Beside it is a stone worn by the rub of a halter. Above the stone, a short line is cut into the wall: [ ]: [a mule] went deep [ ]; me [ ] [ ].",
    req: ["b-6.B"],
    stretch: "st-square",
    carries: {"records": ["rec-x-mule"], "inView": ["seal-6-4"]},
  },
  {
    id: "b-w6.camp",
    kind: "camp",
    w: 6,
    o: 6,
    line: "From beside the lamp, you look at the lamp carved on the wall. Its cuts are still sharp.",
    req: [],
    stretch: "st-hall",
    morning: "S2 re-rendered: ate [ ] now shows the sign for EAT in Dan’s layer",
  },
  {
    id: "b-w6.close",
    kind: "close",
    w: 6,
    o: 8,
    line: "Down the second flight, a lintel stands over solid stone. Beside its blank are two marks; one is the path’s.",
    req: [],
    stretch: "st-flight2",
  },
  // ---- Week 7 ----
  {
    id: "b-7.1",
    kind: "stepKey",
    w: 7,
    o: 1,
    line: "A niche in the square gallery fills its count. Inside is a tablet: an inverted wedge beside the sky, a wedge on a bar beside a block, and a small figure beside a child’s tablet.",
    seal: "seal-7-1",
    req: [],
    stretch: "st-square",
    carries: {"guess": ["mk-up", "mk-stone", "mk-child"]},
  },
  {
    id: "b-7.A",
    kind: "word",
    w: 7,
    o: 2,
    name: "The lintel at the foot of the second flight",
    taps: ["You set the rod’s edge in the blank.", "You cut the first mark, the bar with a drop.", "You cut the second, the two drops parted.", "Light fills the cuts and the rod gives one low ring. The stone beneath the lintel is gone. Beyond it, the Stair continues down through light."],
    req: ["seal-7-1", "mk-path", "mk-open"],
    stretch: "st-flight2",
    painting: "pt-b-7.A",
    carries: {"word": "wd-open-way"},
  },
  {
    id: "b-7.2",
    kind: "step",
    w: 7,
    o: 3,
    line: "Past the crust the tally goes on. In it a barn is carved, and in the barn an owl, cut by someone who has not seen one: …[ ] gave child: up [a barn] [an owl] here… ate [ ]; [ ] [ ]; [ ]… child [ ]: [ ] [ ]…",
    req: ["b-7.A"],
    stretch: "st-salt",
    carries: {"records": ["rec-s6"]},
  },
  // NOTE: ARR2 carries V3 and X-boy here; MVP_CONTENT §4 gives them no rec- ids, so records are left out.
  {
    id: "b-7.B",
    kind: "arrivalKey",
    w: 7,
    o: 4,
    name: "The crew's wall, again",
    line: "Below the second record are twelve rings in a row and, after them, a smaller thirteenth: …person [ ], child one [a tablet]… The niche beneath fills its count. Inside is a wax tablet gone hard, carrying twenty marks. Some are backwards. One is a fork with nothing under it. Beside three, the tally’s hand has cut the same three correctly—not over them, but alongside.",
    seal: "seal-7-2",
    req: [],
    stretch: "st-square",
    painting: "pt-b-7.B",
  },
  {
    id: "b-7.3",
    kind: "stepKey",
    w: 7,
    o: 5,
    line: "At the Stair’s first turn, the count in the recess beside the rail fills. The stone where a hand rested has taken the shape of that hand. It has four fingers, and they are long.",
    seal: "seal-7-3",
    req: [],
    stretch: "st-stair",
  },
  {
    id: "b-7.4",
    kind: "stepKey",
    w: 7,
    o: 6,
    line: "In the gallery wall the count on a cache fills. Inside, in a bag gone hard, are twelve bronze coins and one clay token, and beside the cache is a line: Once, [ ] gave me [a bag]: [ ] person [ ], child one; [ ] [ ]. [ ] door once, [ ] [ ] [ ]. I [ ] it.",
    seal: "seal-7-4",
    req: [],
    stretch: "st-square",
  },
  // NOTE: a Key arrival that is also the word again: kind 'word' with `seal`; `line` is the preface shown before the taps.
  {
    id: "b-7.C",
    kind: "word",
    w: 7,
    o: 7,
    name: "The great door",
    line: "At the far end of the hall, beside the door’s blank, are the same two marks as the lintel’s, and under them is the count.",
    taps: ["You set the rod’s edge in the blank.", "You cut the first mark, the bar with a drop.", "You cut the second, the two drops parted.", "The count fills stroke by stroke. The door is not there. Beyond, a stair drops away at twice the pitch, and the hall’s light follows it for eleven steps before stopping."],
    choice: ["Go down as far as the light", "go back along the hall"],
    seal: "seal-7-5",
    req: ["b-7.A"],
    stretch: "st-hall",
    painting: "pt-b-7.C",
    carries: {"word": "wd-open-way"},
  },
  {
    id: "b-w7.camp",
    kind: "camp",
    w: 7,
    o: 8,
    line: "You sit beside the lamp. At the far end of the hall, the great door stands open, and cold air rises through it.",
    req: [],
    stretch: "st-hall",
    morning: "the map: two ways down, both ending in the dark",
  },
  {
    id: "b-w7.close",
    kind: "close",
    w: 7,
    o: 10,
    line: "Both ways down reach water. The water does not move.",
    req: [],
    stretch: "st-hall",
  },
  // ---- Places with no fragment (MVP_CONTENT §2) ----
  {
    id: "pl-w1-pick-niche",
    kind: "arrival",
    w: 1,
    o: 3,
    name: "The pick niche",
    line: "Low in the Salt Gallery wall is an arm-long niche. A row of cut strokes runs along its lip, every stroke empty. Beside it, the salt is scored with close, short cuts.",
    req: [],
    stretch: "st-salt",
    painting: "pt-pl-w1-pick-niche",
    carries: {"inView": ["seal-1-2"]},
  },
  {
    id: "pl-w1-below-the-lamp",
    kind: "arrival",
    w: 1,
    o: 5,
    name: "Below the lamp",
    line: "Below the ledge, at knee height, a small niche is cut into the wall. Empty strokes run along its lip. The stone around the mouth is darker than the rest and greasy under your fingers.",
    req: [],
    stretch: "st-hall",
    painting: "pt-pl-w1-below-the-lamp",
    carries: {"inView": ["seal-1-3"]},
  },
  {
    id: "pl-w2-above-the-ring",
    kind: "arrival",
    w: 2,
    o: 2,
    name: "Above the ring",
    line: "Above the lone ring, a crack two fingers wide opens in the salt. A small count is cut beside it. Something pale lies far back inside, beyond reach.",
    req: ["seal-1-1"],
    stretch: "st-salt",
    painting: "pt-pl-w2-above-the-ring",
    carries: {"inView": ["seal-2-3"]},
  },
  // NOTE: §2 names "the corner's troughs" here; inView is seal-2-4, the seen-not-sealed smooth place NICHES 2.4 says this place is.
  {
    id: "pl-w2-smooth-place",
    kind: "arrival",
    w: 2,
    o: 4,
    name: "The smooth place",
    line: "At the corner, one patch of the polished wall is bare of marks at the height of a long hand. The stone has been rubbed smooth there, like a banister.",
    req: ["b-1.B"],
    stretch: "st-hall",
    painting: "pt-pl-w2-smooth-place",
    carries: {"inView": ["seal-2-4"]},
  },
  {
    id: "pl-w2-box-by-the-cot",
    kind: "arrival",
    w: 2,
    o: 5,
    name: "The box by the cot",
    line: "A shoebox-sized box is pushed against the wall of her camp. A thin slate lies across the lid with a count cut into it. An upside-down tin mug stands on the slate.",
    req: ["b-1.C"],
    stretch: "st-camp",
    painting: "pt-pl-w2-box-by-the-cot",
    carries: {"inView": ["seal-2-5"]},
  },
  {
    id: "pl-w3-salt-lit",
    kind: "arrival",
    w: 3,
    o: 3,
    name: "The salt, lit",
    line: "Light from the hall comes round the corner and catches the salt in bands of grey and pink. The packed stones in the split are round, brown river stones, carried up from somewhere with water.",
    req: ["b-3.A"],
    stretch: "st-salt",
    painting: "pt-pl-w3-salt-lit",
  },
  {
    id: "pl-w3-far-end",
    kind: "arrival",
    w: 3,
    o: 5,
    name: "The far end",
    line: "The last lamp is a stride from the great door. Its light climbs partway up the stone, but the door continues beyond it into the curve of the ceiling. Cold comes off the face of it like cold from a window in winter.",
    req: ["b-3.A"],
    stretch: "st-hall",
    painting: "pt-pl-w3-far-end",
  },
  {
    id: "pl-w4-hollow",
    kind: "arrival",
    w: 4,
    o: 2,
    name: "The hollow",
    line: "Low in the salt is a hollow the size of two cupped hands, smooth from wear. A count runs round its rim. At the bottom, the salt has been pressed flat in four small places.",
    req: [],
    stretch: "st-salt",
    painting: "pt-pl-w4-hollow",
    carries: {"inView": ["seal-4-5"]},
  },
  {
    id: "pl-w4-recess-above-the-cot",
    kind: "arrival",
    w: 4,
    o: 4,
    name: "The recess above the cot",
    line: "Above the cot, at the height of a raised arm, a recess is closed by a counted slate. A drawing pin has been pushed into a crack beside it, with nothing pinned beneath.",
    req: ["b-1.C"],
    stretch: "st-camp",
    painting: "pt-pl-w4-recess-above-the-cot",
    carries: {"inView": ["seal-4-3"]},
  },
  {
    id: "pl-w5-ledge-lip",
    kind: "arrival",
    w: 5,
    o: 2,
    name: "The ledge's lip",
    line: "The underside of the lamp’s ledge is cut as well. A small count sits there, low enough to be invisible to anyone standing.",
    req: [],
    stretch: "st-hall",
    painting: "pt-pl-w5-ledge-lip",
    carries: {"inView": ["seal-5-5"]},
  },
  {
    id: "pl-w5-worn-steps",
    kind: "arrival",
    w: 5,
    o: 3,
    name: "The worn steps",
    line: "Halfway down the top flight, each step is worn in two places a stride apart. The stride is longer than yours. The rail beside them has been polished along its top.",
    req: ["b-3.C"],
    stretch: "st-stair",
    painting: "pt-pl-w5-worn-steps",
  },
  {
    id: "pl-w5-second-landing",
    kind: "arrival",
    w: 5,
    o: 5,
    name: "The second landing",
    line: "The second flight turns onto a landing as broad as the hall above, its wall lamps already lit. Across from the stair is a square-cornered doorway, too low for whoever made the Stair.",
    req: ["b-4.1"],
    stretch: "st-flight2",
    painting: "pt-pl-w5-second-landing",
  },
  {
    id: "pl-w6-square-gallery",
    kind: "arrival",
    w: 6,
    o: 2,
    name: "The square gallery",
    line: "The gallery runs perfectly straight, no taller than a tall man. Its ceiling is flat, its walls covered in small, even chisel marks. There are no lamp-cups here. Light enters from the rounded stone behind you and thins away. Far ahead, the floor disappears beneath a slope of broken stone.",
    req: ["b-6.A"],
    stretch: "st-square",
    painting: "pt-pl-w6-square-gallery",
  },
  {
    id: "pl-w6-wall-shelf",
    kind: "arrival",
    w: 6,
    o: 4,
    name: "The wall-shelf",
    line: "A shelf is cut into the square wall at chest height, with a count on its lip. Someone has scratched a dead-level line along the edge, ending it with a short tick at either side.",
    req: ["pl-w6-square-gallery"],
    stretch: "st-square",
    painting: "pt-pl-w6-wall-shelf",
    carries: {"inView": ["seal-6-3"]},
  },
  {
    id: "pl-w6-folder",
    kind: "arrival",
    w: 6,
    o: 5,
    name: "Her folder",
    line: "Under the cot, pushed hard against the back wall, is a document folder held shut by an elastic band. A thin counted slate lies over its cover. HILL is written on the spine in marker.",
    req: ["b-1.C"],
    stretch: "st-camp",
    painting: "pt-pl-w6-folder",
    carries: {"inView": ["seal-6-5"]},
  },
];
