/**
 * SEALED STORY CONTENT (D-015). Never shown to Dan outside the game.
 * Transcribed from docs/narrative/sealed/ (ARRIVALS_REGION1.md weeks 1-5, ARRIVALS_REGION2.md weeks 6-7,
 * MVP_CONTENT.md §0-§3). Those files are authoritative; fix them first, then this.
 */
import type { Beat } from '../../core/story-types';

/** Story beats (ARR rows; `o` = the row's position in its week's ARR table, teaser rows counted but not included), then the 15 `pl-` places (`o` = route position, MVP_CONTENT §2). */
export const beats: Beat[] = [
  // ---- Week 1 ----
  {
    id: "b-w1.morning",
    kind: "morning",
    w: 1,
    o: 1,
    line: "You are standing in a field on the side of a hill. The grass rises about your legs, then falls away down the slope; there is no level ground around the iron cap. Among the grass lies an iron cap the size of a table. The iron has a dull, weathered face. Its padlock is on the ground beside it, cut. The severed shackle makes a little gap where the closed curve ought to be. You can see both pieces from where you stand. The hill goes on above you, and the opening under the cap is still out of sight.",
    req: [],
    stretch: "st-mouth",
  },
  {
    id: "b-1.1",
    kind: "step",
    w: 1,
    o: 2,
    line: "The shaft cap has been lifted aside. Its padlock lies next to it, the shackle cut clean through. Two notices remain fixed to the cap: an old enamel one, its name worn away to nothing, saying DANGER OF FALLING, and a new laminated one with a phone number. The enamel has kept its warning after losing the name; the laminate has a different, thin sheen against the iron. Below them, eleven metres of ladder descend into dry air. You can follow the rungs downward for a while before their spacing becomes hard to separate. The cut in the shackle is neat enough to see even here, beside the much larger work of moving the cap.",
    req: [],
    stretch: "st-mouth",
  },
  {
    id: "b-1.2",
    kind: "step",
    w: 1,
    o: 3,
    line: "At the foot of the ladder the brickwork ends and a passage begins. The end of the brickwork is distinct: its little courses stop where the larger, continuous surface takes over. Floor and walls run together in a single curve, like the inside of a pipe; nowhere is there a tool-mark. Your feet find no corner at the base of either wall. Twenty paces on, the passage widens. It does so gradually enough that you feel the change in the space beside your shoulders before you can point to a place where the narrow passage ends.",
    req: [],
    stretch: "st-mouth",
  },
  {
    id: "b-1.A",
    kind: "arrival",
    w: 1,
    o: 4,
    name: "The Lamp Hall",
    line: "The hall rises long and high, its edges rounded like the inside of a shell. The passage has prepared you for the curve, but not for the height: there is room above your head that the lamp cannot wholly account for. At the near end, on a ledge, a clay lamp is burning. It was lit when you came down. There is no oil in it. The clay is small against the breadth of the hall, and its flame makes a little centre from which the rest of the place must be measured. Cups are cut into both walls at head height, one every few paces, all empty. Their repetition leads your eye along the curve before the darkness takes them. Marks cover every surface within reach, with rings among them. Some crowd close to the ledge; others carry on wherever your hand could touch. At the far end, beyond the light, a door occupies most of the wall. Its width is easier to grasp than its height. You can see enough of it to know that the wall closes around it, and too little to judge how far the curve rises above.",
    choice: ["Look at the lamp", "look at the wall"],
    req: [],
    stretch: "st-hall",
    painting: "pt-b-1.A",
    carries: {"records": ["rec-l1", "rec-k1"], "seen": ["mk-ring"]},
  },
  {
    id: "b-1.3",
    kind: "step",
    w: 1,
    o: 5,
    line: "Close to the lamp, the wall resolves into deliberate cuts. A lamp is carved there, shaped like the one on the ledge, with a single mark beside it. The likeness holds in the shape of the little body, not simply in its place so near the flame. Below it is a carved flame, and beside the flame another mark. You have to attend to the depth of the cuts to keep the carved flame distinct from the shifting fire beside you. The two marks occupy separate places, each beside its own carving. Their positions are as plain as the difference between the clay standing out from the ledge and the lamp sunk into stone.",
    req: ["b-1.A"],
    stretch: "st-hall",
    carries: {"records": ["rec-l1"], "guess": ["mk-lamp"]},
  },
  {
    id: "b-1.4",
    kind: "step",
    w: 1,
    o: 6,
    line: "Seen close, the flame’s mark is two cuts that spread apart from a single point. At the point they are narrow enough to seem nearly one incision; farther out, stone remains between them. The lamp’s mark has the same two cuts, set inside a cup. You can trace the difference with your eye without touching the wall: the same opening pair, then the boundary around one of them. The carved lamp and carved flame sit close enough for you to compare them without losing your place. The cuts remain distinct despite all the other marks covering the hall.",
    req: ["b-1.A"],
    stretch: "st-hall",
    carries: {"records": ["rec-l1"], "guess": ["mk-fire"]},
  },
  {
    id: "b-1.B",
    kind: "arrival",
    w: 1,
    o: 7,
    name: "The corner",
    line: "At the turn of the hall, two long troughs have been worn into the floor a stride apart. Each follows the bend rather than crossing it, so that you stand between them and see them disappear round the curve. Beside them the wall is polished smooth to the shoulder height of a man, if that man were twice your size; the marks there have been rubbed faint. Above the rubbed area their cuts remain easier to pick out. You can set your own shoulder against the height in your mind, but it does little to make the scale comfortable. Past the turn another gallery opens. The air smells of salt. It reaches you before the gallery offers up much of its shape, distinct even as the bend conceals the next length of wall.",
    req: [],
    stretch: "st-hall",
    painting: "pt-b-1.B",
  },
  {
    id: "b-1.5",
    kind: "step",
    w: 1,
    o: 8,
    line: "This is the Salt Gallery, where the hill’s rock salt meets the cut stone. The join is irregular; the worked curve comes against a face whose grain runs its own way. The salt face is split from the top to knee height, the opening packed from the other side with stones and salt. The packing has a different, broken surface from the unbroken face around it. A line of marks runs the length of the gallery, all cut by one hand. Even where salt interrupts your view, the spacing invites you to follow its course. Beside it, loose sheets of paper have been tucked into a crack and dated in pencil: Day 1, Day 4, Day 9. The paper stands a little proud of the crack, thin against the mass of the wall.",
    choice: ["Look at the wall", "Look at her sheets"],
    req: ["b-1.B"],
    stretch: "st-salt",
    carries: {"records": ["rec-s1"]},
  },
  {
    id: "b-1.6",
    kind: "stepKey",
    w: 1,
    o: 9,
    line: "Where the first stretch of the line ends, a row of strokes is cut directly into the salt. The cuts behave differently here from those in stone: their edges break into little grains, though the strokes remain clear. The first stroke is full of light now. Its brightness makes the unfilled strokes beside it appear deeper. Beyond it the marks continue into darkness. You can follow the beginning of their course, then lose the individual cuts while still seeing where the salt face goes. The row sits at the meeting of what you can count and what you cannot yet make out.",
    seal: "seal-1-1",
    req: [],
    stretch: "st-salt",
  },
  // NOTE: inView includes seal-1-4 (her boots: seen, not sealed, NICHES 1.4) as well as the tin box.
  {
    id: "b-1.C",
    kind: "arrival",
    w: 1,
    o: 10,
    name: "The Survey Cut",
    line: "Someone lived in this side chamber. A camp cot stands against the wall; beneath it, a pair of dry, laced boots have been placed neatly side by side, ready for morning. Their toes point the same way, their laces held close against the leather. On the cot are a notebook with a pencil tucked into it and a tin box whose lid carries a row of cut strokes. The strokes give the small box a surface quite unlike the plain tin around them. A stone rod rests on the shelf, forearm-long, one edge finer than a knife’s. Its length is easy to measure against your own arm; its edge is harder to reconcile with stone. The chamber has the close proportions of a place where a person could lie down. The ordered boots and the objects within reach of the cot occupy that space more fully than its walls do.",
    choice: ["Open the notebook", "look at the shelf"],
    req: [],
    stretch: "st-camp",
    painting: "pt-b-1.C",
    carries: {"records": ["rec-l2"], "inView": ["seal-1-4", "seal-2-1"]},
  },
  // NOTE: deep beats take the steps rule (nearest arrival above) as their req.
  {
    id: "b-1.7",
    kind: "deep",
    w: 1,
    o: 11,
    line: "On the lamp’s side, away from the three marks on its base, a hook, open, is cut on its own. You have to turn your attention from the crowded base to find it. The isolated cut has room around it on the clay, so its open end is easy to distinguish. The rest of the cell is bare. You can see the grain of the lamp's fired surface where there are no cuts, and the shallow change where this one enters it. Its placement on the side matters to what you can see at once: the three below, and this one apart.",
    req: ["b-1.C"],
    stretch: "st-hall",
    carries: {"seen": ["mk-give"], "partial": "hook"},
  },
  {
    id: "b-w1.camp",
    kind: "camp",
    w: 1,
    o: 12,
    line: "You sit beside the lamp. When the flame moves, the rings on the wall behind it take the light one by one. The nearest ring has a complete bright edge for an instant; the next catches only part of its curve before the flame settles. Sitting here fixes the distance between the small clay lamp and the much larger wall, so that the movement seems to travel across the cuts although nothing on the stone has shifted. The ledge is close enough for its warmth to reach your hand. Above it the rings climb only as far as the uncertain boundary of the light.",
    req: [],
    stretch: "st-hall",
    morning: "a line of the salt tally re-rendered with your two guesses",
  },
  {
    id: "b-w1.close",
    kind: "close",
    w: 1,
    o: 14,
    line: "A lintel stands on the side wall, but beneath it there is no doorway: only stone. Its upper edge makes the absence below it harder to ignore. Two marks are cut beside it with a blank between them. One is the flame’s. The blank has a width you can compare with the neighbouring cuts, an interval left in a place otherwise carefully worked. The stone below the lintel has no seam you can follow. You can stand squarely before it and see a doorway's outline implied above, while the wall beneath remains solid.",
    req: [],
    stretch: "st-hall",
  },
  // ---- Week 2 ----
  // NOTE: stepKey beats take no arrival req; their seal being in view (Key rule, MVP_CONTENT §0.2) governs them.
  {
    id: "b-2.1",
    kind: "stepKey",
    w: 2,
    o: 1,
    line: "On the cot, the count cut into the tin box’s lid fills. The lid lifts. Inside are more sheets; on one, four marks have been drawn large. Their pencil lines are broad enough to show the shapes separately, away from the crowded cuts in the hall. Three have pencilled words beneath them. Beneath the fourth is only a question mark. You can hold the sheet so that all four fit in view at once. The question mark occupies exactly the same position as the three words do under the others, a small, plain admission on otherwise ordered paper.",
    seal: "seal-2-1",
    req: [],
    stretch: "st-camp",
    carries: {"guess": ["mk-person", "mk-one", "mk-me"]},
  },
  {
    id: "b-2.2",
    kind: "step",
    w: 2,
    o: 2,
    line: "At the side-wall lintel, two marks flank a blank. One is the flame’s mark. The other is a hook, and a drop leaving it. Under the lintel there is still no door, only stone. The two cuts are placed at either side of the uncut space, near enough to compare and far enough apart that the empty part has its own extent. At the base of the lintel the face of the wall carries on without a join. You can look up at the worked stone and down at the solid surface below without finding an opening between them.",
    req: ["seal-2-1"],
    stretch: "st-hall",
    carries: {"guess": ["mk-give"]},
  },
  {
    id: "b-2.A",
    kind: "arrival",
    w: 2,
    o: 3,
    name: "The Salt Gallery, further in",
    line: "Beyond the inner count the tally continues in the same hand. The intervals in the line retain their familiar measure even as this stretch enters a part of the gallery you have not read. Above it, set apart and larger than the others, is a single ring. Its curve has more space around it than the tightly placed marks below, and its position makes you raise your head. Her sheets do not cover the next stretch. The last pencil-covered portion ends while the cut line continues along the salt. The difference in their lengths is visible without handling either surface. You can compare the paper with the wall up to that boundary; after it, there is only the worked surface itself and the lone ring above.",
    choice: ["Read the tally", "look at the ring"],
    req: [],
    stretch: "st-salt",
    painting: "pt-b-2.A",
    carries: {"records": ["rec-s2"]},
  },
  {
    id: "b-2.3",
    kind: "step",
    w: 2,
    o: 4,
    line: "You open the notebook at Day 3. The pencil is caught between the leaves, so the pages separate with a slight resistance. The date gives you a position among the loose sheets, though this page remains in the bound book. You steady it on the cot to keep the fold flat. Its paper has the slight unevenness of sheets turned and held before; the pencilled heading is plain. For a moment the whole chamber narrows to the distance between the two open pages and the little space occupied by that date.",
    req: ["b-2.A"],
    stretch: "st-camp",
    carries: {"records": ["rec-l3"]},
  },
  {
    id: "b-2.4",
    kind: "stepKey",
    w: 2,
    o: 5,
    line: "The count on the tally-stick’s niche fills. Inside is a stick notched in fives. Its repeated cuts are close enough to count in groups without turning it. Beside it, a short line in the tally’s hand has been cut into the wall, with a number among the marks. The stick can be held in a hand; the wall line remains fixed beside the opening. Their nearness allows you to compare the notches with the number while keeping both in view. The small hollow of the niche gives the stick a precise place within the much longer record outside it.",
    seal: "seal-2-2",
    req: [],
    stretch: "st-salt",
    carries: {"records": ["rec-x-daughter"]},
  },
  {
    id: "b-2.B",
    kind: "arrival",
    w: 2,
    o: 6,
    name: "The rod",
    line: "You lift the rod from the shelf. It is warm, and heavier than its size suggests. The weight draws your wrist down before you have quite adjusted your grip. A line of marks runs along the handle in a hand unlike the tally’s; in the corner of the last cell is a hook with a tail. The worked edge is so fine that you hold it clear of your other hand while you turn the handle. Beneath the shelf, in pencil: For the next one. Cut the two marks on the lintel. Don’t be precious about it. The words are as direct as the edge is exact. You can read them with the rod still in your hand, its unexpected warmth travelling into your palm. Between the shelf and the pencil there is just room to compare the thing you hold with the instruction below it.",
    req: ["b-2.1"],
    stretch: "st-camp",
    painting: "pt-b-2.B",
    carries: {"records": ["rec-l4"]},
  },
  {
    id: "b-w2.camp",
    kind: "camp",
    w: 2,
    o: 7,
    line: "The cups run away from the lamp at head height, one after another into the dark. In every one, the flame’s mark remains unlit. From where you sit, the first few mouths have distinct curved rims; farther along, each becomes a shallow break in the wall. The burning lamp beside you makes the emptiness of the other cups especially exact. The flame’s mark repeats inside them at intervals you can judge by the spaces between cups, though the last of those intervals vanishes before you can count them all.",
    req: [],
    stretch: "st-hall",
    morning: "the mark on the map: the lintel marked as a door",
  },
  {
    id: "b-w2.close",
    kind: "close",
    w: 2,
    o: 9,
    line: "The blank in the lintel is exactly the width of the rod’s edge. You can set the two measures against one another by sight: the narrow worked edge in your hand and the uncut interval held between the marks. The surrounding stone makes the blank visible without giving it depth. Nothing in the width requires you to guess at an approximate fit. It is a close, physical correspondence between a thing that can be lifted and a place fixed high in the side wall.",
    req: [],
    stretch: "st-hall",
  },
  // ---- Week 3 ----
  // NOTE: for this word, `line` is the wake shown after the fourth tap (no field for "after the taps").
  {
    id: "b-3.A",
    kind: "word",
    w: 3,
    o: 1,
    name: "The lintel",
    line: "Then the lamp-cups take fire one after another: a hand of them, then more, running the length of the hall and round the corner. At first you can keep pace with each new flame. Then there are too many lit places to hold separately, and the curve of the hall, previously lost at intervals, stands out in a continuous length. The stone beneath the lintel is gone. Where it had run without a seam, there is open space beneath the worked upper stone. Beyond it lies a landing and a stair descending from it. The landing is already lit. You did not light it. From the hall you can see the first drop of the stair without yet seeing how far it goes. Behind you the lit cups follow the wall round the bend; before you is light in a place the lamp on its ledge could never have reached.",
    taps: ["You set the rod’s edge in the blank.", "You cut the first mark, the flame’s.", "You cut the second, the hook and the drop.", "Light runs through the cuts. The rod rings once, low, like a struck pipe."],
    req: ["b-2.B", "mk-give"],
    stretch: "st-hall",
    painting: "pt-b-3.A",
    carries: {"word": "wd-light"},
  },
  {
    id: "b-3.1",
    kind: "step",
    w: 3,
    o: 2,
    line: "Farther along the Salt Gallery, beyond the last of her sheets, the tally continues. Its cuts keep the same measured relation to the salt face, even where there is no paper to lay beside them. Halfway down this unread stretch, the flame’s mark and the hook-and-drop are cut together in one cell. Their edges are close, but the two shapes remain separate within that boundary. You can locate the cell in the long line by looking back towards the point where the sheets end. The marks have not changed size; it is their shared space that distinguishes them from the cells on either side.",
    req: ["b-3.A"],
    stretch: "st-salt",
    carries: {"records": ["rec-s3"], "inView": ["seal-3-2"]},
  },
  {
    id: "b-3.2",
    kind: "step",
    w: 3,
    o: 3,
    line: "You open the notebook at Day 6. The bound pages give under your thumb before the dated one lies flat. The pencil tucked there has left a shallow pressure in the paper near the fold. With the notebook on the cot, you can hold the two leaves open without putting a hand across the date. Day 6 falls between the earlier page you have seen and the loose sheet dated Day 9. The gap between those numbers is easier to register here, in the quiet of the chamber, than along the crowded gallery wall.",
    req: ["b-3.1"],
    stretch: "st-camp",
    carries: {"records": ["rec-l5"]},
  },
  // NOTE: req b-3.A is physical access (the Stair lies beyond the lintel), added so the skip rule cannot play it first.
  {
    id: "b-3.B",
    kind: "arrivalKey",
    w: 3,
    o: 4,
    name: "The head of the Stair",
    line: "The landing is broad. After the width of the opening beneath the lintel, there is space here to stand well clear of the stair's edge. A niche beside it carries a count, and the count fills. The top flight drops away into light already burning below. You can see the edges of the higher steps clearly; lower down, the slope of them draws the eye beneath the level of the landing. On the niche lid, a small tablet shows a carved doorway beside one mark and a carved bar beside another. The two pictures have been placed so that each belongs to its neighbouring mark. Inside stands a second clay lamp, unlit, its glaze unchipped. You can compare its intact, smooth surface with the flame-lit clay left above in the hall. Here the unlit lamp remains inside the niche while the stair and its light continue down beyond it.",
    seal: "seal-3-1",
    req: ["b-3.A"],
    stretch: "st-stair",
    painting: "pt-b-3.B",
    carries: {"guess": ["mk-here", "mk-door"]},
  },
  {
    id: "b-3.3",
    kind: "step",
    w: 3,
    o: 5,
    line: "With the hall lit, you examine the lamp on the ledge again. Its base carries the flame, the hook-and-drop and a bar with a tick; in the corner is a hook closed on a dot. The new light from the cups reaches the underside more evenly than the small flame could. You can distinguish the three marks across the base from the one pressed into the corner without tipping the lamp far. The clay has a curve of its own, so the last cut comes into view only when you turn the base a little. Its place in the corner remains clear even when the lamp is set upright again.",
    req: ["b-3.B"],
    stretch: "st-hall",
    carries: {"records": ["rec-k1"]},
  },
  // NOTE: req b-3.A is physical access, as for b-3.B.
  {
    id: "b-3.C",
    kind: "arrival",
    w: 3,
    o: 6,
    name: "The top flight",
    line: "The stair is wide enough for three people abreast, but each step rises higher than a step should. You feel that height in the lift of your knee before the width ceases to seem generous. At the first turn, a rail has been cut from the wall itself and worn smooth along the top. It stays part of the same stone as the wall, with no join beneath your hand. Beside it is another niche with a count. The rail follows the turn while the counted opening occupies its own small place nearby. Looking back up the flight, you can judge the broad stair by its full width; facing down, the tall risers bring its scale back to your body one step at a time.",
    choice: ["Go down", "go back to the tally"],
    req: ["b-3.A"],
    stretch: "st-stair",
    painting: "pt-b-3.C",
    carries: {"inView": ["seal-4-1"]},
  },
  {
    id: "b-3.4",
    kind: "deep",
    w: 3,
    o: 7,
    line: "A small counted door stands on the second flight. It is shut; a finger’s width of darkness shows along one edge. The narrow dark strip is enough to separate the door from its surround, though it reveals nothing beyond. Beside it, among rings worn smooth, one ring is newly sharp. Your eye catches that crisp circle against the softened edges around it. The stair continues below, and farther on a wedge is cut alone into the wall. The distance down the flight keeps the wedge apart from the door and its rings: one mark by itself below, a shut opening and its count above.",
    req: ["b-3.C"],
    stretch: "st-flight2",
    carries: {"records": ["rec-k2"], "seen": ["mk-deep"], "partial": "wedge"},
  },
  {
    id: "b-w3.camp",
    kind: "camp",
    w: 3,
    o: 8,
    line: "The hall is lit now as far as the corner. Beyond the turn, the glow lies across the salt. From beside the first lamp you can see the cups occupying both walls in succession, each flame making the hall's length easier to judge. The salt beyond does not return the light evenly; some bands keep their pale colour while the packed part of the split stays comparatively dark. You have sat here before when most of the hall could only be inferred from the curve. Tonight its far dimensions remain in sight.",
    req: [],
    stretch: "st-hall",
    morning: "S1 re-rendered with HERE and DOOR",
  },
  {
    id: "b-w3.close",
    kind: "close",
    w: 3,
    o: 10,
    line: "On the second flight below, a small door carries a count. It is set into the wall beside the descending steps, within reach from the flight. Its height is modest against the broad stair. The counted strokes occupy the door while the stair continues past it, leaving the opening as a distinct feature of this turn. The count has its own small boundaries on the door, separate from the worn edges of the steps below. From above, you can hold both scales in sight.",
    req: [],
    stretch: "st-stair",
  },
  // ---- Week 4 ----
  {
    id: "b-4.1",
    kind: "step",
    w: 4,
    o: 1,
    line: "You descend the top flight to its first turn. The risers ask for a deliberate lift of your foot even when you are going down. A second flight continues below, with a small counted door set into it. From the turn you can see the door's position against the slope of the steps without seeing past its shut face. Beneath the next turn is a recess with a count of its own. The two counts occupy different levels of the stair, separated by the drop and the bend. The rail's smooth top remains beside you at the first turn while the lower recess sits beyond its reach.",
    req: [],
    stretch: "st-stair",
    carries: {"inView": ["seal-5-1"]},
  },
  {
    id: "b-4.2",
    kind: "stepKey",
    w: 4,
    o: 2,
    line: "At the first turn, the count on the second niche fills. A tablet rests on its lid: a wedge beside the picture of a well. The two carvings are near enough to read as a pair, each given a separate patch of stone. The small tablet lies against the much larger turn of the stair, where the cut rail follows the wall. You can look from the wedge on its surface to the open descent below without finding another picture on the lid. The well remains a picture, its edge incised rather than an opening in the stair.",
    seal: "seal-4-1",
    req: [],
    stretch: "st-stair",
    carries: {"guess": ["mk-deep"]},
  },
  {
    id: "b-4.3",
    kind: "step",
    w: 4,
    o: 3,
    line: "You open the notebook at Day 9. The page turns at the binding, distinct from the loose sheet of the same date tucked into the gallery crack. You keep the book steady on the cot while finding the heading. Pencil on paper has a different scale here from the cut tally: a few strokes can fit beneath your thumb. The chamber's shelf and the box remain within reach, but the date holds your attention on the open leaves.",
    req: [],
    stretch: "st-camp",
    carries: {"records": ["rec-l6"]},
  },
  {
    id: "b-4.A",
    kind: "arrival",
    w: 4,
    o: 4,
    name: "The sheet dated Day 9",
    line: "You follow the tally beyond the lone ring until it passes beneath a crust of salt carrying a count. The crust stands out from the face beneath it, interrupting the line rather than ending it. Her Day 9 sheet belongs to this stretch. You can place the thin paper against the length of cut wall it concerns, though it cannot cover the portion hidden under salt. In pencil: …go home… he held me… go… lamp… gave… went up… salt… stones… The gaps on the sheet are as visible as the surviving words. Salt on the wall and missing spans on paper occupy different parts of your sight; neither gives up the part it conceals. The crust's count sits above the course of the tally, its strokes separate from the older line. You can follow that line to the covered portion and no farther by eye.",
    req: ["b-3.1"],
    stretch: "st-salt",
    painting: "pt-b-4.A",
    carries: {"records": ["rec-s4"], "inView": ["seal-5-2"]},
  },
  {
    id: "b-4.4",
    kind: "step",
    w: 4,
    o: 5,
    line: "Every record along the tally carries a hook closed on a dot in its corner; the same mark is cut on the lamp’s base. The corners give you a fixed place to find it, even when the records themselves vary in length. She copied it onto her sheet and wrote: signature? The pencil question is small beside the repeated cuts in stone. The corner mark on the wall by the lamp is not this hook. You can compare the wall, the lamp and the sheet as three separate surfaces: an incision, another incision in clay, and her pencilled copy with its question still open.",
    req: ["b-4.A"],
    stretch: "st-salt",
    carries: {"seen": ["mk-hand"]},
  },
  {
    id: "b-4.B",
    kind: "arrivalKey",
    w: 4,
    o: 6,
    name: "The salt block",
    line: "Past the split, a niche bears a count. It is cut into the salt face beyond the packed opening, where the gallery continues. When it fills, a block of salt is revealed inside. Cut into its face is a hook closed on a dot, the size of a thumbnail. The small mark occupies surprisingly little of the exposed block; you can judge it against your own thumb without lifting anything. A short line in the tally’s hand is cut into the wall beside it. Its strokes remain on the fixed face of the gallery while the marked block sits within the niche. The salt's granular edges surround both cuts, but their positions are precise: the hook on the block, the line next to the opening.",
    seal: "seal-4-2",
    req: [],
    stretch: "st-salt",
    painting: "pt-b-4.B",
    carries: {"records": ["rec-x-neighbour"]},
  },
  // NOTE: inView seal-4-4 (the Lower Door's count: seen, not sealed, NICHES 4.4).
  {
    id: "b-4.C",
    kind: "arrival",
    w: 4,
    o: 7,
    name: "The Lower Door, close",
    line: "The great door fills the far end of the hall. At this distance the rounded ceiling seems to come down around its upper edge; nearer, you can see how much wall the door occupies. Every stroke of its count is empty. The row gives your eye a measure across a surface too large to take in comfortably at once. Beside a blank are two marks: the bar-with-a-drop and two drops parted. Their positions hold the empty space between them in the same field of view. Beneath the count is another mark, like a path doubling back. It sits lower than the other two and apart from the blank. You can follow the door's face upwards past the count, then return to these comparatively small, exact cuts near where you stand.",
    req: [],
    stretch: "st-hall",
    painting: "pt-b-4.C",
    carries: {"inView": ["seal-4-4"]},
  },
  {
    id: "b-w4.camp",
    kind: "camp",
    w: 4,
    o: 8,
    line: "By the lamp, you turn its base towards the light. Three marks are cut there. One is the mark that begins every line of the tally. The clay rounds away under your fingers, so each mark comes squarely into view in turn rather than all presenting itself like writing on a page. You can hold the lamp near the wall and compare the first cut on the base with the first cut in the nearby line. Its flame remains above your hands while the base catches light from the cups along the hall.",
    req: [],
    stretch: "st-hall",
    morning: "the different hook on the wall by the lamp, highlighted once",
  },
  {
    id: "b-w4.close",
    kind: "close",
    w: 4,
    o: 10,
    line: "The Lower Door carries two marks beside a count whose every stroke is empty. The count extends across its stone face in a way your eye can follow from one side towards the other. The two marks occupy their place beside it, small against the size of the door. No stroke in the count yet differs from the rest. The cut row is precise, while the door surrounding it is so large that the marks take up only a small part of the visible face. Your eyes can return to the first stroke without losing the last.",
    req: [],
    stretch: "st-hall",
  },
  // ---- Week 5 ----
  {
    id: "b-5.0",
    kind: "step",
    w: 5,
    o: 1,
    line: "On the second flight, every stroke of the little door’s count is full. The door remains shut. The filled cuts and the unyielding face sit together, close enough that you can inspect both from the same step. Beside it, among thousands of rings worn smooth, one ring still has sharp edges. So many softened circles make the single crisp rim difficult to overlook once you find it. The stair carries on below the little door; its height and breadth make this shut, counted opening seem especially contained.",
    req: [],
    stretch: "st-flight2",
    carries: {"records": ["rec-k2"]},
  },
  {
    id: "b-5.1",
    kind: "stepKey",
    w: 5,
    o: 2,
    line: "The count on the recess beneath the second turn fills. Inside is a tablet: a bar-and-tick beside a setting sun, a bar-with-a-drop beside a road, and the same bar again with its drop at the far end. The three pictures occupy successive places on the small face of the tablet. You can follow their order with a fingertip held just above the cuts, from the sun to the road and then to the altered position of the drop. The recess keeps the tablet beneath the turn, below the level where the stair first changed direction.",
    seal: "seal-5-1",
    req: [],
    stretch: "st-flight2",
    carries: {"guess": ["mk-once", "mk-path", "mk-go"]},
  },
  {
    id: "b-5.A",
    kind: "arrival",
    w: 5,
    o: 3,
    name: "The tally, from the head",
    line: "Every record in the tally begins with the same sequence: a bar with a tick, a ring, a single drop. You can pick out those first three cuts again and again along the wall, using their order to locate the start of each record. The line on the wall by the lamp is different. There, the bar with a tick comes second. Both are cut in stone, yet the change of position stands out when you set the opening of a record against the opening of that line. The crowded gallery and the lit space by the ledge are far apart, but the order of these small marks is plain in either place. It is a difference of a single position, legible even when the lengths of the two lines are quite unlike.",
    choice: ["Look at the first stretch again", "look at the wall by the lamp"],
    req: ["seal-5-1"],
    stretch: "st-salt",
    painting: "pt-b-5.A",
  },
  {
    id: "b-5.2",
    kind: "step",
    w: 5,
    o: 4,
    line: "You open the notebook at Day 14. There is enough of the bound book beneath your hand now for its earlier leaves to rest together on one side. The pencil heading occupies the same ordinary place on the page as the earlier dates. You hold the paper near its outer edge to keep the centre of the spread visible. In the side chamber the number is simply a date in a notebook, though it also gives you a point farther along the sequence of sheets.",
    req: ["b-5.A"],
    stretch: "st-camp",
    carries: {"records": ["rec-l7"]},
  },
  {
    id: "b-5.B",
    kind: "arrival",
    w: 5,
    o: 5,
    name: "Through a gap",
    line: "At shoulder height on the second flight, a gap has been cut through the wall. You can see through it without stooping, though the opening is too narrow to give you the whole space at once. Beyond it is another gallery, where square-cut stone meets the rounded work of the stair. The junction has two distinct geometries visible in the same view: straight edges on one side, the stair's long curve on the other. A record in the tally’s hand is cut on the square wall. It begins with the same three marks, except that where the tally has one drop, this has two. You can see the doubled cut from this side of the wall and set it against the repeated beginning you know from the Salt Gallery. The gap frames only part of that other space; within it, the altered count of drops is unmistakable.",
    req: [],
    stretch: "st-flight2",
    painting: "pt-b-5.B",
    carries: {"records": ["rec-v1"]},
  },
  {
    id: "b-5.3",
    kind: "stepKey",
    w: 5,
    o: 6,
    line: "The count on the salt crust fills, exposing another stretch of the tally. Where the crust had hidden the wall, the newly visible cuts continue in the same line as those on either side. Three marks stand together there: the lamp’s, the flame’s and the hook-and-drop’s. They have little space between them, but each keeps its separate outline. No doorway-shape is anywhere near them. You can survey the exposed salt around that cluster, above and below the tally, and find none. The uncovered stretch gives you precisely the three marks in company, without the neighbouring picture you might have expected to see.",
    seal: "seal-5-2",
    req: [],
    stretch: "st-salt",
    carries: {"records": ["rec-s5"]},
  },
  {
    id: "b-w5.camp",
    kind: "camp",
    w: 5,
    o: 7,
    line: "The lamp burns at your side. On its base: the flame, the hook-and-drop, the bar with a tick. Seated here, you can turn the clay enough to bring each cut towards the steady part of the flame without disturbing the ledge. Their short sequence fits into the hollow of your two hands. Beyond the lamp the lit cups carry a much longer repetition down the hall, but the three cuts on the base remain close together, made to be seen on one small object.",
    req: [],
    stretch: "st-hall",
    morning: "L8 next",
  },
  {
    id: "b-w5.close",
    kind: "close",
    w: 5,
    o: 9,
    line: "Below, the stair meets a gallery made of square-cut stone. The straight join stands out after the continuous rounded surface of the flights. You can see where the stone changes its manner of meeting at the edge: flat walls and corners take over from the stair's curve. The gallery carries on beyond that junction. Where the two forms meet, the corner has a firm edge that the stair above never gives your hand. This one change in the stone is enough to distinguish the lower place by touch.",
    req: [],
    stretch: "st-flight2",
  },
  // ---- Week 6 ----
  {
    id: "b-6.A",
    kind: "arrival",
    w: 6,
    o: 1,
    name: "The side passage",
    line: "A low doorway at the Stair’s second landing opens into the gallery you saw through the gap. You have to lower your head beneath it; on the other side there are corners rather than the stair's enclosing curve. Here the walls meet at corners. Where square stone meets rounded stone, the two works have been cut into one another like clasped hands. The interlocking edges can be followed from wall to wall, each kind of work retaining its own surface while entering the other. Up close, the square-wall record reads: …way [ ] [ ] here [ ] once… person [ ] went deep [ ]; fire. One went deep. A lamp, lit. One other. The gaps in the record remain gaps even at this distance. You can see each surviving span in its own cut place on the square wall, with the worked junction still near enough to touch behind you.",
    choice: ["Read it", "go on"],
    req: ["b-5.B"],
    stretch: "st-square",
    painting: "pt-b-6.A",
    carries: {"records": ["rec-v1"]},
  },
  {
    id: "b-6.1",
    kind: "step",
    w: 6,
    o: 2,
    line: "You open the notebook at Day 20. Small chips of stone lie in the gutter between the pages. They collect where the two leaves slope towards the binding, a little irregular line that shifts when you open the book fully. You can see the date above them without brushing them away. The chips are distinct from the pencilled writing by their thickness and hard edges; they give the fold a weight the paper alone would not have. The cot holds the open book level while the stone pieces remain in its centre.",
    req: ["b-6.A"],
    stretch: "st-camp",
    carries: {"records": ["rec-l8"]},
  },
  {
    id: "b-6.2",
    kind: "stepKey",
    w: 6,
    o: 3,
    line: "At the Salt Gallery’s last hidden stretch, the count on the crust fills. Behind it lies a tablet. A doorway is carved beside two drops parted; beside a loaf is a hook closed on a drop over a bar. The two pairings occupy their own areas of the tablet, separated enough to see where one ends and the other begins. Beyond the tablet, the tally continues. Its course takes your eye past the newly exposed place along the salt face. The little carved doorway stays on the tablet; the gallery beyond it is still the same continuous space around you.",
    seal: "seal-6-1",
    req: [],
    stretch: "st-salt",
    carries: {"guess": ["mk-open", "mk-eat"]},
  },
  {
    id: "b-6.B",
    kind: "arrivalKey",
    w: 6,
    o: 4,
    name: "The crew's wall",
    line: "A second record, longer than the first, is cut into the square wall in the tally’s hand: …one ate [ ], person [ ]… [ ] [ ] one: way [ ] [ ] [ ]… gave [ ] [ ] [ ]; door open… person [ ] gave [ ]. Its surviving words occur at intervals across a considerable length of flat stone. One span appears on her sheets: …he held us…. The pencil and the cut record have their own proportions, paper narrow enough to hold, wall broad enough to follow with your body. Beneath the record is a counted niche. It fills. Inside lies a wax tablet gone hard, ruled into rows, a ring at the head of each. You can make out the regular beginning of every row without taking the tablet from its hollow. Its small ordered surface sits directly beneath the much longer broken line above.",
    choice: ["Read the record", "look at the tablet"],
    seal: "seal-6-2",
    req: [],
    stretch: "st-square",
    painting: "pt-b-6.B",
    carries: {"records": ["rec-v2", "rec-x-foreman"]},
  },
  {
    id: "b-6.3",
    kind: "step",
    w: 6,
    o: 5,
    line: "A mule-shoe lies on the gallery floor. Its curve is low against the straight edges of the stone around it. Beside it is a stone worn by the rub of a halter. The smooth place on that stone occupies a confined height, a repeated contact made visible in its surface. Above the stone, a short line is cut into the wall: [ ]: [a mule] went deep [ ]; me [ ] [ ]. You can look from the shoe at floor level to the rubbed place and then up to the cut line without changing position. The three occupy distinct heights in the square gallery.",
    req: ["b-6.B"],
    stretch: "st-square",
    carries: {"records": ["rec-x-mule"], "inView": ["seal-6-4"]},
  },
  {
    id: "b-w6.camp",
    kind: "camp",
    w: 6,
    o: 6,
    line: "From beside the lamp, you look at the lamp carved on the wall. Its cuts are still sharp. The real flame moves across the pictured body, but the incised edge remains exact even when the light shifts. The clay lamp sits out from the wall on its ledge; the carved one stays within the stone. You can compare their shapes from where you rest without needing the marks beside the carving to stand out at all.",
    req: [],
    stretch: "st-hall",
    morning: "S2 re-rendered: ate [ ] now shows the sign for EAT in Dan’s layer",
  },
  {
    id: "b-w6.close",
    kind: "close",
    w: 6,
    o: 8,
    line: "Down the second flight, a lintel stands over solid stone. Beside its blank are two marks; one is the path’s. The worked upper edge gives you a measure for the uninterrupted wall beneath it. From the flight you can see the marks on either side of the space and the solid face below in the same glance. The turn of the stair continues past this place. You can judge the blank by its neighbouring cuts, but the height of the stone below it by standing beside the wall. The lintel does not interrupt that solid reach of masonry.",
    req: [],
    stretch: "st-flight2",
  },
  // ---- Week 7 ----
  {
    id: "b-7.1",
    kind: "stepKey",
    w: 7,
    o: 1,
    line: "A niche in the square gallery fills its count. Inside is a tablet: an inverted wedge beside the sky, a wedge on a bar beside a block, and a small figure beside a child’s tablet. Each pair has its own portion of the tablet's face. Their carved outlines are small beside the even chisel marks of the square wall, but the separate shapes remain clear when you bring the tablet into the light entering the gallery. The inverted wedge and the wedge on a bar can be compared without confusing either with the little figure at the end.",
    seal: "seal-7-1",
    req: [],
    stretch: "st-square",
    carries: {"guess": ["mk-up", "mk-stone", "mk-child"]},
  },
  {
    id: "b-7.A",
    kind: "word",
    w: 7,
    o: 2,
    name: "The lintel at the foot of the second flight",
    taps: ["You set the rod’s edge in the blank.", "You cut the first mark, the bar with a drop.", "You cut the second, the two drops parted.", "Light fills the cuts and the rod gives one low ring. The stone beneath the lintel is gone. Beyond it, the Stair continues down through light."],
    req: ["seal-7-1", "mk-path", "mk-open"],
    stretch: "st-flight2",
    painting: "pt-b-7.A",
    carries: {"word": "wd-open-way"},
  },
  {
    id: "b-7.2",
    kind: "step",
    w: 7,
    o: 3,
    line: "Past the crust the tally goes on. In it a barn is carved, and in the barn an owl, cut by someone who has not seen one: …[ ] gave child: up [a barn] [an owl] here… ate [ ]; [ ] [ ]; [ ]… child [ ]: [ ] [ ]… The pictured bird is contained inside the pictured building, both worked into the same record as the surrounding marks. You can recognise the intention of an owl without finding the proportions you would expect. The broken words travel on either side of the carving across the salt, with the missing spans still plainly missing. Your eye returns to that awkward small bird because it is a particular shape amid the more regular marks of the tally.",
    req: ["b-7.A"],
    stretch: "st-salt",
    carries: {"records": ["rec-s6"]},
  },
  // NOTE: ARR2 carries V3 and X-boy here; MVP_CONTENT §4 gives them no rec- ids, so records are left out.
  {
    id: "b-7.B",
    kind: "arrivalKey",
    w: 7,
    o: 4,
    name: "The crew's wall, again",
    line: "Below the second record are twelve rings in a row and, after them, a smaller thirteenth: …person [ ], child one [a tablet]… You can count the first twelve across the wall, then see the change in scale of the last without having to count again. The niche beneath fills its count. Inside is a wax tablet gone hard, carrying twenty marks. Some are backwards. One is a fork with nothing under it. Beside three, the tally’s hand has cut the same three correctly—not over them, but alongside. The neighbouring cuts let you compare each of those three pairs while keeping both versions intact. The hardened wax bears the crowded twenty; the correction sits next to three of them, careful about their position rather than erasing what was there.",
    seal: "seal-7-2",
    req: [],
    stretch: "st-square",
    painting: "pt-b-7.B",
  },
  {
    id: "b-7.3",
    kind: "stepKey",
    w: 7,
    o: 5,
    line: "At the Stair’s first turn, the count in the recess beside the rail fills. The stone where a hand rested has taken the shape of that hand. It has four fingers, and they are long. Your own hand can lie near the depression without covering its reach. The rail's smooth upper surface runs past it, while this particular place holds the length and division of fingers instead of a general polish. The hollow is in stone, not a carving set out as a picture; its depth varies where the fingers and the rest of the hand met the surface.",
    seal: "seal-7-3",
    req: [],
    stretch: "st-stair",
  },
  {
    id: "b-7.4",
    kind: "stepKey",
    w: 7,
    o: 6,
    line: "In the gallery wall the count on a cache fills. Inside, in a bag gone hard, are twelve bronze coins and one clay token, and beside the cache is a line: Once, [ ] gave me [a bag]: [ ] person [ ], child one; [ ] [ ]. [ ] door once, [ ] [ ] [ ]. I [ ] it. The bronze pieces occupy one part of the stiff bag and the clay token another, a difference you can see through the opening. The line remains beside the cache rather than within it, cut into the flat wall at a height you can read. Its words and square-bracketed absences sit alongside a counted collection whose pieces can be numbered exactly.",
    seal: "seal-7-4",
    req: [],
    stretch: "st-square",
  },
  // NOTE: a Key arrival that is also the word again: kind 'word' with `seal`; `line` is the preface shown before the taps.
  {
    id: "b-7.C",
    kind: "word",
    w: 7,
    o: 7,
    name: "The great door",
    line: "At the far end of the hall, beside the door’s blank, are the same two marks as the lintel’s, and under them is the count. The scale of the great door gives the small arrangement a great deal of stone around it. You can stand near enough to see the separate edges of both cuts, then step back far enough to set them against the full face of the door. Their order and the space between them remain the same as at the lintel, even though this wall rises much higher. Below, the counted strokes occupy their own band of stone. You can follow that band from its first stroke to its last while the door extends beyond what one close view will hold.",
    taps: ["You set the rod’s edge in the blank.", "You cut the first mark, the bar with a drop.", "You cut the second, the two drops parted.", "The count fills stroke by stroke. The door is not there. Beyond, a stair drops away at twice the pitch, and the hall’s light follows it for eleven steps before stopping."],
    choice: ["Go down as far as the light", "go back along the hall"],
    seal: "seal-7-5",
    req: ["b-7.A"],
    stretch: "st-hall",
    painting: "pt-b-7.C",
    carries: {"word": "wd-open-way"},
  },
  {
    id: "b-w7.camp",
    kind: "camp",
    w: 7,
    o: 8,
    line: "Beside the lamp, you sit facing the far end of the hall. There the great door stands open, and cold air rises through it. The lamp is near enough to see the curve of its clay; the opening is far enough that its upper edge belongs to the hall's dark height. The air reaches you along the length between them, cooler than the stillness by the ledge. The flames in the cups show the shape of that distance, one interval after another, to the open end.",
    req: [],
    stretch: "st-hall",
    morning: "the map: two ways down, both ending in the dark",
  },
  {
    id: "b-w7.close",
    kind: "close",
    w: 7,
    o: 10,
    line: "Both ways down reach water. The water does not move. At either descent the surface holds its level, making the slope of the way above it easier to judge. There is no current to follow with your eye from one direction towards the other. Each route ends at the same still boundary. At the edge of either descent, the difference between the cut way and the flat water is immediate. There is no visible disturbance in the surface to give either direction a greater claim on your attention.",
    req: [],
    stretch: "st-hall",
  },
  // ---- Places with no fragment (MVP_CONTENT §2) ----
  {
    id: "pl-w1-pick-niche",
    kind: "arrival",
    w: 1,
    o: 3,
    name: "The pick niche",
    line: "Low in the Salt Gallery wall is an arm-long niche. You have to bend to put its whole length at eye level; from above, the far end is hidden by the lip. A row of cut strokes runs along its lip, every stroke empty. They occupy the edge where the wall gives way to the hollow, so a fingertip can follow their spacing without entering it. Beside it, the salt is scored with close, short cuts. The roughened patch differs from both the smooth inner face and the longer strokes of the count. Salt breaks at the rims of those little incisions, making their crowded lines visible even where they do not descend deeply. The niche keeps its arm-long shape in the wall while the fine scoring remains outside it.",
    req: [],
    stretch: "st-salt",
    painting: "pt-pl-w1-pick-niche",
    carries: {"inView": ["seal-1-2"]},
  },
  {
    id: "pl-w1-below-the-lamp",
    kind: "arrival",
    w: 1,
    o: 5,
    name: "Below the lamp",
    line: "Below the ledge, at knee height, a small niche is cut into the wall. From where you stand beside the lamp, the ledge itself interrupts your view of its mouth. Empty strokes run along its lip. They are set low enough that you have to bend to separate them cleanly from the surrounding stone. The stone around the mouth is darker than the rest and greasy under your fingers. The difference lies exactly where your hand meets the opening; beyond that patch, the wall returns to its usual dry surface. Above, the lamp occupies its ledge with the flame in sight. Down here you see the underside of the same stone and the narrow counted hollow tucked beneath it. Its scale makes it a place you examine with a hand rather than by stepping into it.",
    req: [],
    stretch: "st-hall",
    painting: "pt-pl-w1-below-the-lamp",
    carries: {"inView": ["seal-1-3"]},
  },
  {
    id: "pl-w2-above-the-ring",
    kind: "arrival",
    w: 2,
    o: 2,
    name: "Above the ring",
    line: "Above the lone ring, a crack two fingers wide opens in the salt. It is high enough that the ring helps you locate it when you look up from the tally. A small count is cut beside it. Its strokes occupy sound salt close to the narrow opening. Something pale lies far back inside, beyond reach. At first the pale part seems to belong to the salt itself; then its position at the rear of the crack separates it from the nearer edges. You can measure the mouth against two fingers, but not the space that runs inward from it. Looking from one side to the other shifts the near edges across the distant pale patch without bringing that patch any closer.",
    req: ["seal-1-1"],
    stretch: "st-salt",
    painting: "pt-pl-w2-above-the-ring",
    carries: {"inView": ["seal-2-3"]},
  },
  // NOTE: §2 names "the corner's troughs" here; inView is seal-2-4, the seen-not-sealed smooth place NICHES 2.4 says this place is.
  {
    id: "pl-w2-smooth-place",
    kind: "arrival",
    w: 2,
    o: 4,
    name: "The smooth place",
    line: "At the corner, one patch of the polished wall is bare of marks at the height of a long hand. The omission has its own shape amid cuts otherwise worn faint across this part of the wall. The stone has been rubbed smooth there, like a banister. You can put your hand beneath the patch and feel how much higher its centre lies. The two troughs in the floor follow the turn nearby, a stride apart, while this one smooth place occupies only a short length of wall. It has no incised boundary; its edges are where the marks resume and the sheen becomes less even. Your eye can find it again by that little interruption in the crowded, polished surface.",
    req: ["b-1.B"],
    stretch: "st-hall",
    painting: "pt-pl-w2-smooth-place",
    carries: {"inView": ["seal-2-4"]},
  },
  {
    id: "pl-w2-box-by-the-cot",
    kind: "arrival",
    w: 2,
    o: 5,
    name: "The box by the cot",
    line: "A shoebox-sized box is pushed against the wall of her camp. It occupies the low strip of floor beside the cot, easy to overlook from the chamber entrance. A thin slate lies across the lid with a count cut into it. The slate has its own straight edge against the box's broader top; the strokes are gathered within that smaller surface. An upside-down tin mug stands on the slate. Its rim touches the stone, making a circle against the flat piece beneath it. You can see the arrangement without shifting any part of it: box against wall, counted slate above, mug turned mouth down at the top. Its homely scale sits alongside the neatly placed boots beneath the cot. The mug’s inverted position remains plain even from the doorway.",
    req: ["b-1.C"],
    stretch: "st-camp",
    painting: "pt-pl-w2-box-by-the-cot",
    carries: {"inView": ["seal-2-5"]},
  },
  {
    id: "pl-w3-salt-lit",
    kind: "arrival",
    w: 3,
    o: 3,
    name: "The salt, lit",
    line: "Light from the hall comes round the corner and catches the salt in bands of grey and pink. The colours follow the face rather than the pattern of marks cut into it, so the tally crosses from one band into another. The packed stones in the split are round, brown river stones, carried up from somewhere with water. Their rounded surfaces contrast with the broken salt pressed between them. You can see individual curves now that the light has reached the opening, each stone distinct where before the packing seemed a single dark interruption. The split descends from above your head to knee height, leaving a long vertical account of the two materials together: salt with its banding, brown stones fitted against it. The fresh light lets you inspect the place without making the split itself any wider.",
    req: ["b-3.A"],
    stretch: "st-salt",
    painting: "pt-pl-w3-salt-lit",
  },
  {
    id: "pl-w3-far-end",
    kind: "arrival",
    w: 3,
    o: 5,
    name: "The far end",
    line: "The last lamp is a stride from the great door. It stands close enough for its flame to pick out the lower face in detail; one more stride puts you against the stone itself. Its light climbs partway up the stone, but the door continues beyond it into the curve of the ceiling. You can follow the illuminated portion upwards until it thins, then infer the rest from the dark outline where the ceiling bends around it. Cold comes off the face of it like cold from a window in winter. It reaches your skin at a distance the lamplight cannot make warm. The flame is small against this surface, though from down the hall the lamp seemed one of a long, sufficient row. Here the high part of the door remains beyond its reach.",
    req: ["b-3.A"],
    stretch: "st-hall",
    painting: "pt-pl-w3-far-end",
  },
  {
    id: "pl-w4-hollow",
    kind: "arrival",
    w: 4,
    o: 2,
    name: "The hollow",
    line: "Low in the salt is a hollow the size of two cupped hands, smooth from wear. You bend to see into it; from standing height its lower curve is concealed by the rim. A count runs round its rim. The strokes follow the rounded opening rather than crossing it in a straight line. At the bottom, the salt has been pressed flat in four small places. Each flattened patch is separate enough to count, though all lie within the little basin of the hollow. The face around it still shows the salt's grain; inside, wear has made the surface more continuous. Your two hands give a useful measure of the opening, but the four small level places at its base demand a much closer look.",
    req: [],
    stretch: "st-salt",
    painting: "pt-pl-w4-hollow",
    carries: {"inView": ["seal-4-5"]},
  },
  {
    id: "pl-w4-recess-above-the-cot",
    kind: "arrival",
    w: 4,
    o: 4,
    name: "The recess above the cot",
    line: "Above the cot, at the height of a raised arm, a recess is closed by a counted slate. You can judge how high it is by reaching from the place where the cot stands against the wall. The slate sits across the opening, and the cut strokes remain visible on its face. A drawing pin has been pushed into a crack beside it, with nothing pinned beneath. Its small head interrupts the stone near the larger closed recess. Below, the cot fills the same stretch of wall at a very different height. The bare space under the pin is easy to examine because there is no paper covering it. You can take in the slate, the nearby crack and the single pin without moving the objects on the cot.",
    req: ["b-1.C"],
    stretch: "st-camp",
    painting: "pt-pl-w4-recess-above-the-cot",
    carries: {"inView": ["seal-4-3"]},
  },
  {
    id: "pl-w5-ledge-lip",
    kind: "arrival",
    w: 5,
    o: 2,
    name: "The ledge's lip",
    line: "The underside of the lamp’s ledge is cut as well. You have to lower yourself to see the worked place; the lamp above it remains visible only at the edge of your view. A small count sits there, low enough to be invisible to anyone standing. Its cuts occupy the stone's lower face, which the flame on the ledge cannot illuminate directly. From this height the lip has a definite thickness, and the count lies within that thickness rather than on the wall behind it. The surrounding surface is close to your eyes, so the little row of strokes is easier to distinguish than it would be from across the hall. Standing again, the ledge hides it completely beneath the burning lamp.",
    req: [],
    stretch: "st-hall",
    painting: "pt-pl-w5-ledge-lip",
    carries: {"inView": ["seal-5-5"]},
  },
  {
    id: "pl-w5-worn-steps",
    kind: "arrival",
    w: 5,
    o: 3,
    name: "The worn steps",
    line: "Halfway down the top flight, each step is worn in two places a stride apart. The depressions recur at the same distances across successive treads, making two long courses down the stair. The stride is longer than yours. You can try to set your feet into both worn places, but one falls short when the other is comfortably placed. The rail beside them has been polished along its top. Its smoothness runs continuously past the separate worn patches below. The stair is broad enough to show both courses clearly, while its high risers demand your attention each time you descend. Looking up the flight from midway, you can see the paired wear repeated step after step towards the landing. The interval between each pair remains broader than your own stance.",
    req: ["b-3.C"],
    stretch: "st-stair",
    painting: "pt-pl-w5-worn-steps",
  },
  {
    id: "pl-w5-second-landing",
    kind: "arrival",
    w: 5,
    o: 5,
    name: "The second landing",
    line: "The second flight turns onto a landing as broad as the hall above, its wall lamps already lit. After the steep rise of the steps, the breadth of level stone changes the way you stand: there is room to face across it without being pressed to the wall. Across from the stair is a square-cornered doorway, too low for whoever made the Stair. The corners are abrupt against the rounded enclosure you have followed down. You can look back at the wide flight and then at the modest height of the opposite opening, taking their difference in one view. The lit wall lamps trace the landing's extent on either side, while that low doorway gives a separate measure nearer your own height. Both ways remain part of the same level place.",
    req: ["b-4.1"],
    stretch: "st-flight2",
    painting: "pt-pl-w5-second-landing",
  },
  {
    id: "pl-w6-square-gallery",
    kind: "arrival",
    w: 6,
    o: 2,
    name: "The square gallery",
    line: "The gallery runs perfectly straight, no taller than a tall man. Your head is much nearer its ceiling than it was beneath the high vault of the Stair. Its ceiling is flat, its walls covered in small, even chisel marks. The regular cuts persist along the length you can see, making the surface appear worked in short, repeated strokes. There are no lamp-cups here. Light enters from the rounded stone behind you and thins away. The square edges lose definition first; farther ahead you can still discern the floor's line because it leads directly towards a change of level. Far ahead, the floor disappears beneath a slope of broken stone. That slope occupies the width of the straight passage at its distant end. You can see the change from fitted, cut surfaces to irregular fragments without making out each broken piece.",
    req: ["b-6.A"],
    stretch: "st-square",
    painting: "pt-pl-w6-square-gallery",
  },
  {
    id: "pl-w6-wall-shelf",
    kind: "arrival",
    w: 6,
    o: 4,
    name: "The wall-shelf",
    line: "A shelf is cut into the square wall at chest height, with a count on its lip. Its level front edge stands out from the many small chisel marks of the wall behind. Someone has scratched a dead-level line along the edge, ending it with a short tick at either side. The fine scratch runs straight between its two little terminal cuts, occupying a different scale from the broader strokes of the count. You can set your eye alongside the shelf and follow that line without seeing it rise or fall. The shelf projects just enough for its upper and lower surfaces to be distinct. Here, with the gallery wall meeting itself in corners, the level of this small worked edge is easy to judge against the straight runs around it.",
    req: ["pl-w6-square-gallery"],
    stretch: "st-square",
    painting: "pt-pl-w6-wall-shelf",
    carries: {"inView": ["seal-6-3"]},
  },
  {
    id: "pl-w6-folder",
    kind: "arrival",
    w: 6,
    o: 5,
    name: "Her folder",
    line: "Under the cot, pushed hard against the back wall, is a document folder held shut by an elastic band. You have to lower your head beside the cot to see it all the way back. A thin counted slate lies over its cover. The slate holds down only part of the folder, leaving the band visible round its edges. HILL is written on the spine in marker. The capital letters face outward from the low, confined space, plain enough to read at this distance. The cot above and the wall behind leave little room to lift the folder without disturbing the slate. From where you kneel, you can see the order of its layers: writing on the spine, band round the folder, counted stone over the cover.",
    req: ["b-1.C"],
    stretch: "st-camp",
    painting: "pt-pl-w6-folder",
    carries: {"inView": ["seal-6-5"]},
  },
];
