/**
 * SEALED STORY CONTENT (D-015). Never shown to Dan outside the game.
 * Transcribed from docs/narrative/sealed/ (ARRIVALS_REGION1.md weeks 1-5, ARRIVALS_REGION2.md weeks 6-7,
 * MVP_CONTENT.md §0-§3). Those files are authoritative; fix them first, then this.
 */
import type { Beat } from '../../core/story-types';

/** Story beats (ARR rows; `o` = the row's position in its week's ARR table, teaser rows counted but not included), then the 15 `pl-` places (`o` = route position, MVP_CONTENT §2). */
export const beats: Beat[] = [
  // ---- Week 1 ----
  {
    id: "b-w1.morning",
    kind: "morning",
    w: 1,
    o: 1,
    line: "A field on the side of a hill. In the grass, an iron cap the size of a table, and the padlock on it is on the ground, cut.",
    req: [],
    stretch: "st-mouth",
  },
  {
    id: "b-1.1",
    kind: "step",
    w: 1,
    o: 2,
    line: "The shaft cap is off. The padlock is on the ground beside it, cut clean through the shackle. Two notices on the cap: an old enamel one, the name worn to nothing, DANGER OF FALLING; a new laminated one with a phone number. Eleven metres of ladder go down into dry air.",
    req: [],
    stretch: "st-mouth",
  },
  {
    id: "b-1.2",
    kind: "step",
    w: 1,
    o: 3,
    line: "The ladder ends in a passage. Floor and walls meet in one curve, like the inside of a pipe, and there is no tool-mark anywhere on it. Twenty paces on, it opens.",
    req: [],
    stretch: "st-mouth",
  },
  {
    id: "b-1.A",
    kind: "arrival",
    w: 1,
    o: 4,
    name: "The Lamp Hall",
    line: "Long, high, rounded at the edges like the inside of a shell. On a ledge at the near end, a clay lamp, lit. It was lit when you came down. There is no oil in it. Along both walls at head height, cups cut into the stone, one every few paces, empty. Every surface within reach is cut with marks, and among the marks, rings. At the far end, past where the light reaches, a door. It is most of the wall.",
    choice: ["Look at the lamp", "look at the wall"],
    req: [],
    stretch: "st-hall",
    painting: "pt-b-1.A",
    carries: {"records": ["rec-l1", "rec-k1"], "seen": ["mk-ring"]},
  },
  {
    id: "b-1.3",
    kind: "step",
    w: 1,
    o: 5,
    line: "The wall by the lamp, close. The carved lamp is the same shape as the one on the ledge. Beside it, one mark. Under it, a carved flame, and beside that, another.",
    req: ["b-1.A"],
    stretch: "st-hall",
    carries: {"records": ["rec-l1"], "guess": ["mk-lamp"]},
  },
  {
    id: "b-1.4",
    kind: "step",
    w: 1,
    o: 6,
    line: "The flame's mark, close. It is two cuts diverging from a point. The lamp's mark has the same two cuts, inside a cup.",
    req: ["b-1.A"],
    stretch: "st-hall",
    carries: {"records": ["rec-l1"], "guess": ["mk-fire"]},
  },
  {
    id: "b-1.B",
    kind: "arrival",
    w: 1,
    o: 7,
    name: "The corner",
    line: "Where the hall turns, the floor is worn into two long troughs a stride apart, and the wall beside them is polished smooth to the height of a man's shoulder, if the man were twice your size. The marks there are rubbed faint. Beyond the turn, a gallery, and the smell of salt.",
    req: [],
    stretch: "st-hall",
    painting: "pt-b-1.B",
  },
  {
    id: "b-1.5",
    kind: "step",
    w: 1,
    o: 8,
    line: "The Salt Gallery. The hill's rock salt meets the cut stone here. The salt face is split from the top to knee height, and the split is packed with stones and salt from the other side. Along the wall, a line of marks as long as the gallery, all cut by one hand. Someone has left loose sheets of paper tucked into a crack beside it, dated in pencil: Day 1, Day 4, Day 9.",
    choice: ["Look at the wall", "Look at her sheets"],
    req: ["b-1.B"],
    stretch: "st-salt",
    carries: {"records": ["rec-s1"]},
  },
  {
    id: "b-1.6",
    kind: "stepKey",
    w: 1,
    o: 9,
    line: "The Salt Gallery, where the first stretch of the line ends. On the salt, a row of cut strokes. The first stroke is full of light. Past it, the line of marks goes on into the dark.",
    seal: "seal-1-1",
    req: [],
    stretch: "st-salt",
  },
  // NOTE: inView includes seal-1-4 (her boots: seen, not sealed, NICHES 1.4) as well as the tin box.
  {
    id: "b-1.C",
    kind: "arrival",
    w: 1,
    o: 10,
    name: "The Survey Cut",
    line: "A side chamber someone lived in. A camp cot, and under it a pair of boots, laced, dry, side by side as if for the morning. On the cot, a notebook with a pencil in it, and a tin box with a row of cut strokes on its lid. On a shelf, a rod of stone the length of a forearm, one edge finer than a knife.",
    choice: ["Open the notebook", "look at the shelf"],
    req: [],
    stretch: "st-camp",
    painting: "pt-b-1.C",
    carries: {"records": ["rec-l2"], "inView": ["seal-1-4", "seal-2-1"]},
  },
  // NOTE: deep beats take the steps rule (nearest arrival above) as their req.
  {
    id: "b-1.7",
    kind: "deep",
    w: 1,
    o: 11,
    line: "The lamp, close: on its side, away from the three marks on the base, a hook cut alone, open. Nothing else in the cell.",
    req: ["b-1.C"],
    stretch: "st-hall",
    carries: {"seen": ["mk-give"], "partial": "hook"},
  },
  {
    id: "b-w1.camp",
    kind: "camp",
    w: 1,
    o: 12,
    line: "By the lamp. The rings on the wall behind it catch the light one after another as it moves.",
    req: [],
    stretch: "st-hall",
    morning: "a line of the salt tally re-rendered with your two guesses",
  },
  {
    id: "b-w1.close",
    kind: "close",
    w: 1,
    o: 14,
    line: "On the side wall, a lintel, and under it no door: stone. Beside it, two marks with a blank between them. One is the flame's.",
    req: [],
    stretch: "st-hall",
  },
  // ---- Week 2 ----
  // NOTE: stepKey beats take no arrival req; their seal being in view (Key rule, MVP_CONTENT §0.2) governs them.
  {
    id: "b-2.1",
    kind: "stepKey",
    w: 2,
    o: 1,
    line: "The tin box on the cot. The count on its lid fills, and the lid lifts. Inside, more sheets, and one sheet with four marks drawn large: under three of them a word in pencil; under the fourth, only a question mark.",
    seal: "seal-2-1",
    req: [],
    stretch: "st-camp",
    carries: {"guess": ["mk-person", "mk-one", "mk-me"]},
  },
  {
    id: "b-2.2",
    kind: "step",
    w: 2,
    o: 2,
    line: "The lintel on the side wall, close. Two marks beside a blank. One is the flame's mark. The other is a hook, and a drop leaving it. Beneath the lintel there is no door, only stone.",
    req: ["seal-2-1"],
    stretch: "st-hall",
    carries: {"guess": ["mk-give"]},
  },
  {
    id: "b-2.A",
    kind: "arrival",
    w: 2,
    o: 3,
    name: "The Salt Gallery, further in",
    line: "Past the inner count, the tally goes on. The hand is the same. Above it, alone, a single ring, larger than the others. Her sheets skip the next stretch.",
    choice: ["Read the tally", "look at the ring"],
    req: [],
    stretch: "st-salt",
    painting: "pt-b-2.A",
    carries: {"records": ["rec-s2"]},
  },
  {
    id: "b-2.3",
    kind: "step",
    w: 2,
    o: 4,
    line: "The notebook, Day 3.",
    req: ["b-2.A"],
    stretch: "st-camp",
    carries: {"records": ["rec-l3"]},
  },
  {
    id: "b-2.4",
    kind: "stepKey",
    w: 2,
    o: 5,
    line: "The tally-stick's niche: the count on it fills. Inside, a stick notched in fives; beside it on the wall, a short line in the hand of the tally, with a number in it.",
    seal: "seal-2-2",
    req: [],
    stretch: "st-salt",
    carries: {"records": ["rec-x-daughter"]},
  },
  {
    id: "b-2.B",
    kind: "arrival",
    w: 2,
    o: 6,
    name: "The rod",
    line: "You lift it from the shelf. It is heavier than it looks and warm. On the handle, a line of marks in a hand that is not the tally's, with a hook with a tail in the corner of the last cell, and under the shelf, in pencil: For the next one. Cut the two marks on the lintel. Don't be precious about it.",
    req: ["b-2.1"],
    stretch: "st-camp",
    painting: "pt-b-2.B",
    carries: {"records": ["rec-l4"]},
  },
  {
    id: "b-w2.camp",
    kind: "camp",
    w: 2,
    o: 7,
    line: "The lamp. Along the hall, the cups at head height, going away into the dark, and in each one the flame's mark, unlit.",
    req: [],
    stretch: "st-hall",
    morning: "the mark on the map: the lintel marked as a door",
  },
  {
    id: "b-w2.close",
    kind: "close",
    w: 2,
    o: 9,
    line: "The blank on the lintel is the width of the rod's edge exactly.",
    req: [],
    stretch: "st-hall",
  },
  // ---- Week 3 ----
  // NOTE: for this word, `line` is the wake shown after the fourth tap (no field for "after the taps").
  {
    id: "b-3.A",
    kind: "word",
    w: 3,
    o: 1,
    name: "The lintel",
    line: "Then the lamp-cups along the hall take fire one after another, a hand of them, then more, to the end of the hall and round the corner, and the stone under the lintel is not there. Beyond it, a landing, and a stair going down, and the landing is lit already. You did not light it.",
    taps: ["The rod's edge, in the blank.", "The first mark: the flame.", "The second: the hook and the drop.", "The cuts fill with light along the wall, and the rod rings once, low, like a struck pipe."],
    req: ["b-2.B", "mk-give"],
    stretch: "st-hall",
    painting: "pt-b-3.A",
    carries: {"word": "wd-light"},
  },
  {
    id: "b-3.1",
    kind: "step",
    w: 3,
    o: 2,
    line: "The Salt Gallery: the tally, further. Her sheets stop before this stretch. Halfway along it, the flame's mark and the hook-and-drop stand together in one cell.",
    req: ["b-3.A"],
    stretch: "st-salt",
    carries: {"records": ["rec-s3"], "inView": ["seal-3-2"]},
  },
  {
    id: "b-3.2",
    kind: "step",
    w: 3,
    o: 3,
    line: "The notebook, Day 6.",
    req: ["b-3.1"],
    stretch: "st-camp",
    carries: {"records": ["rec-l5"]},
  },
  // NOTE: req b-3.A is physical access (the Stair lies beyond the lintel), added so the skip rule cannot play it first.
  {
    id: "b-3.B",
    kind: "arrivalKey",
    w: 3,
    o: 4,
    name: "The head of the Stair",
    line: "A landing. A niche with a count on it, and the count fills. The top flight going down into lamp-light that is already lit. On the niche's lid, a small tablet: a carved doorway beside a mark; a carved bar beside a mark. Inside the niche, a second lamp, clay, unlit, its glaze unchipped.",
    seal: "seal-3-1",
    req: ["b-3.A"],
    stretch: "st-stair",
    painting: "pt-b-3.B",
    carries: {"guess": ["mk-here", "mk-door"]},
  },
  {
    id: "b-3.3",
    kind: "step",
    w: 3,
    o: 5,
    line: "The lamp on the ledge, close, now that the hall is lit: on its base, the flame, the hook-and-drop, and a bar with a tick. In the corner, a hook closed on a dot.",
    req: ["b-3.B"],
    stretch: "st-hall",
    carries: {"records": ["rec-k1"]},
  },
  // NOTE: req b-3.A is physical access, as for b-3.B.
  {
    id: "b-3.C",
    kind: "arrival",
    w: 3,
    o: 6,
    name: "The top flight",
    line: "The stair is wide enough for three and each step is higher than a step should be. At the first turn, a rail cut from the stone, worn smooth along its top, and in the wall beside it a second niche with a count.",
    choice: ["Go down", "go back to the tally"],
    req: ["b-3.A"],
    stretch: "st-stair",
    painting: "pt-b-3.C",
    carries: {"inView": ["seal-4-1"]},
  },
  {
    id: "b-3.4",
    kind: "deep",
    w: 3,
    o: 7,
    line: "The second flight: a small door with a count, shut, with a finger's width of dark down one edge; beside it, among the worn rings, one ring cut sharp. Beyond, the stair goes on. A wedge cut on the wall, alone.",
    req: ["b-3.C"],
    stretch: "st-flight2",
    carries: {"records": ["rec-k2"], "seen": ["mk-deep"], "partial": "wedge"},
  },
  {
    id: "b-w3.camp",
    kind: "camp",
    w: 3,
    o: 8,
    line: "The lamps along the hall are lit now, all the way to the corner. Round the corner, a glow on the salt.",
    req: [],
    stretch: "st-hall",
    morning: "S1 re-rendered with HERE and DOOR",
  },
  {
    id: "b-w3.close",
    kind: "close",
    w: 3,
    o: 10,
    line: "Down the second flight, a small door with a count on it.",
    req: [],
    stretch: "st-stair",
  },
  // ---- Week 4 ----
  {
    id: "b-4.1",
    kind: "step",
    w: 4,
    o: 1,
    line: "The top flight, down to its first turn. Below it, a second flight, and on it a small door with a count. Where the second flight turns, under the turn, a recess with a count of its own.",
    req: [],
    stretch: "st-stair",
    carries: {"inView": ["seal-5-1"]},
  },
  {
    id: "b-4.2",
    kind: "stepKey",
    w: 4,
    o: 2,
    line: "The first turn. The count on the second niche fills. On its lid, a tablet: a wedge beside a picture of a well.",
    seal: "seal-4-1",
    req: [],
    stretch: "st-stair",
    carries: {"guess": ["mk-deep"]},
  },
  {
    id: "b-4.3",
    kind: "step",
    w: 4,
    o: 3,
    line: "The notebook, Day 9.",
    req: [],
    stretch: "st-camp",
    carries: {"records": ["rec-l6"]},
  },
  {
    id: "b-4.A",
    kind: "arrival",
    w: 4,
    o: 4,
    name: "The sheet dated Day 9",
    line: "The tally, past the lone ring, to where it goes under a crust of salt with a count on it. This stretch is the one her sheet dated Day 9 is about. In her pencil: …go home… he held me… go… lamp… gave… went up… salt… stones…",
    req: ["b-3.1"],
    stretch: "st-salt",
    painting: "pt-b-4.A",
    carries: {"records": ["rec-s4"], "inView": ["seal-5-2"]},
  },
  {
    id: "b-4.4",
    kind: "step",
    w: 4,
    o: 5,
    line: "In the corner of every record along the tally, a hook closed on a dot. On the lamp's base, the same. On her sheet she has drawn it and written: signature? On the wall by the lamp, the hook in the corner is not this hook.",
    req: ["b-4.A"],
    stretch: "st-salt",
    carries: {"seen": ["mk-hand"]},
  },
  {
    id: "b-4.B",
    kind: "arrivalKey",
    w: 4,
    o: 6,
    name: "The salt block",
    line: "In a niche past the split, a count, and it fills. Inside, a block of salt, and cut into its face a hook closed on a dot, the size of a thumbnail. Beside it on the wall, a short line in the tally's hand.",
    seal: "seal-4-2",
    req: [],
    stretch: "st-salt",
    painting: "pt-b-4.B",
    carries: {"records": ["rec-x-neighbour"]},
  },
  // NOTE: inView seal-4-4 (the Lower Door's count: seen, not sealed, NICHES 4.4).
  {
    id: "b-4.C",
    kind: "arrival",
    w: 4,
    o: 7,
    name: "The Lower Door, close",
    line: "At the far end of the hall, the great door: a count with empty strokes and, beside a blank, two marks: the bar-with-a-drop, and two drops parted. Under the count, a mark like a path doubling back.",
    req: [],
    stretch: "st-hall",
    painting: "pt-b-4.C",
    carries: {"inView": ["seal-4-4"]},
  },
  {
    id: "b-w4.camp",
    kind: "camp",
    w: 4,
    o: 8,
    line: "The lamp. Someone cut three marks on its base, and one of them is the first mark of every line of the tally.",
    req: [],
    stretch: "st-hall",
    morning: "the different hook on the wall by the lamp, highlighted once",
  },
  {
    id: "b-w4.close",
    kind: "close",
    w: 4,
    o: 10,
    line: "The Lower Door: two marks, and a count with every stroke empty.",
    req: [],
    stretch: "st-hall",
  },
  // ---- Week 5 ----
  {
    id: "b-5.0",
    kind: "step",
    w: 5,
    o: 1,
    line: "The second flight. The count on the little door is full, every stroke, and the door is shut. Beside it, a ring cut sharp-edged among thousands worn smooth.",
    req: [],
    stretch: "st-flight2",
    carries: {"records": ["rec-k2"]},
  },
  {
    id: "b-5.1",
    kind: "stepKey",
    w: 5,
    o: 2,
    line: "The recess under the second turn. Its count fills. Inside, a tablet with a bar-and-tick beside a picture of a setting sun, and a bar-with-a-drop beside a picture of a road, and the same bar with its drop at the far end.",
    seal: "seal-5-1",
    req: [],
    stretch: "st-flight2",
    carries: {"guess": ["mk-once", "mk-path", "mk-go"]},
  },
  {
    id: "b-5.A",
    kind: "arrival",
    w: 5,
    o: 3,
    name: "The tally, from the head",
    line: "Every record along the tally begins with the same three things: the bar with a tick, a ring, a single drop. The line on the wall by the lamp does not begin with it. There, the bar with a tick comes second.",
    choice: ["Look at the first stretch again", "look at the wall by the lamp"],
    req: ["seal-5-1"],
    stretch: "st-salt",
    painting: "pt-b-5.A",
  },
  {
    id: "b-5.2",
    kind: "step",
    w: 5,
    o: 4,
    line: "The notebook, Day 14.",
    req: ["b-5.A"],
    stretch: "st-camp",
    carries: {"records": ["rec-l7"]},
  },
  {
    id: "b-5.B",
    kind: "arrival",
    w: 5,
    o: 5,
    name: "Through a gap",
    line: "On the second flight, a gap in the wall at shoulder height: beyond it, another gallery, square-cut stone meeting the rounded stone, and on its wall a record in the tally's hand that begins with the same three marks, but the last of them is two drops where the tally has one.",
    req: [],
    stretch: "st-flight2",
    painting: "pt-b-5.B",
    carries: {"records": ["rec-v1"]},
  },
  {
    id: "b-5.3",
    kind: "stepKey",
    w: 5,
    o: 6,
    line: "The Salt Gallery: the crust's count fills. Behind the salt, a stretch of the tally. In it, three marks stand in a row: the lamp's, the flame's, the hook-and-drop's, and no doorway-shape near them.",
    seal: "seal-5-2",
    req: [],
    stretch: "st-salt",
    carries: {"records": ["rec-s5"]},
  },
  {
    id: "b-w5.camp",
    kind: "camp",
    w: 5,
    o: 7,
    line: "The lamp, lit. On the base, the flame, the hook-and-drop, the bar with a tick.",
    req: [],
    stretch: "st-hall",
    morning: "L8 next",
  },
  {
    id: "b-w5.close",
    kind: "close",
    w: 5,
    o: 9,
    line: "Down the stair, a gallery of square-cut stone meets this one.",
    req: [],
    stretch: "st-flight2",
  },
  // ---- Week 6 ----
  {
    id: "b-6.A",
    kind: "arrival",
    w: 6,
    o: 1,
    name: "The side passage",
    line: "From the Stair's second landing, a low doorway into the gallery seen through the gap. Its walls meet at corners, and where the square stone meets the rounded stone the two are cut into each other like two hands clasped. On the square wall, the record, close: …way [ ] [ ] here [ ] once… person [ ] went deep [ ]; fire. One went deep. A lamp, lit. One other.",
    choice: ["Read it", "go on"],
    req: ["b-5.B"],
    stretch: "st-square",
    painting: "pt-b-6.A",
    carries: {"records": ["rec-v1"]},
  },
  {
    id: "b-6.1",
    kind: "step",
    w: 6,
    o: 2,
    line: "The notebook, Day 20. In the gutter of the page, chips of stone.",
    req: ["b-6.A"],
    stretch: "st-camp",
    carries: {"records": ["rec-l8"]},
  },
  {
    id: "b-6.2",
    kind: "stepKey",
    w: 6,
    o: 3,
    line: "The Salt Gallery's last hidden stretch. The count on the crust fills. Behind it, a tablet: two drops parted beside a doorway; a hook closed on a drop over a bar, beside a loaf. Past the tablet, the tally goes on.",
    seal: "seal-6-1",
    req: [],
    stretch: "st-salt",
    carries: {"guess": ["mk-open", "mk-eat"]},
  },
  {
    id: "b-6.B",
    kind: "arrivalKey",
    w: 6,
    o: 4,
    name: "The crew's wall",
    line: "On the square wall, a second record in the tally's hand, longer than the first: …one ate [ ], person [ ]… [ ] [ ] one: way [ ] [ ] [ ]… gave [ ] [ ] [ ]; door open… person [ ] gave [ ]. One span of it is on her sheets: …he held us…. Under the record, a niche with a count, and the count fills: a wax tablet gone hard, ruled in rows, with a ring at the head of every row.",
    choice: ["Read the record", "look at the tablet"],
    seal: "seal-6-2",
    req: [],
    stretch: "st-square",
    painting: "pt-b-6.B",
    carries: {"records": ["rec-v2", "rec-x-foreman"]},
  },
  {
    id: "b-6.3",
    kind: "step",
    w: 6,
    o: 5,
    line: "On the gallery floor, a mule-shoe, and beside it a stone with a halter's rub worn into it. On the wall above the stone, a short line: [ ]: [a mule] went deep [ ]; me [ ] [ ].",
    req: ["b-6.B"],
    stretch: "st-square",
    carries: {"records": ["rec-x-mule"], "inView": ["seal-6-4"]},
  },
  {
    id: "b-w6.camp",
    kind: "camp",
    w: 6,
    o: 6,
    line: "Beside the lamp, the carved one on the wall, its cuts sharp-edged.",
    req: [],
    stretch: "st-hall",
    morning: "S2 re-rendered: ate [ ] now shows the sign for EAT in Dan's layer",
  },
  {
    id: "b-w6.close",
    kind: "close",
    w: 6,
    o: 8,
    line: "Down the second flight, a lintel with a blank beside two marks. One is the path's.",
    req: [],
    stretch: "st-flight2",
  },
  // ---- Week 7 ----
  {
    id: "b-7.1",
    kind: "stepKey",
    w: 7,
    o: 1,
    line: "A niche in the square gallery: the count fills. A tablet: an inverted wedge beside the sky; a wedge on a bar beside a block; a small figure beside a child's tablet.",
    seal: "seal-7-1",
    req: [],
    stretch: "st-square",
    carries: {"guess": ["mk-up", "mk-stone", "mk-child"]},
  },
  {
    id: "b-7.A",
    kind: "word",
    w: 7,
    o: 2,
    name: "The lintel at the foot of the second flight",
    taps: ["The rod's edge, in the blank.", "The first mark: the bar with a drop.", "The second: the two drops parted.", "The cuts fill with light, and the rod rings once, and the stone under the lintel is not there. The Stair goes on down, lit."],
    req: ["seal-7-1", "mk-path", "mk-open"],
    stretch: "st-flight2",
    painting: "pt-b-7.A",
    carries: {"word": "wd-open-way"},
  },
  {
    id: "b-7.2",
    kind: "step",
    w: 7,
    o: 3,
    line: "The tally, past the crust. In it, a barn, and in the barn an owl, cut by someone who has not seen one: …[ ] gave child: up [a barn] [an owl] here… ate [ ]; [ ] [ ]; [ ]… child [ ]: [ ] [ ]…",
    req: ["b-7.A"],
    stretch: "st-salt",
    carries: {"records": ["rec-s6"]},
  },
  // NOTE: ARR2 carries V3 and X-boy here; MVP_CONTENT §4 gives them no rec- ids, so records are left out.
  {
    id: "b-7.B",
    kind: "arrivalKey",
    w: 7,
    o: 4,
    name: "The crew's wall, again",
    line: "Below the second record, twelve rings in a row, and a thirteenth, smaller: …person [ ], child one [a tablet]… In the niche beneath, its count filled, a wax tablet gone hard: twenty marks, some backwards, and one fork with nothing under it. Beside three of them, in the tally's hand, the same three: beside, not over.",
    seal: "seal-7-2",
    req: [],
    stretch: "st-square",
    painting: "pt-b-7.B",
  },
  {
    id: "b-7.3",
    kind: "stepKey",
    w: 7,
    o: 5,
    line: "The Stair's first turn: the rail. The count in the recess beside it fills. Where a hand rested on the rail, the stone has taken its shape: four fingers, and long.",
    seal: "seal-7-3",
    req: [],
    stretch: "st-stair",
  },
  {
    id: "b-7.4",
    kind: "stepKey",
    w: 7,
    o: 6,
    line: "A cache in the gallery wall: its count fills. Twelve bronze coins and one clay token in a bag gone hard, and a line beside it: Once, [ ] gave me [a bag]: [ ] person [ ], child one; [ ] [ ]. [ ] door once, [ ] [ ] [ ]. I [ ] it.",
    seal: "seal-7-4",
    req: [],
    stretch: "st-square",
  },
  // NOTE: a Key arrival that is also the word again: kind 'word' with `seal`; `line` is the preface shown before the taps.
  {
    id: "b-7.C",
    kind: "word",
    w: 7,
    o: 7,
    name: "The great door",
    line: "At the far end of the hall, beside the door's blank, the same two marks as the lintel's, and under them the count.",
    taps: ["The rod's edge, in the blank.", "The first mark: the bar with a drop.", "The second: the two drops parted.", "The count fills stroke by stroke, and the door is not there. Beyond it, a stair twice as steep, and the hall's light goes down eleven steps of it and stops."],
    choice: ["Go down as far as the light", "go back along the hall"],
    seal: "seal-7-5",
    req: ["b-7.A"],
    stretch: "st-hall",
    painting: "pt-b-7.C",
    carries: {"word": "wd-open-way"},
  },
  {
    id: "b-w7.camp",
    kind: "camp",
    w: 7,
    o: 8,
    line: "The lamp. The great door at the far end is open now, and cold air comes up it.",
    req: [],
    stretch: "st-hall",
    morning: "the map: two ways down, both ending in the dark",
  },
  {
    id: "b-w7.close",
    kind: "close",
    w: 7,
    o: 10,
    line: "Both ways down end at water that does not move.",
    req: [],
    stretch: "st-hall",
  },
  // ---- Places with no fragment (MVP_CONTENT §2) ----
  {
    id: "pl-w1-pick-niche",
    kind: "arrival",
    w: 1,
    o: 3,
    name: "The pick niche",
    line: "Low in the Salt Gallery's wall, a niche the length of an arm, and on its lip a row of cut strokes, every one of them empty. The salt beside it is scored with short cuts, close together.",
    req: [],
    stretch: "st-salt",
    painting: "pt-pl-w1-pick-niche",
    carries: {"inView": ["seal-1-2"]},
  },
  {
    id: "pl-w1-below-the-lamp",
    kind: "arrival",
    w: 1,
    o: 5,
    name: "Below the lamp",
    line: "Under the ledge, at the height of your knee, a small niche with a row of cut strokes on its lip. The stone round its mouth is darker than the rest, and greasy to the touch.",
    req: [],
    stretch: "st-hall",
    painting: "pt-pl-w1-below-the-lamp",
    carries: {"inView": ["seal-1-3"]},
  },
  {
    id: "pl-w2-above-the-ring",
    kind: "arrival",
    w: 2,
    o: 2,
    name: "Above the ring",
    line: "Over the lone ring, the salt has a crack in it two fingers wide, and a count cut beside it, small. Far back in the crack, something pale, too far in to reach.",
    req: ["seal-1-1"],
    stretch: "st-salt",
    painting: "pt-pl-w2-above-the-ring",
    carries: {"inView": ["seal-2-3"]},
  },
  // NOTE: §2 names "the corner's troughs" here; inView is seal-2-4, the seen-not-sealed smooth place NICHES 2.4 says this place is.
  {
    id: "pl-w2-smooth-place",
    kind: "arrival",
    w: 2,
    o: 4,
    name: "The smooth place",
    line: "At the corner, on the polished wall, one patch where the marks are rubbed away altogether, at the height of a long hand. The stone there has gone smooth the way a banister does.",
    req: ["b-1.B"],
    stretch: "st-hall",
    painting: "pt-pl-w2-smooth-place",
    carries: {"inView": ["seal-2-4"]},
  },
  {
    id: "pl-w2-box-by-the-cot",
    kind: "arrival",
    w: 2,
    o: 5,
    name: "The box by the cot",
    line: "In her camp, pushed against the wall, a box the size of a shoebox with a thin slate laid across its lid, and a count cut in the slate. On the slate, a tin mug, upside down.",
    req: ["b-1.C"],
    stretch: "st-camp",
    painting: "pt-pl-w2-box-by-the-cot",
    carries: {"inView": ["seal-2-5"]},
  },
  {
    id: "pl-w3-salt-lit",
    kind: "arrival",
    w: 3,
    o: 3,
    name: "The salt, lit",
    line: "In the glow that comes round the corner from the lit hall, the salt is banded grey and pink, and it glitters. The stones packed in the split are river stones, round and brown, carried up from somewhere with water in it.",
    req: ["b-3.A"],
    stretch: "st-salt",
    painting: "pt-pl-w3-salt-lit",
  },
  {
    id: "pl-w3-far-end",
    kind: "arrival",
    w: 3,
    o: 5,
    name: "The far end",
    line: "The last lamp before the far end is a stride from the great door, and in its light the door goes up past where the flames reach, into the curve of the ceiling. Cold comes off its face, the way it comes off a window in winter.",
    req: ["b-3.A"],
    stretch: "st-hall",
    painting: "pt-pl-w3-far-end",
  },
  {
    id: "pl-w4-hollow",
    kind: "arrival",
    w: 4,
    o: 2,
    name: "The hollow",
    line: "Low in the salt, a hollow the size of two cupped hands, worn smooth inside, and a count on its rim. The salt at the bottom is pressed flat in four small places.",
    req: [],
    stretch: "st-salt",
    painting: "pt-pl-w4-hollow",
    carries: {"inView": ["seal-4-5"]},
  },
  {
    id: "pl-w4-recess-above-the-cot",
    kind: "arrival",
    w: 4,
    o: 4,
    name: "The recess above the cot",
    line: "Above her cot, at the height of a raised arm, a recess in the wall, closed by a slate with a count on it. Beside it, a drawing pin pushed into a crack, on its own.",
    req: ["b-1.C"],
    stretch: "st-camp",
    painting: "pt-pl-w4-recess-above-the-cot",
    carries: {"inView": ["seal-4-3"]},
  },
  {
    id: "pl-w5-ledge-lip",
    kind: "arrival",
    w: 5,
    o: 2,
    name: "The ledge's lip",
    line: "Under the lamp's ledge the stone is cut too: a small count, low enough that nobody standing would see it.",
    req: [],
    stretch: "st-hall",
    painting: "pt-pl-w5-ledge-lip",
    carries: {"inView": ["seal-5-5"]},
  },
  {
    id: "pl-w5-worn-steps",
    kind: "arrival",
    w: 5,
    o: 3,
    name: "The worn steps",
    line: "Halfway down the top flight, every step is worn in two places a stride apart, and the stride is longer than yours. The rail beside them shines along its top.",
    req: ["b-3.C"],
    stretch: "st-stair",
    painting: "pt-pl-w5-worn-steps",
  },
  {
    id: "pl-w5-second-landing",
    kind: "arrival",
    w: 5,
    o: 5,
    name: "The second landing",
    line: "Where the second flight turns, a landing as wide as the hall above, and the lamps along its wall are lit. In the wall across from the stair, a doorway too low for whoever made the stair, square at the corners.",
    req: ["b-4.1"],
    stretch: "st-flight2",
    painting: "pt-pl-w5-second-landing",
  },
  {
    id: "pl-w6-square-gallery",
    kind: "arrival",
    w: 6,
    o: 2,
    name: "The square gallery",
    line: "The gallery runs straight, as tall as a tall man and no taller, its ceiling flat and its walls covered in small, even chisel marks. There are no cups in these walls. The light comes in from the round stone and gives out. Far down, the floor goes under a slope of broken stone.",
    req: ["b-6.A"],
    stretch: "st-square",
    painting: "pt-pl-w6-square-gallery",
  },
  {
    id: "pl-w6-wall-shelf",
    kind: "arrival",
    w: 6,
    o: 4,
    name: "The wall-shelf",
    line: "A shelf cut into the square wall at the height of your chest, with a count on its lip. Along the shelf's edge someone has scratched a line, dead level, with a short tick at each end.",
    req: ["pl-w6-square-gallery"],
    stretch: "st-square",
    painting: "pt-pl-w6-wall-shelf",
    carries: {"inView": ["seal-6-3"]},
  },
  {
    id: "pl-w6-folder",
    kind: "arrival",
    w: 6,
    o: 5,
    name: "Her folder",
    line: "Under her cot, pushed to the back, a document folder with an elastic band round it, and a thin slate on its cover with a count. On the folder's spine, in marker: HILL.",
    req: ["b-1.C"],
    stretch: "st-camp",
    painting: "pt-pl-w6-folder",
    carries: {"inView": ["seal-6-5"]},
  },
];
