/**
 * SEALED STORY CONTENT (D-015). Never shown to Dan outside the game.
 * Transcribed from docs/narrative/sealed/ (ARRIVALS_REGION1.md weeks 1-5, ARRIVALS_REGION2.md weeks 6-7,
 * MVP_CONTENT.md §0-§3). Those files are authoritative; fix them first, then this.
 */
import type { CampView } from '../../core/story-types';

// NOTE: CampView has no `painting` field; each view's painting is `pt-<id>` (e.g. pt-cv-03, PAINTING_BRIEFS.md).
/** Camps with a view (MVP_CONTENT §3): a day that completes short of the next named place ends at one for the current stretch. */
export const camps: CampView[] = [
  {
    id: "cv-01",
    stretch: "st-mouth",
    w: 1,
    req: [],
    name: "The ladder's foot",
    line: "Eleven metres above, a square of white sky sits at the top of the shaft. The ladder climbs towards it while the air slips past you and out.",
    look: {"find": "fd-a02"},
  },
  {
    id: "cv-02",
    stretch: "st-mouth",
    w: 1,
    req: [],
    name: "The pipe",
    line: "The passage leaves the ladder in a single slow curve, floor and walls running together. It bends so gently that you notice the turn only where the light fails.",
    look: {"find": "fd-a05"},
  },
  {
    id: "cv-03",
    stretch: "st-hall",
    w: 1,
    req: [],
    until: "b-3.A",
    name: "The hall, from the passage",
    line: "Just inside, the lamp burns on its ledge. Beyond it the hall goes on into darkness.",
    look: {"find": "fd-b12"},
  },
  {
    id: "cv-04",
    stretch: "st-hall",
    w: 3,
    req: ["b-3.A"],
    name: "The hall, from the far end",
    line: "From the great door, two rows of flame lead back through the hall to the lamp’s ledge. Around the corner, light lies across the salt.",
    look: {"find": "fd-b11"},
  },
  {
    id: "cv-05",
    stretch: "st-hall",
    w: 1,
    req: [],
    name: "In the trough",
    line: "You stand with one foot in one of the troughs at the corner. The other runs beside it, a stride away, equally deep and smooth.",
    look: {"find": "fd-c01"},
  },
  {
    id: "cv-06",
    stretch: "st-salt",
    w: 1,
    req: [],
    name: "The salt, close",
    line: "At arm’s length, the salt face resolves into bands of grey and white. Fine crystals skin the split where air leaks through.",
    look: {"find": "fd-c09"},
  },
  {
    id: "cv-07",
    stretch: "st-salt",
    w: 2,
    req: [],
    name: "The tally, end on",
    line: "Seen lengthways, the tally is a dark seam along the gallery wall, running from the first stretch into the unlit salt beyond.",
    look: {"find": "fd-c12"},
  },
  {
    id: "cv-08",
    stretch: "st-camp",
    w: 1,
    req: [],
    name: "Her cot",
    line: "From the doorway, her camp is all stillness: the cot, the boots beneath it, the notebook with its pencil, the shelf.",
    look: {"find": "fd-d08"},
  },
  {
    id: "cv-09",
    stretch: "st-camp",
    w: 2,
    req: ["b-2.B"],
    name: "Her shelf",
    line: "On the shelf where the rod lay, the dust is broken by one clean stripe the length of a forearm.",
    look: {"line": "For the next one. Cut the two marks on the lintel. Don’t be precious about it."},
  },
  {
    id: "cv-10",
    stretch: "st-stair",
    w: 3,
    req: [],
    name: "The landing",
    line: "The landing at the head of the Stair is broad enough for a cart. From its edge, the flight descends into lamplight you did not light.",
    look: {"find": "fd-e07"},
  },
  {
    id: "cv-11",
    stretch: "st-stair",
    w: 3,
    req: [],
    name: "Halfway down",
    line: "Halfway down the top flight, each step comes almost to your knee. The rail runs level with your chest.",
    look: {"find": "fd-e09"},
  },
  {
    id: "cv-12",
    stretch: "st-stair",
    w: 4,
    req: [],
    name: "The first turn",
    line: "The rail turns with the stair. Below it, the second flight drops away; a small counted door is set into the wall.",
    look: {"find": "fd-e05"},
  },
  {
    id: "cv-13",
    stretch: "st-flight2",
    w: 5,
    req: ["b-5.0"],
    name: "The second flight",
    line: "The little door remains shut although its count is full. Beside it, one sharp-cut ring sits among all the worn ones.",
    look: {"find": "fd-f02"},
  },
  {
    id: "cv-14",
    stretch: "st-flight2",
    w: 5,
    req: ["b-5.B"],
    name: "The gap",
    line: "Through the shoulder-high gap you can see square stone beyond. A draught slips through carrying the smell of old smoke.",
    look: {"find": "fd-f06"},
  },
  {
    id: "cv-15",
    stretch: "st-square",
    w: 6,
    req: [],
    name: "The join",
    line: "The square-cut stone and the rounded stone meet so closely that a blade would not enter the join.",
    look: {"find": "fd-g09"},
  },
];
