/**
 * SEALED STORY CONTENT (D-015). Never shown to Dan outside the game.
 * Transcribed from docs/narrative/sealed/ (ARRIVALS_REGION1.md weeks 1-5, ARRIVALS_REGION2.md weeks 6-7,
 * MVP_CONTENT.md §0-§3). Those files are authoritative; fix them first, then this.
 */
import type { CampView } from '../../core/story-types';

// NOTE: CampView has no `painting` field; each view's painting is `pt-<id>` (e.g. pt-cv-03, PAINTING_BRIEFS.md).
/** Camps with a view (MVP_CONTENT §3): a day that completes short of the next named place ends at one for the current stretch. */
export const camps: CampView[] = [
  {
    id: "cv-01",
    stretch: "st-mouth",
    w: 1,
    req: [],
    name: "The ladder's foot",
    line: "Eleven metres up, a square of white sky, and the ladder going up to it. The air moves up past you and out.",
    look: {"find": "fd-a02"},
  },
  {
    id: "cv-02",
    stretch: "st-mouth",
    w: 1,
    req: [],
    name: "The pipe",
    line: "The passage from the ladder, floor and walls one curve, bending away so gently you only see it by where the light gives out.",
    look: {"find": "fd-a05"},
  },
  {
    id: "cv-03",
    stretch: "st-hall",
    w: 1,
    req: [],
    until: "b-3.A",
    name: "The hall, from the passage",
    line: "Just inside, the lamp on its ledge, and past it the hall going away into the dark.",
    look: {"find": "fd-b12"},
  },
  {
    id: "cv-04",
    stretch: "st-hall",
    w: 3,
    req: ["b-3.A"],
    name: "The hall, from the far end",
    line: "From the great door, the two lines of flames go back up the hall to the ledge. Beside you, round the corner, a glow on the salt.",
    look: {"find": "fd-b11"},
  },
  {
    id: "cv-05",
    stretch: "st-hall",
    w: 1,
    req: [],
    name: "In the trough",
    line: "You stand in one of the two troughs at the corner. The other is a stride away, the same depth, the same smoothness.",
    look: {"find": "fd-c01"},
  },
  {
    id: "cv-06",
    stretch: "st-salt",
    w: 1,
    req: [],
    name: "The salt, close",
    line: "The salt face at arm's length: bands of grey and white, and a skin of fine crystals where the air comes through the split.",
    look: {"find": "fd-c09"},
  },
  {
    id: "cv-07",
    stretch: "st-salt",
    w: 2,
    req: [],
    name: "The tally, end on",
    line: "Looking along the gallery wall, the tally is a line of shadow from the first stretch to the dark.",
    look: {"find": "fd-c12"},
  },
  {
    id: "cv-08",
    stretch: "st-camp",
    w: 1,
    req: [],
    name: "Her cot",
    line: "Her camp from the doorway: the cot, the boots under it, the notebook with the pencil in it, a shelf.",
    look: {"find": "fd-d08"},
  },
  {
    id: "cv-09",
    stretch: "st-camp",
    w: 2,
    req: ["b-2.B"],
    name: "Her shelf",
    line: "The shelf where the rod lay, a clean stripe in the dust the length of a forearm.",
    look: {"line": "For the next one. Cut the two marks on the lintel. Don't be precious about it."},
  },
  {
    id: "cv-10",
    stretch: "st-stair",
    w: 3,
    req: [],
    name: "The landing",
    line: "At the head of the stair, the landing wide enough for a cart, and the flight going down into lamplight you did not light.",
    look: {"find": "fd-e07"},
  },
  {
    id: "cv-11",
    stretch: "st-stair",
    w: 3,
    req: [],
    name: "Halfway down",
    line: "The top flight from its middle: every step as high as your knee, the rail at your chest.",
    look: {"find": "fd-e09"},
  },
  {
    id: "cv-12",
    stretch: "st-stair",
    w: 4,
    req: [],
    name: "The first turn",
    line: "The rail curls round the turn, and below it the second flight goes down, and on it a small door with a count.",
    look: {"find": "fd-e05"},
  },
  {
    id: "cv-13",
    stretch: "st-flight2",
    w: 5,
    req: ["b-5.0"],
    name: "The second flight",
    line: "The little door, shut, its count full; beside it the one sharp ring among the worn.",
    look: {"find": "fd-f02"},
  },
  {
    id: "cv-14",
    stretch: "st-flight2",
    w: 5,
    req: ["b-5.B"],
    name: "The gap",
    line: "Through the gap at shoulder height, square stone, and a draught that smells of old smoke.",
    look: {"find": "fd-f06"},
  },
  {
    id: "cv-15",
    stretch: "st-square",
    w: 6,
    req: [],
    name: "The join",
    line: "The square stone and the round fit so close you couldn't get a blade in the join.",
    look: {"find": "fd-g09"},
  },
];
