/**
 * SEALED (D-015): story content. Never shown to Dan outside the game.
 * Transcribed from docs/narrative/sealed/MVP_CONTENT.md §8.1 (the Truth column is never shipped); those files are authoritative.
 */

import type { Find } from '../../core/story-types';

export const finds: Find[] = [
  { id: "fd-a01", stretch: "st-mouth", w: 1, req: ["b-1.1"],   /* below the climb: never before it is told (round 5) */ line: "At the bottom of the shaft, where the ladder meets the floor, an old rung lies in the dust, bent in the middle like a bow. You look up the ladder. Just above, one rung is newer than all the others. It looks as if the old one bent, and someone fitted a new one in its place." },
  { id: "fd-a02", stretch: "st-mouth", w: 1, req: ["b-1.1"],   /* below the climb: never before it is told (round 5) */ line: "On the brick wall at the foot of the ladder, someone has drawn an arrow in old chalk, pointing straight up the shaft. Beside it is written: 36 FT. That seems to be the depth of the shaft in feet, the same eleven metres the ladder runs." },
  { id: "fd-a03", stretch: "st-mouth", w: 1, req: [], until: "b-3.A", line: "Tucked under the rim of the iron cap lying in the grass, you spot a cereal-bar wrapper. It has been folded small and pushed in with the foil side out, tucked away rather than dropped. It looks fairly recent. You leave it where it is." },
  { id: "fd-a04", stretch: "st-mouth", w: 1, req: ["b-1.1"],   /* below the climb: never before it is told (round 5) */ until: "b-3.A", line: "At the bottom of the shaft, you look at where the brick lining stops. The last row of bricks sits straight on the stone below, with no mortar between them. The stone was here first: the brick shaft seems to have been built down onto it." },
  { id: "fd-a05", stretch: "st-mouth", w: 1, req: ["b-1.1"],   /* below the climb: never before it is told (round 5) */ line: "From the ladder you walk a few paces into the passage, the smooth tunnel leading into the hill. The dust on its floor is full of bootprints, all the same size, going in and coming out. There are so many that they have worn a path, like a track across a lawn. It looks as if one person walked here many, many times." },
  { id: "fd-a06", stretch: "st-mouth", w: 1, req: ["b-1.1"],   /* below the climb: never before it is told (round 5) */ line: "A length of blue rope, the modern kind used for climbing or boating, is tied to the bottom rung of the ladder. You pick up its loose end. The rope has been cut, and the cut end melted into a hard knob, as if someone sealed it on purpose to stop it fraying." },
  { id: "fd-b01", stretch: "st-hall", w: 1, req: [], line: "At the near end of the Lamp Hall, you look at the front edge of the ledge where the lamp stands. Something has run over the lip and set there: a drip of glaze, the glassy coating on pottery, the same colour as the lamp. You touch it with a fingertip. It is as hard as glass. It looks as if it ran there while still wet and hardened where it stopped; how it came to be there, you cannot tell." },
  { id: "fd-b02", stretch: "st-hall", w: 3, req: ["b-3.A"], line: "In the lit Lamp Hall, you look closely into one of the cups. The flame has no wick. It stands straight up from the flame's symbol cut into the cup's bottom, as if it burns on the symbol itself, with nothing to feed it." },
  { id: "fd-b03", stretch: "st-hall", w: 6, req: ["b-6.1"],   /* R2 after the fact (MVP_CONTENT): in week 3 it would answer R2 three weeks early beside C-57 and NICHES 3.4 (D-160 check); a top find, so since D-160 only an old save still at the top after L8 is given it */ line: "On the wall by the lamp, beside the ledge, you look again at the small carved picture of a lamp. Under it, faint in pencil, is a grid of small squares, the kind you draw before you cut, like the guide lines a sign-writer rules before lettering." },
  { id: "fd-b04", stretch: "st-hall", w: 1, req: [], line: "Standing by the ledge, you look up at the ceiling. Old soot is spread across the stone above it in the shape of a fan, thick and black at its point and fading outwards. Something seems to have burned here for a very long time." },
  { id: "fd-b05", stretch: "st-hall", w: 1, req: [], until: "b-3.A", line: "On the floor beside the ledge, five candle stubs stand in a row. Each has burned right down to the stone. They look like the leftovers of someone else's light, brought down here and used up. You leave them in their row." },
  { id: "fd-b06", stretch: "st-hall", w: 3, req: ["b-3.A"], line: "Near the corner of the Lamp Hall, one cup was broken at the lip and has been mended with a paste of the same stone, like a chipped basin filled in. Inside it, the flame's symbol is whole, and its flame burns like the others." },
  { id: "fd-b07", stretch: "st-hall", w: 1, req: [], line: "You walk to the far end of the Lamp Hall, beyond the reach of the light, and stop at the foot of the great door, the huge door that fills most of the end wall. Along the floor at its base the dust lies in a line, finer than anywhere else, as if air has moved under the door for a long time.", until: "b-3.A" },
  { id: "fd-b08", stretch: "st-hall", w: 1, req: ["b-1.5"],   /* it names the Salt Gallery and the tally: after both are shown (D-154 review; round 1, item 3) */ line: "Beside the ledge, you peer into a crack in the stone. The burnt end of a wick lies inside. Next to it, a short line of tiny symbols is cut into the stone. The cutting looks like the work of whoever cut the tally.", told: "tl-wick" }, // side chamber
  { id: "fd-b09", stretch: "st-hall", w: 1, req: [], line: "You crouch and look under the ledge. A thin flake of glaze lies on the floor there, like a chip off a glazed pot. It is one shade darker than the lamp above. You do not disturb it." },
  { id: "fd-b10", stretch: "st-hall", w: 1, req: [], until: "b-1.C",   /* b-1.C's own first sentence is this arrow since round 1 (item 4) */ line: "On the floor of the Lamp Hall, someone has drawn an arrow in chalk. It points to a round-topped doorway in the side wall, the way into a small side chamber. Beside the arrow, also in chalk, is the word CAMP. It looks as if someone has been living in there." },
  { id: "fd-b11", stretch: "st-hall", w: 3, req: ["b-3.A"], line: "In the Lamp Hall, now that the cups are lit, you look up. There are rings on the ceiling too, small carved circles like those on the walls, cut high overhead." },
  { id: "fd-b12", stretch: "st-hall", w: 1, req: [], line: "At the ledge, you lean close to the lamp, the small clay oil lamp that stands there burning, and breathe gently on its flame. An ordinary flame would flicker. This one does not bend at all. You try again, harder. It stays perfectly upright." },
  { id: "fd-c01", stretch: "st-hall", w: 1, req: ["b-1.B"], until: "b-3.A", line: "At the far end of the Lamp Hall, by the great door, the hall turns a corner. Two long troughs are worn into the floor there, smooth inside like basins. In the bottom of one lies a dry leaf, brown and crumbling, the kind that grows on a hedge. It looks as if it found its way in from outside somehow." },
  { id: "fd-c02", stretch: "st-salt", w: 1, req: [], line: "You walk along the Salt Gallery, the long, low passage beside the wall of rock salt, to where it first turns. There, a knot of wool gone grey with age is tied round a knob of salt on the wall. Beside it, a short line of symbols is cut into the salt. Both look very old.", told: "tl-wool" }, // side chamber
  { id: "fd-c03", stretch: "st-salt", w: 2, req: ["b-1.5"],   /* names the tally (round 1, item 3) */ line: "In the Salt Gallery, tucked into a crack in the salt wall, lies a small cake of salt, a little shaped block. A thumbprint is pressed into it, as if someone pressed it into shape by hand. Under it is a short line of symbols, cut by whoever cut the tally.", told: "tl-salt-cake" }, // side chamber
  { id: "fd-c04", stretch: "st-salt", w: 1, req: ["b-1.5"],   /* names the tally (round 1, item 3) */ line: "In the Salt Gallery, a small chip of salt lies loose at the foot of the wall. You bend to look at it without picking it up. It is scratched with short strokes in rows of five, like the marks people make in fives when keeping score. Beside it, a short line of symbols is cut by whoever cut the tally.", told: "tl-count" }, // side chamber
  { id: "fd-c05", stretch: "st-salt", w: 2, req: [], line: "Further along the Salt Gallery, a carrying pole lies in the salt: a length of wood for bearing loads across the shoulders. It is worn smooth in two grooves, as if loads hung from it there. Beside it, a few symbols are cut into the salt.", told: "tl-yoke" }, // side chamber
  { id: "fd-c06", stretch: "st-salt", w: 1, req: [], until: "b-3.A", line: "Further along the Salt Gallery, a bronze awl, a small pointed tool for making holes, is stuck point first in a crack in the salt. The bronze has gone green. It looks very old, and it has been left exactly where it was pushed in." },
  { id: "fd-c07", stretch: "st-salt", w: 1, req: [], line: "On the floor of the Salt Gallery lies a strip of animal hide, knotted into a loop like a leather tie. You pick it up. It has dried as hard as wood and will not bend. You set it back down where it lay." },
  { id: "fd-c08", stretch: "st-salt", w: 1, req: ["b-1.5"],   /* names the tally (round 1, item 3) */ until: "b-3.6", line: "In the narrow crack beside the tally, with the loose pencilled sheets, lies a pencil, sharpened and used until it is no longer than your thumb. Whoever wrote the sheets seems to have written a great deal." },
  { id: "fd-c09", stretch: "st-salt", w: 1, req: ["b-1.5"], until: "b-3.A",   /* names the tally (round 1, item 3) */ line: "You bend close to the tally on the Salt Gallery wall. In its lowest cuts, salt has grown into small crystals, like frost in a crack. Those cuts look as if they have been there a long time." },
  { id: "fd-c10", stretch: "st-salt", w: 1, req: ["b-1.5"], until: "b-3.A", line: "You stop by the split, the crack down the salt wall that looks as if it was blocked up from the other side. In the salt floor beside it is the print of a sandal, set hard, with the lines of its straps still showing. It seems to have been made by someone in sandals, not boots." },
  { id: "fd-c11", stretch: "st-salt", w: 1, req: ["b-1.5"], line: "You look closely at the split in the salt wall, where stones and salt are packed tight into the crack. Between two of the stones is a plug of wool with salt worked into it, pushed in like stuffing to fill the last gap. You leave it in place." },
  { id: "fd-c12", stretch: "st-salt", w: 2, req: ["b-2.A"], line: "Above the tally, you look closely at the lone ring. It is one single cut, like a circle drawn without lifting the pen, with no place where it starts or stops." },
  { id: "fd-c13", stretch: "st-salt", w: 1, req: ["seal-1-2"], until: "b-3.A", line: "Now that the pick niche stands open, you crouch and look inside, past the bronze salt-pick. The niche's floor is scored with fine scratches where a pick has been laid down and taken up again, many times. It looks as if the pick was kept here, and used, for a very long time." },
  { id: "fd-c14", stretch: "st-salt", w: 2, req: ["b-2.A"], until: "b-3.6", line: "Among her sheets beside the tally, you turn over the one dated Day 4. On the back she has sketched the two troughs at the corner of the Lamp Hall and measured across them, and written: *stride?? 1.4 m* If that is a stride, it is far longer than yours." },
  { id: "fd-d01", stretch: "st-camp", w: 1, req: [], until: "b-3.2", line: "In the Box Room, the small side chamber where someone camped, you look at the notebook on the cot. The pencil tucked into it has a hair elastic wound round it, as if to keep it from slipping away." },
  { id: "fd-d02", stretch: "st-camp", w: 1, req: [], until: "b-3.A", line: "Among the papers in the Box Room is a page from an old railway timetable, printed on thin paper. One line is ringed in pencil, as if it mattered to someone. The station's name has been torn away, so you cannot tell where it was." },
  { id: "fd-d03", stretch: "st-camp", w: 1, req: [], until: "b-3.A", line: "In her camp in the Box Room, on the lid of a biscuit tin, lies a used tea bag, dried out until it is thin and stiff as paper. It seems to have been sitting there for some time." },
  { id: "fd-d04", stretch: "st-camp", w: 2, req: [], line: "In the Box Room, among her papers, is a photocopy of a page of handwriting in brown ink. At the top it says *Log.* The rest has come out grey in the copying, too faint to read. It looks like a copy of someone's old record book." },
  { id: "fd-d05", stretch: "st-camp", w: 1, req: [], until: "b-3.A", line: "In the Box Room you find a roll of black tape, like electrician's tape, and beside it a battery with its label peeled off. They look like the odds and ends of someone's kit." },
  { id: "fd-d06", stretch: "st-camp", w: 1, req: [], until: "b-3.A", line: "On the shelf in the Box Room, the cup from a thermos flask stands upside down. You turn it over. A brown ring has dried inside, as if a drink was left standing in it before it was put away." },
  { id: "fd-d07", stretch: "st-camp", w: 1, req: [], until: "b-3.A", line: "Lying in her camp in the Box Room is a crossword torn out of a newspaper. It is half filled in with pencil, as if someone stopped partway through. The date has been torn off, so there is no telling which day's paper it came from." },
  { id: "fd-d08", stretch: "st-camp", w: 1, req: [], line: "On the frame of the cot in the Box Room, a strip of masking tape is stuck down, with DAY 1 written on it in marker. It looks like the first day of a stay, marked the way you might mark a calendar." },
  { id: "fd-d09", stretch: "st-camp", w: 1, req: [], until: "b-3.A", line: "In the Box Room you find a box of matches and slide it open. Only three matches are left inside." },
  { id: "fd-d10", stretch: "st-camp", w: 3, req: ["b-3.A"],   /* before L8 (b-6.1), at the top (D-160) */ line: "In the Box Room, on the wall above her cot, are pencil tallies in fives, the way people keep score, row after row, with a line drawn under the last. It looks as if she was counting something, one stroke at a time, and then drew a line under it." },
  { id: "fd-d11", stretch: "st-camp", w: 1, req: [], until: "b-3.A", line: "In her camp in the Box Room, a paperback thriller lies face down, open at page 211, as if its reader put it down meaning to come back to it. You leave it as it is." },
  { id: "fd-d12", stretch: "st-camp", w: 1, req: [], until: "b-3.A", line: "By the doorway of the Box Room, a fleece hat hangs on a nail, ready to be grabbed on the way out." },
  { id: "fd-e01", stretch: "st-stair", w: 3, req: [], line: "On the Stair, one step's edge is chipped. Inside the chip, the stone is darker than the worn surface and threaded with something like glass, glinting like the inside of a broken rock." },
  { id: "fd-e02", stretch: "st-stair", w: 3, req: [], line: "At the edge of the landing at the head of the Stair lies a wax seal the size of a coin: a blob of wax once pressed with a stamp, the kind used to seal letters. The stamp is worn flat. Beside it, a short line of symbols is cut by whoever cut the tally, like a label.", told: "tl-seal" }, // side chamber
  { id: "fd-e03", stretch: "st-stair", w: 3, req: ["b-3.C"], line: "Down the wall of the top flight of the Stair runs a long band of polished stone, smooth as a banister, above the rail. It looks as if one hand went down this wall many times." },
  { id: "fd-e04", stretch: "st-stair", w: 3, req: ["b-4.2"], line: "At the first turn of the Stair, a bronze nail with a square head is driven into a crack in the stone. It looks old." },
  { id: "fd-e05", stretch: "st-stair", w: 3, req: ["b-3.C"], line: "On the Stair's rail, cut from the wall at the height of your chest, is a pencil tick, and beside it, in pencil like her notes: *1.3 m. Rail for somebody tall.* It seems she measured the rail's height." },
  { id: "fd-e06", stretch: "st-stair", w: 3, req: [], line: "On one of the Stair's steps lies a flake of candle wax, and beside it, pressed into the dust, is the print of a trainer's sole. Both look modern, as if someone came this way in trainers, carrying a candle." },
  { id: "fd-e07", stretch: "st-stair", w: 3, req: [], line: "On the wall at the head of the Stair's top flight is one ring, a small carved circle, set apart from the rest and cut deeper than they are. It looks placed there on purpose, at the start of the stair." },
  { id: "fd-e08", stretch: "st-stair", w: 4, req: ["b-4.2"], line: "At the first turn of the Stair, a rope has worn a groove round the front edge of one step, as if it was pulled over that edge many times. Caught in the groove is a single thread of blue." },
  { id: "fd-e09", stretch: "st-stair", w: 3, req: [], line: "In the wall of the Stair's top flight, at head height, is a row of small cut hollows, each the size of a fingertip: four, then a space, then four. They look cut on purpose, in two neat groups." },
  { id: "fd-e10", stretch: "st-stair", w: 3, req: [], line: "Wedged under a step on the Stair is a folded page. You open it. It is a sketch of the stair with every step marked *50 cm*, and the flights counted off down the margin. It looks like her sketch, measuring the steps." },
  { id: "fd-f01", stretch: "st-flight2", w: 4, req: ["b-4.2"], line: "On the second flight of the Stair, beside the little door, lies a square cut from a foam mat, just big enough to kneel on. It looks as if someone knelt here to work at the door." },
  { id: "fd-f02", stretch: "st-flight2", w: 5, req: ["b-5.0"], line: "On the jamb of the little door, the upright edge of its frame, someone has written in pencil: *open. D9* It reads like a dated note; D9 could stand for Day 9. She wrote open, and the door is shut now, as if it closed again behind her." },
  { id: "fd-f03", stretch: "st-flight2", w: 4, req: [], line: "Along the wall of the second flight, at waist height, runs a straight black line, snapped against the stone the way builders snap a chalk line. It looks as if someone was measuring here." },
  { id: "fd-f04", stretch: "st-flight2", w: 5, req: [], line: "Down on the second landing, where the Stair turns at the foot of the second flight, a small clay lamp with a spout and a handle stands in a corner. It is not the lamp on the ledge, and it is not burning, but it has been used: there is soot in its spout, and the clay is cold. Someone seems to have carried it down, used it and left it." },
  { id: "fd-f05", stretch: "st-flight2", w: 5, req: [], line: "Down the second flight of the Stair, a long, shallow groove runs through the dust of every step, as if something heavy was dragged down them." },
  { id: "fd-f06", stretch: "st-flight2", w: 5, req: ["b-5.B"],   /* names the gap (round 2, blocker 2) */ line: "On the second flight, under the gap in the wall, a heap of square-edged stone chips has been swept against the wall. They look like the chips knocked out when the gap was made, tidied into a pile." },
  { id: "fd-f07", stretch: "st-flight2", w: 4, req: [], line: "On the front of one step of the Stair is a ring, one of the small carved circles, worn so smooth that it is only a shine in the stone. It seems to have been touched, again and again, for a very long time." },
  { id: "fd-f08", stretch: "st-flight2", w: 5, req: [], line: "On one of the Stair's steps lies a leather thong, dry and curled, with a bronze bead threaded on it. It looks very old, like a cord once worn round a neck or a wrist." },
  { id: "fd-g01", stretch: "st-square", w: 6, req: [], line: "In the square gallery, in a niche at the height of a man's head, stands a clay lamp with a spout, the kind you fill with oil. Above it is a patch of soot, as if it once burned here. Beneath it, cut small by whoever cut the tally, is a line of symbols.", told: "tl-lamp" }, // side chamber
  { id: "fd-g02", stretch: "st-square", w: 6, req: [], line: "Against the square gallery's wall lies a small sandal, smaller than your boot. Its sole is studded with hobnails in rows, the small nails once hammered into soles to make them last. Above it on the wall is a short line of symbols.", told: "tl-sandal" }, // side chamber
  { id: "fd-g03", stretch: "st-square", w: 6, req: [], line: "You look closely at the square gallery's wall. The chisel marks that cover it are each a finger's width, row on row, every one angled the same way, as if the work was done steadily and to a method." },
  { id: "fd-g04", stretch: "st-square", w: 6, req: [], line: "On the square gallery's floor, an iron hobnail, one of the small nails from the sole of a shoe, has rusted away to a brown stain." },
  { id: "fd-g05", stretch: "st-square", w: 6, req: [], line: "On the square gallery's wall, at a man's height, strokes are scratched into the stone in tens, with a gap after each ten. It looks as if someone was keeping count of something, ten at a time." },
  { id: "fd-g06", stretch: "st-square", w: 6, req: [], line: "In the square gallery, a wooden peg is driven into a crack in the wall. Its end is charred black, as if something burning was once fixed to it." },
  { id: "fd-g07", stretch: "st-square", w: 6, req: [], line: "On the square gallery's floor lies a sherd, a broken piece of a big pottery jar. It has a stamped mark on it, like a maker's stamp, rubbed smooth." },
  { id: "fd-g08", stretch: "st-square", w: 6, req: [], line: "In the square gallery lies a grey whetstone, the kind of stone used to sharpen blades. It is worn hollow in the middle, as if it was used for a very long time." },
  { id: "fd-g09", stretch: "st-square", w: 6, req: [], line: "At the join in the square gallery, where the square-cut stone meets the rounded stone, a crack has been filled with a sliver of grey metal. It seems to have been poured in hot, to lock a block in place, the way lead was once used to fix iron railings into stone." },
  { id: "fd-g10", stretch: "st-square", w: 6, req: [], line: "At knee height, a single cut line runs along the square gallery's wall from one end to the other, never rising or dipping. It is like the level line a builder snaps along a wall before starting work." },
  /* ---- story weeks 8–14 (STORY_JOB §8): each true of its age and owner; texture unless a clue id is named ---- */
  { id: "fd-h01", stretch: "st-water", w: 8, req: ["b-8.A"], line: "At the Water's edge you crouch and touch the surface with one fingertip. A ripple spreads from it, small, and dies almost at once. The water is cold, like any water, and it closes over the place as if you had never touched it." },
  { id: "fd-h02", stretch: "st-water", w: 8, req: ["b-8.A"], line: "Along the Water's near shore, iron pegs are driven into the rock at even steps, a pace apart, dark with age, their heads worn flat. They look like marks for measuring something along the shore." },
  { id: "fd-h03", stretch: "st-water", w: 8, req: ["b-8.A"], line: "Sitting on the shore of the Water, you notice there is no smell of damp. The air here is as dry as in the Lamp Hall, though the lake lies right beside you." },
  { id: "fd-h04", stretch: "st-water", w: 8, req: ["b-8.A"], line: "On a flat rock at the Water's edge is a strip of masking tape, stuck down and curling at one end. On it, in marker, she has written one word: STILL?" }, // C-39a, texture
  { id: "fd-h05", stretch: "st-water", w: 8, req: ["pl-w8-channel"], line: "In the rock above the channel, small square holes are cut at knee height, one every pace. Two still hold stumps of old, dry wood. A walkway of planks may once have run along here." },
  { id: "fd-h06", stretch: "st-water", w: 8, req: ["b-8.A"], line: "Where the Stair meets the shore, the last dry step is as smooth and even as those above it, its edge sharp over the black water." },
  { id: "fd-i01", stretch: "st-blast", w: 8, req: ["b-8.C"], line: "On the narrow way below the Water, a black line of old soot runs along the ceiling, straight as a chalk line, as if a string of lamps once hung there." },
  { id: "fd-i02", stretch: "st-blast", w: 9, req: ["pl-w9-approach"], line: "On the floor of the narrow way below the Water lies a scrap of waxed paper, the kind blasting charges were wrapped in, its printing faded to a grey smudge." },
  { id: "fd-i03", stretch: "st-blast", w: 10, req: ["pl-w10-blast-floor"], line: "In the blast room, the dust on the floor is grey with old smoke, and it lies thickest along the narrow iron rails." },
  { id: "fd-i04", stretch: "st-blast", w: 10, req: ["pl-w10-blast-floor"], line: "Low on the blast room's wall, someone has written in chalk: 61 YDS, with an arrow pointing at the torn wall. It seems to mark how far the tunnel had come." },
  { id: "fd-i05", stretch: "st-blast", w: 11, req: ["pl-w10-blast-floor"], line: "By the door of the blast room, the floor is worn pale in a path to the ledge, as if someone walked there many times." },
  { id: "fd-i06", stretch: "st-blast", w: 11, req: ["pl-w10-blast-floor"], line: "On the blast room's floor, by the iron rails, lies a bootlace, knotted and snapped, gone as stiff as wire." },
  { id: "fd-j01", stretch: "st-reading", w: 9, req: ["b-9.A"], line: "In the Reading Room you run your hand along a bench top. It is cold and smooth, and its edge is rounded off like the edge of an old step." }, // C-69
  { id: "fd-j02", stretch: "st-reading", w: 9, req: ["b-9.A"], line: "In the Reading Room, one bench has a crack across its top, and the crack has been filled with the same stone, neatly, like a mended cup." },
  { id: "fd-j03", stretch: "st-reading", w: 9, req: ["b-9.A"], line: "On a bench in the Reading Room lies a sheet of squared paper, folded once. Inside, in her pencil, she has copied the three symbols over the inner door and written under them: SILENCE? A LIBRARY RULE??" }, // C-42's surface reading
  { id: "fd-j04", stretch: "st-reading", w: 10, req: ["b-9.A"], line: "In the Reading Room you look up at the highest row of tablets, far above your reach. There is no ladder and nothing to stand on anywhere in the hall." },
  { id: "fd-k01", stretch: "st-side", w: 12, req: ["b-12.C"], line: "In the side gallery, the chisel marks run in neat rows like the square gallery's, but halfway along they stop, and the rest of the wall is cut rougher, as if the work was hurried." },
  { id: "fd-k02", stretch: "st-side", w: 12, req: ["b-12.C"], line: "On the side gallery's floor lies a snapped pick handle, its wood gone grey and light." },
  { id: "fd-k03", stretch: "st-side", w: 13, req: ["b-13.1"], line: "Along the foot of the side gallery's wall runs a line of candle-grease drips, as if someone walked along here slowly with a candle, again and again." },
  { id: "fd-l01", stretch: "st-lower", w: 14, req: ["b-14.B"], line: "In the lower way you stop and listen. A thin current of cold air runs past your face, going up." },
  { id: "fd-l02", stretch: "st-lower", w: 14, req: ["b-14.B"], line: "Where the lower way bends, the rounded wall has a band of polish high above your head, as if something brushed along it, going down, for a very long time." }, // C-04a texture
  { id: "fd-g11", stretch: "st-square", w: 13, req: ["b-13.B"],   /* the deep end is reached in week 13 (D-160) */ line: "At the square gallery's deep end, among the fallen stone, lies a wooden prop, the kind miners wedge under a roof to hold it up, snapped in the middle." },
  { id: "fd-g12", stretch: "st-square", w: 13, req: ["pl-w13-lower-gallery"], line: "In the lower gallery beyond the fall, the square-cut walls are pale and clean, with none of the soot that darkens the square gallery." },
  { id: "fd-c15", stretch: "st-salt", w: 3, req: ["b-3.5"],   /* the tally bared to its end in week 3 (D-160) */ line: "You walk along the bared tally to its end. The salt below its last line is scuffed smooth at the height of a seated man's shoulder, as if someone sat against the wall here, often." },
];
