/**
 * SEALED (D-015): story content. Never shown to Dan outside the game.
 * Transcribed from docs/narrative/sealed/MVP_CONTENT.md §8.1 (the Truth column is never shipped); those files are authoritative.
 */

import type { Find } from '../../core/story-types';

export const finds: Find[] = [
  { id: "fd-a01", stretch: "st-mouth", w: 1, req: [], line: "At the foot of the ladder, you find an old rung lying half-settled in the dust, its metal bent through the middle into a shallow bow. The empty place it came from is easy to pick out. The rung immediately above that gap is newer than the rest, its surface less dulled and its edges less worn." },
  { id: "fd-a02", stretch: "st-mouth", w: 1, req: [], line: "At the ladder’s foot, you find an old chalk arrow on the shaft brick, its point aimed straight down. The chalk has sunk into the brick’s rough face and thinned at the edges, but the direction remains plain. Beside it, written with the same blunt certainty, are the characters: 36 FT." },
  { id: "fd-a03", stretch: "st-mouth", w: 1, req: [], line: "Behind one bracket, a cereal-bar wrapper has been folded again and again into a small square and pushed into the narrow space. You can see only the compacted packet and the foil turned outward, catching what little brightness reaches the metal. Its creases are sharp enough to show how tightly it was made." },
  { id: "fd-a04", stretch: "st-mouth", w: 1, req: [], line: "At the bottom of the shaft, you can see exactly where the brickwork ends. The final course of shaft brick rests directly against the stone below, with no mortar filling the join between them. Brick and stone meet edge to edge. Whatever else has been built here, the stone was here first." },
  { id: "fd-a05", stretch: "st-mouth", w: 1, req: [], line: "The passage dust is crowded with bootprints, each one the same size. You can follow them going in and coming out, heels and soles crossing until the separate tracks blur together. There are enough impressions that the centre has become a path of its own, worn into the dust by the repetition of those same boots." },
  { id: "fd-a06", stretch: "st-mouth", w: 1, req: [], line: "Blue rope is tied securely around the bottom rung, its fibres flattened where the knot grips the metal. Below the knot the rope ends abruptly: it has been cut. The loose end has been melted until the strands fuse together into a hard, rounded knob rather than fraying apart." },
  { id: "fd-b01", stretch: "st-hall", w: 1, req: [], line: "On the lip of the ledge, a single drip of glaze has run down and hardened before it could fall. You can trace its rounded edge with your eye: the colour matches the lamp exactly, yet the little bead has the bright, sealed surface of glass. It looks poured rather than carved, frozen against the stone." },
  { id: "fd-b02", stretch: "st-hall", w: 3, req: ["b-3.A"], line: "You examine the cups one by one and find no wick in any of them. There is nowhere for a wick to hide: the interiors are open to view. In every cup, the flame stands directly on the mark itself, rising from that point without thread, fibre or other visible thing between mark and fire." },
  { id: "fd-b03", stretch: "st-hall", w: 6, req: ["b-6.1"], line: "Beneath the carved lamp, the stone carries something much fainter than the finished cutting. A pencil grid of small squares sits under it, so pale that parts nearly disappear into the surface. You can still follow enough of the ruled pattern to see the earlier planning beneath the carving, square by square." },
  { id: "fd-b04", stretch: "st-hall", w: 1, req: [], line: "Above the ledge, old soot spreads across the ceiling in a broad fan. Its darkest part lies directly over the ledge, where the deposit is thickest, and from there the blackening thins outward. The stone beyond gradually returns to its own colour, making the soot’s shape readable even where its outer edge becomes faint." },
  { id: "fd-b05", stretch: "st-hall", w: 1, req: [], line: "Five candle stubs stand in a neat row on the floor beside the ledge. Each has burned down almost to the stone, leaving only a short, thick remnant of wax. Seen together, the five low shapes barely rise from the floor, their used-down tops uneven where the candles ended." },
  { id: "fd-b06", stretch: "st-hall", w: 3, req: ["b-3.A"], line: "Near the corner, one cup is broken at the lip. The missing edge has been rebuilt with a paste made from the same stone, its repaired surface slightly different from the original curve. Inside, however, the flame’s mark remains whole. The break reaches the vessel; it does not interrupt that mark." },
  { id: "fd-b07", stretch: "st-hall", w: 1, req: [], line: "At the foot of the great door, the dust changes. It gathers there in a line finer than the dust anywhere else, sifted into a narrow pale edge along the bottom of the door. The line has the delicate, even look of dust repeatedly disturbed by air passing beneath the door for a long time.", until: "b-7.C" },
  { id: "fd-b08", stretch: "st-hall", w: 1, req: [], line: "In a crack beside the ledge lies the burnt end of a wick, blackened and shortened to a small scrap. Immediately next to it, cut into the stone at a much smaller scale, is a line in the tally’s hand. You can take in wick and cutting together without shifting your gaze far from the crack.", told: "tl-wick" }, // side chamber
  { id: "fd-b09", stretch: "st-hall", w: 1, req: [], line: "Under the ledge lies a thin flake of glaze. Its surface carries the same kind of finish as the lamp, but its colour is one shade darker. The broken edge shows how little substance there is to it; lying flat against the floor, it looks almost like a chip of coloured glass." },
  { id: "fd-b10", stretch: "st-hall", w: 1, req: [], line: "A chalk arrow on the hall floor points across towards the side chamber. The mark is broad enough to follow at once, its point aimed cleanly at that opening. Beside the arrow, someone has written a single word in block capitals, each letter separate and unornamented: CAMP." },
  { id: "fd-b11", stretch: "st-hall", w: 3, req: ["b-3.A"], line: "In the lamplight, more rings become visible above you. They are cut into the ceiling itself, continuing where the height makes them difficult to examine. You judge their position against the walls and the open floor beneath. Some lie beyond any place a ladder could have stood to reach them from below." },
  { id: "fd-b12", stretch: "st-hall", w: 1, req: [], line: "You lean towards the lamp and breathe across the flame. Your breath reaches the space above the cup, close enough that an ordinary flame would show it at once. This one does not bend. Its outline remains upright over the mark, unchanged by the air you send across it." },
  { id: "fd-c01", stretch: "st-hall", w: 1, req: [], line: "In the bottom of one trough at the corner lies a dry brown leaf. Its edges have begun to crumble into small brittle points, while the centre still holds the flattened shape of the leaf. You recognise the ordinary sort: the kind that grows on a hedge, resting here against the hard trough floor." },
  { id: "fd-c02", stretch: "st-salt", w: 1, req: [], line: "At the gallery’s first turn, a piece of wool has been knotted round a knob of salt. The fibres have greyed, and the knot sits tight against the pale mineral. Beside it, a short line has been cut into the salt, close enough that the wool and the incision occupy the same small patch of wall.", told: "tl-wool" }, // side chamber
  { id: "fd-c03", stretch: "st-salt", w: 2, req: [], line: "A crack in the salt holds a small cake of salt, shaped separately enough to stand out from the surrounding wall. Pressed into its surface is a thumbprint, the pad and curve left as a shallow impression. Directly underneath, a line in the tally’s hand has been cut into the salt.", told: "tl-salt-cake" }, // side chamber
  { id: "fd-c04", stretch: "st-salt", w: 1, req: [], line: "You find a loose chip of salt marked with rows of scratches. The scratches have been counted in fives, their grouping repeated across the small surface rather than scattered at random. Beside the chip is another cut line, recognisable as the tally’s hand, set close to the counted marks.", told: "tl-count" }, // side chamber
  { id: "fd-c05", stretch: "st-salt", w: 2, req: [], line: "A carrying pole lies on the salt, its length of wood worn smooth by use. Two long grooves run where the surface has been rubbed down most deeply, parallel hollows polished into the grain. Beside the pole, a few marks are cut into the salt, small against the longer shape of the timber.", told: "tl-yoke" }, // side chamber
  { id: "fd-c06", stretch: "st-salt", w: 1, req: [], line: "A bronze awl has been driven point-first into a crack in the salt. Age has turned much of the metal green, especially around the exposed body, while the point itself disappears into the narrow split. The awl projects from the wall at the angle at which it was forced into the crack." },
  { id: "fd-c07", stretch: "st-salt", w: 1, req: [], line: "On the floor you find a narrow strip of hide tied into a loop. Time and dryness have taken all softness from it: the hide has stiffened until it is hard as wood. The knot and the curve of the loop remain fixed in place, held in the shape the strip dried into." },
  { id: "fd-c08", stretch: "st-salt", w: 1, req: [], line: "In the crack with her sheets lies a pencil reduced almost to a stub. It has been sharpened and used until the whole thing is only the length of your thumb. Against the larger sheets, the pencil seems particularly small, its worn body showing how little wood remains to hold." },
  { id: "fd-c09", stretch: "st-salt", w: 1, req: [], line: "In the lowest cuts of the tally, small salt crystals have grown inside the incisions. They collect along the cut edges and in the deepest parts, bright and granular against the older surface. The effect is like frost caught in a crack, except that each pale grain belongs to the salt wall itself." },
  { id: "fd-c10", stretch: "st-salt", w: 1, req: [], line: "By the split, a sandal-print is set hard into the salt floor. The pressure has preserved more than the outline of the foot: even the straps have left their marks, crossing the impression in distinct bands. You can read the whole shape at once, sole and straps fixed together in the hardened surface." },
  { id: "fd-c11", stretch: "st-salt", w: 1, req: [], line: "Two stones have been packed into the split, and between them someone has pressed a plug of wool. Salt has worked deep into the fibres until the wool looks crusted from within rather than merely dusted on the outside. The plug fills the narrow gap left between the two stones." },
  { id: "fd-c12", stretch: "st-salt", w: 2, req: ["b-2.A"], line: "Above the tally, the lone ring resolves into a single unbroken cut. You follow the groove around its full circle, searching the line itself rather than the surrounding salt. There is no visible place where the tool first entered or finally left the surface: no beginning and no end you can identify." },
  { id: "fd-c13", stretch: "st-salt", w: 1, req: ["seal-1-2"], line: "The floor of the pick niche is crossed by a repeated pattern of scoring. Each mark belongs to the same simple action: a pick laid down, lifted, then laid down again. The scores overlap enough to show repetition, yet the long, narrow contacts remain distinct across the place where the tool repeatedly rested." },
  { id: "fd-c14", stretch: "st-salt", w: 2, req: ["b-2.A"], line: "On the back of her Day 4 sheet, she has drawn the two troughs at the corner and measured the space separating them. The sketch is practical rather than decorative, with the gap given attention alongside the troughs themselves. Beneath it she has written exactly: *stride?? 1.4 m*" },
  { id: "fd-d01", stretch: "st-camp", w: 1, req: [], line: "A hair elastic is wound several times around the notebook’s pencil. The dark loop grips the pencil tightly, each turn lying over the last and making a small band around the wood. It is an ordinary, flexible thing among the harder objects in the chamber, kept together with the pencil rather than lying loose." },
  { id: "fd-d02", stretch: "st-camp", w: 1, req: [], line: "A page torn from an old railway timetable lies among the papers, printed on thin paper that flexes with the slightest handling. One line of the timetable has been ringed in pencil. At the torn edge, the station name that would identify that line is missing, taken away with the absent part of the page." },
  { id: "fd-d03", stretch: "st-camp", w: 1, req: [], line: "A used tea bag has dried flat against the lid of a mug. The paper has stiffened and gone papery at the edges, pressed so closely to the lid that its shape is held almost flush against the surface. What was once soft and wet is now a thin, rigid patch over the mug’s top." },
  { id: "fd-d04", stretch: "st-camp", w: 2, req: [], line: "A photocopy shows brown-ink handwriting reproduced in muted tones. At the top, one word remains legible: *Log.* Below that heading, the rest of the writing has been greyed out by the copier until the page carries only indistinct blocks and traces instead of readable words." },
  { id: "fd-d05", stretch: "st-camp", w: 1, req: [], line: "Beside a battery lies a roll of black tape, its wound layers making a compact dark cylinder on the shelf. The battery has been stripped of its label; only the bare casing remains where printed information should be. Tape and unlabelled battery sit together without anything else on them to identify a use." },
  { id: "fd-d06", stretch: "st-camp", w: 1, req: [], line: "The cup of a thermos stands upside down on the shelf, its rim resting flat against the surface. When you look into the part still visible, you can see a brown ring dried inside it. The stain circles the interior evenly enough to mark the level of whatever once sat there." },
  { id: "fd-d07", stretch: "st-camp", w: 1, req: [], line: "A newspaper crossword has been torn in half. Some of the surviving squares are filled in with pencil while others remain blank, the incomplete grid cut off by the tear. The piece that would carry the newspaper’s date is gone, leaving the puzzle partly solved but without its day." },
  { id: "fd-d08", stretch: "st-camp", w: 1, req: [], line: "A strip of masking tape has been stuck directly onto the cot frame. Across the pale tape, in marker, are the words DAY 1. The letters sit on the narrow strip rather than the frame itself, making the label stand apart from the darker material of the cot." },
  { id: "fd-d09", stretch: "st-camp", w: 1, req: [], line: "You open the matchbox far enough to see what remains inside. There are three matches. They lie together in the small cardboard tray, each full length still intact, leaving most of the box empty around them. Whatever number the box once held, the count now is exact and simple: three." },
  { id: "fd-d10", stretch: "st-camp", w: 6, req: ["b-6.1"], line: "Above the cot, twelve pencil strokes have been tallied on the surface. They are grouped in fives, so the spacing breaks the twelve into deliberate counts rather than one continuous row. Beneath the last stroke, a separate line has been drawn, straight enough to read as distinct from the tally marks above it." },
  { id: "fd-d11", stretch: "st-camp", w: 1, req: [], line: "A paperback thriller lies face down with its spine forced wide by the way it has been left. The covers and pages splay outward against the surface, holding the book open at page 211. That number is visible at the exposed spread, fixing the abandoned place exactly despite the closed face of the cover." },
  { id: "fd-d12", stretch: "st-camp", w: 1, req: [], line: "Beside the door, a fleece hat hangs from a nail. The soft fabric droops from the single point, its shape folded by its own weight rather than laid flat. It is close enough to the doorway to look immediately practical: an ordinary piece of clothing suspended against the hard wall." },
  { id: "fd-e01", stretch: "st-stair", w: 3, req: [], line: "One step has lost a piece from its edge, exposing stone darker than the weathered outer surface. Through that darker interior runs a thread of material that looks like glass. The line catches differently from the stone around it, narrow and hard within the chipped face rather than spread across the surface." },
  { id: "fd-e02", stretch: "st-stair", w: 3, req: [], line: "At the landing’s edge lies a wax seal no larger than a coin. Its stamped face has been worn so flat that the impression is no longer distinct, leaving only the small disc and its softened surface. Beside it, the tally’s hand has cut a line into the landing stone.", told: "tl-seal" }, // side chamber
  { id: "fd-e03", stretch: "st-stair", w: 3, req: [], line: "Down the wall of the top flight runs a long polished band at the height of a long hand. The surrounding stone remains rougher, making the smoothed strip easy to follow along the stairs. It has the continuous sheen of repeated contact, as though the same hand passed there again and again." },
  { id: "fd-e04", stretch: "st-stair", w: 3, req: [], line: "At the first turn, a bronze nail has been driven into a crack in the stone. Its head is square, giving the small piece of metal a blunt geometry against the irregular split around it. The shaft disappears into the crack, while the square head remains exposed at the surface." },
  { id: "fd-e05", stretch: "st-stair", w: 3, req: [], line: "A small pencil tick crosses the rail. Beside it, the pencil continues into a short note, written plainly enough to read in full: *1.3 m. Rail for somebody tall.* You can compare the tick directly with the rail’s height; the measurement and the observation occupy the same narrow stretch." },
  { id: "fd-e06", stretch: "st-stair", w: 3, req: [], line: "On the top step, a thin flake of candle wax rests beside the print of a trainer’s sole. The wax has cooled into an irregular pale chip, while the tread beside it records the modern shoe in a broader pattern. The two traces touch the same step without overlapping." },
  { id: "fd-e07", stretch: "st-stair", w: 3, req: [], line: "At the head of the top flight, one ring is cut into the wall apart from the others. Its isolation is obvious before its depth is: there is clear stone around it. The groove itself is noticeably deeper than the other rings, holding a stronger dark line within the cut." },
  { id: "fd-e08", stretch: "st-stair", w: 4, req: [], line: "A groove has been worn around the edge of one step by a rope. The channel follows the corner where repeated pressure would bite hardest into the stone. Caught in that worn groove is a single blue thread, fine enough to sit inside it while still keeping its colour." },
  { id: "fd-e09", stretch: "st-stair", w: 3, req: [], line: "At head height on the wall of the top flight are eight small hollows, each about the size of a fingertip. Their arrangement is exact enough to count without touching them: four hollows, then a space, then four more. The gap divides the eight into two equal groups." },
  { id: "fd-e10", stretch: "st-stair", w: 3, req: [], line: "A folded page is wedged beneath one of the steps. When opened enough to read, it shows a drawing of the Stair, every step labelled *50 cm*. Under the drawing is a second note in the same practical hand: *built for legs longer than mine*. The measurements repeat all the way down the drawn flight." },
  { id: "fd-f01", stretch: "st-flight2", w: 4, req: [], line: "Beside the little door lies a square cut from a foam mat. Its edges are plainly trimmed rather than torn, making a pad just large enough to kneel on. Against the stone floor, the foam keeps its manufactured texture and slight give, positioned exactly where someone working at the low door would need their knees." },
  { id: "fd-f02", stretch: "st-flight2", w: 5, req: ["b-5.0"], line: "On the jamb of the little door, pencil has been used rather than a cut mark. The writing is small and close to the edge, but still legible. It reads exactly: *open. D9* The soft graphite sits on the jamb’s surface, separate from the harder marks elsewhere around the door." },
  { id: "fd-f03", stretch: "st-flight2", w: 4, req: [], line: "Along the wall of the second flight runs a straight black line at waist height. It is narrow and sharply placed, with the abrupt, even appearance of a chalk line snapped against the stone. The line holds the same level across the wall rather than following the rise of the steps." },
  { id: "fd-f04", stretch: "st-flight2", w: 5, req: [], line: "In the corner of the second landing stands a small clay lamp with a spout and a handle. Soot darkens the inside of the spout, concentrated where a flame would have been nearest the opening. You touch the lamp carefully enough to judge its temperature. The clay is cold." },
  { id: "fd-f05", stretch: "st-flight2", w: 5, req: [], line: "Across the dust on every step of the second flight runs the same long, shallow groove. It cuts through the loose dust rather than the stone beneath, continuing step after step down the flight. The breadth and persistence of the mark make it look as though something heavy was dragged down." },
  { id: "fd-f06", stretch: "st-flight2", w: 5, req: [], line: "Beneath the gap, square-edged chips of stone have been swept into a heap against the wall. Their fresh-looking angles distinguish them from loose dust and rounded debris. The pieces collect tightly at the base of the wall, gathered from the floor into one deliberate pile below the opening." },
  { id: "fd-f07", stretch: "st-flight2", w: 4, req: [], line: "One riser carries a ring cut into its face, but most of the incision has been worn away. What remains is less a groove than a shine in the stone, a circular trace polished where the cut once had depth. You can still follow enough of that sheen to recognise the ring." },
  { id: "fd-f08", stretch: "st-flight2", w: 5, req: [], line: "A dry leather thong lies curled on the floor. Threaded onto it is a bronze bead, the metal resting within the stiff curve of the leather rather than loose beside it. The thong has dried into its present shape, while the bead remains free enough on the strip to show the threading clearly." },
  { id: "fd-g01", stretch: "st-square", w: 6, req: [], line: "In a niche at about head height, beneath a patch of soot, stands a spouted clay lamp. The soot occupies the stone above while the lamp fits the recess below it. Directly underneath the niche, a small line has been cut in the tally’s hand, modest in scale beside the lamp and its darkened patch.", told: "tl-lamp" }, // side chamber
  { id: "fd-g02", stretch: "st-square", w: 6, req: [], line: "Against the square wall lies a small sandal fitted with hobnails. Its sole is short, and the metal studs break the surface in a regular roughness where they remain. Above the sandal, a line of marks has been made on the wall, high enough that you take in footwear and marks as separate details.", told: "tl-sandal" }, // side chamber
  { id: "fd-g03", stretch: "st-square", w: 6, req: [], line: "Seen from close enough to resolve the tooling, the square wall is covered with chisel cuts. Each cut is about a finger’s width long. They run row after row across the stone, and every small incision leans at the same angle, turning the whole worked face into a repeated pattern of strokes." },
  { id: "fd-g04", stretch: "st-square", w: 6, req: [], line: "An iron hobnail lies where it fell on the floor. Rust has spread from the metal into the surface beneath it, leaving a brown stain that fixes the nail’s position even more clearly than its small shape does. The stain is concentrated around the iron rather than scattered across the stone." },
  { id: "fd-g05", stretch: "st-square", w: 6, req: [], line: "At roughly a man’s height on the square wall, strokes have been scratched into the stone in counted groups. You can follow them by tens: ten strokes, then a gap, then the next ten. The repeated spaces divide the long series cleanly, turning what might first look like scoring into a deliberate count." },
  { id: "fd-g06", stretch: "st-square", w: 6, req: [], line: "A wooden peg has been driven into a crack in the stone. The wood is still recognisable along the exposed shaft, but the outer end is charred black. The burning stops before the peg enters the crack, leaving the darkened tip outside and the rest wedged firmly into the split." },
  { id: "fd-g07", stretch: "st-square", w: 6, req: [], line: "A broken sherd from a large jar lies with its curved surface exposed. Pressed into it is a stamped mark, but handling or abrasion has rubbed the impression almost smooth. Enough remains to show that a stamp was there, while the raised and recessed detail has been reduced nearly to the level of the pottery." },
  { id: "fd-g08", stretch: "st-square", w: 6, req: [], line: "A grey whetstone has been used until its middle is no longer flat. Repeated sharpening has worn a hollow through the centre, leaving the ends thicker than the part between them. The dip is broad and smooth, shaped by use rather than by a single break or chip." },
  { id: "fd-g09", stretch: "st-square", w: 6, req: [], line: "Where the square stone meets the round, the join is not simply a dry seam. Grey metal has been poured into a crack between the two forms, filling the irregular space and hardening there. It keys one block to the other, a metallic bridge set directly across the meeting of square and round stone." },
  { id: "fd-g10", stretch: "st-square", w: 6, req: [], line: "A cut line runs the full length of the gallery at knee height. It is dead level, refusing the small variations of the floor and the individual blocks around it. Once you align your eye with it, the incision carries straight along the wall as a single horizontal measure through the square-stone passage." },
];
