/**
 * SEALED (D-015): story content. Never shown to Dan outside the game.
 * Transcribed from docs/narrative/sealed/MVP_CONTENT.md §8.1 (the Truth column is never shipped); those files are authoritative.
 */

import type { Find } from '../../core/story-types';

export const finds: Find[] = [
  { id: "fd-a01", stretch: "st-mouth", w: 1, req: [], line: "At the bottom of the shaft, where the ladder meets the floor, an old rung lies in the dust, bent in the middle like a bow. You look up the ladder. Just above, one rung is newer than all the others. It looks as if the old one bent, and someone fitted a new one in its place." },
  { id: "fd-a02", stretch: "st-mouth", w: 1, req: [], line: "On the brick wall at the foot of the ladder, someone has drawn an arrow in old chalk, pointing straight down at the floor. Beside it is written: 36 FT. That seems to be the depth of the shaft in feet, the same eleven metres the ladder runs." },
  { id: "fd-a03", stretch: "st-mouth", w: 1, req: [], line: "Behind a metal bracket on the brick wall at the ladder's foot, you spot a cereal-bar wrapper. It has been folded small and pushed in with the foil side out, tucked away rather than dropped. It looks fairly recent. You leave it where it is." },
  { id: "fd-a04", stretch: "st-mouth", w: 1, req: [], line: "At the bottom of the shaft, you look at where the brick lining stops. The last row of bricks sits straight on the stone below, with no mortar between them. The stone was here first: the brick shaft seems to have been built down onto it." },
  { id: "fd-a05", stretch: "st-mouth", w: 1, req: [], line: "From the ladder you walk a few paces into the passage, the smooth tunnel leading into the hill. The dust on its floor is full of bootprints, all the same size, going in and coming out. There are so many that they have worn a path, like a track across a lawn. It looks as if one person walked here many, many times." },
  { id: "fd-a06", stretch: "st-mouth", w: 1, req: [], line: "A length of blue rope, the modern kind used for climbing or boating, is tied to the bottom rung of the ladder. You pick up its loose end. The rope has been cut, and the cut end melted into a hard knob, as if someone sealed it on purpose to stop it fraying." },
  { id: "fd-b01", stretch: "st-hall", w: 1, req: [], line: "At the near end of the Lamp Hall, you look at the front edge of the ledge where the lamp stands. Something has run over the lip and set there: a drip of glaze, the glassy coating on pottery, the same colour as the lamp. You touch it with a fingertip. It is as hard as glass. It looks as if it ran there while still wet and hardened where it stopped; how it came to be there, you cannot tell." },
  { id: "fd-b02", stretch: "st-hall", w: 3, req: ["b-3.A"], line: "You examine the cups one by one and find no wick in any of them. There is nowhere for a wick to hide: the interiors are open to view. In every cup, the flame stands directly on the mark itself, rising from that point without thread, fibre or other visible thing between mark and fire." },
  { id: "fd-b03", stretch: "st-hall", w: 6, req: ["b-6.1"], line: "Beneath the carved lamp, the stone carries something much fainter than the finished cutting. A pencil grid of small squares sits under it, so pale that parts nearly disappear into the surface. You can still follow enough of the ruled pattern to see the earlier planning beneath the carving, square by square." },
  { id: "fd-b04", stretch: "st-hall", w: 1, req: [], line: "Standing by the ledge, you look up at the ceiling. Old soot is spread across the stone above it in the shape of a fan, thick and black at its point and fading outwards. Something seems to have burned here for a very long time." },
  { id: "fd-b05", stretch: "st-hall", w: 1, req: [], line: "On the floor beside the ledge, five candle stubs stand in a row. Each has burned right down to the stone. They look like the leftovers of someone else's light, brought down here and used up. You leave them in their row." },
  { id: "fd-b06", stretch: "st-hall", w: 3, req: ["b-3.A"], line: "Near the corner, one cup is broken at the lip. The missing edge has been rebuilt with a paste made from the same stone, its repaired surface slightly different from the original curve. Inside, however, the flame’s mark remains whole. The break reaches the vessel; it does not interrupt that mark." },
  { id: "fd-b07", stretch: "st-hall", w: 1, req: [], line: "You walk to the far end of the Lamp Hall, beyond the reach of the light, and stop at the foot of the great door, the huge door that fills most of the end wall. Along the floor at its base the dust lies in a line, finer than anywhere else, as if air has moved under the door for a long time.", until: "b-7.C" },
  { id: "fd-b08", stretch: "st-hall", w: 1, req: [], line: "Beside the ledge, you peer into a crack in the stone. The burnt end of a wick lies inside. Next to it, a short line of tiny symbols is cut into the stone. The cutting looks like the same hand as the tally, the long carved line in the Salt Gallery that seems to be some kind of record.", told: "tl-wick" }, // side chamber
  { id: "fd-b09", stretch: "st-hall", w: 1, req: [], line: "You crouch and look under the ledge. A thin flake of glaze lies on the floor there, like a chip off a glazed pot. It is one shade darker than the lamp above. You do not disturb it." },
  { id: "fd-b10", stretch: "st-hall", w: 1, req: [], line: "On the floor of the Lamp Hall, someone has drawn an arrow in chalk. It points to a round-topped doorway in the side wall, the way into a small side chamber. Beside the arrow, also in chalk, is the word CAMP. It looks as if someone has been living in there." },
  { id: "fd-b11", stretch: "st-hall", w: 3, req: ["b-3.A"], line: "In the lamplight, more rings become visible above you. They are cut into the ceiling itself, continuing where the height makes them difficult to examine. You judge their position against the walls and the open floor beneath. Some lie beyond any place a ladder could have stood to reach them from below." },
  { id: "fd-b12", stretch: "st-hall", w: 1, req: [], line: "At the ledge, you lean close to the lamp, the small clay oil lamp that stands there burning, and breathe gently on its flame. An ordinary flame would flicker. This one does not bend at all. You try again, harder. It stays perfectly upright." },
  { id: "fd-c01", stretch: "st-hall", w: 1, req: [], line: "At the far end of the Lamp Hall, by the great door, the hall turns a corner. Two long troughs are worn into the floor there, smooth inside like basins. In the bottom of one lies a dry leaf, brown and crumbling, the kind that grows on a hedge. It looks as if it found its way in from outside somehow." },
  { id: "fd-c02", stretch: "st-salt", w: 1, req: [], line: "You walk along the Salt Gallery, the long, low passage beside the wall of rock salt, to where it first turns. There, a knot of wool gone grey with age is tied round a knob of salt on the wall. Beside it, a short line of symbols is cut into the salt. Both look very old.", told: "tl-wool" }, // side chamber
  { id: "fd-c03", stretch: "st-salt", w: 2, req: [], line: "A crack in the salt holds a small cake of salt, shaped separately enough to stand out from the surrounding wall. Pressed into its surface is a thumbprint, the pad and curve left as a shallow impression. Directly underneath, a line in the tally’s hand has been cut into the salt.", told: "tl-salt-cake" }, // side chamber
  { id: "fd-c04", stretch: "st-salt", w: 1, req: [], line: "In the Salt Gallery, a small chip of salt lies loose at the foot of the wall. You bend to look at it without picking it up. It is scratched with short strokes in rows of five, like the marks people make in fives when keeping score. Beside it, a short line of symbols is cut in the same hand as the tally.", told: "tl-count" }, // side chamber
  { id: "fd-c05", stretch: "st-salt", w: 2, req: [], line: "A carrying pole lies on the salt, its length of wood worn smooth by use. Two long grooves run where the surface has been rubbed down most deeply, parallel hollows polished into the grain. Beside the pole, a few marks are cut into the salt, small against the longer shape of the timber.", told: "tl-yoke" }, // side chamber
  { id: "fd-c06", stretch: "st-salt", w: 1, req: [], line: "Further along the Salt Gallery, a bronze awl, a small pointed tool for making holes, is stuck point first in a crack in the salt. The bronze has gone green. It looks very old, and it has been left exactly where it was pushed in." },
  { id: "fd-c07", stretch: "st-salt", w: 1, req: [], line: "On the floor of the Salt Gallery lies a strip of animal hide, knotted into a loop like a leather tie. You pick it up. It has dried as hard as wood and will not bend. You set it back down where it lay." },
  { id: "fd-c08", stretch: "st-salt", w: 1, req: [], line: "Beside the tally in the Salt Gallery is a narrow crack where loose sheets of paper are tucked, someone's working notes. With them lies a pencil, sharpened and used until it is no longer than your thumb. Whoever wrote the notes seems to have written a great deal." },
  { id: "fd-c09", stretch: "st-salt", w: 1, req: [], line: "You bend close to the tally, the long line of carved symbols along the Salt Gallery wall that seems to be some kind of record. In its lowest cuts, salt has grown into small crystals, like frost in a crack. Those cuts look as if they have been there a long time." },
  { id: "fd-c10", stretch: "st-salt", w: 1, req: [], line: "You stop by the split, the crack down the salt wall that looks as if it was blocked up from the other side. In the salt floor beside it is the print of a sandal, set hard, with the lines of its straps still showing. It seems to have been made by someone in sandals, not boots." },
  { id: "fd-c11", stretch: "st-salt", w: 1, req: [], line: "You look closely at the split in the salt wall, where stones and salt are packed tight into the crack. Between two of the stones is a plug of wool with salt worked into it, pushed in like stuffing to fill the last gap. You leave it in place." },
  { id: "fd-c12", stretch: "st-salt", w: 2, req: ["b-2.A"], line: "Above the tally, the lone ring resolves into a single unbroken cut. You follow the groove around its full circle, searching the line itself rather than the surrounding salt. There is no visible place where the tool first entered or finally left the surface: no beginning and no end you can identify." },
  { id: "fd-c13", stretch: "st-salt", w: 1, req: ["seal-1-2"], line: "Now that the pick niche stands open, you crouch and look inside, past the bronze salt-pick. The niche's floor is scored with fine scratches where a pick has been laid down and taken up again, many times. It looks as if the pick was kept here, and used, for a very long time." },
  { id: "fd-c14", stretch: "st-salt", w: 2, req: ["b-2.A"], line: "On the back of her Day 4 sheet, she has drawn the two troughs at the corner and measured the space separating them. The sketch is practical rather than decorative, with the gap given attention alongside the troughs themselves. Beneath it she has written exactly: *stride?? 1.4 m*" },
  { id: "fd-d01", stretch: "st-camp", w: 1, req: [], line: "In the Survey Cut, the small side chamber where someone camped, you look at the notebook on the cot. The pencil tucked into it has a hair elastic wound round it, as if to keep it from slipping away." },
  { id: "fd-d02", stretch: "st-camp", w: 1, req: [], line: "Among the papers in the Survey Cut is a page from an old railway timetable, printed on thin paper. One line is ringed in pencil, as if it mattered to someone. The station's name has been torn away, so you cannot tell where it was." },
  { id: "fd-d03", stretch: "st-camp", w: 1, req: [], line: "In the camp in the Survey Cut, a mug stands with a lid on it. On the lid lies a used tea bag, dried out until it is thin and stiff as paper. It seems to have been sitting there for some time." },
  { id: "fd-d04", stretch: "st-camp", w: 2, req: [], line: "A photocopy shows brown-ink handwriting reproduced in muted tones. At the top, one word remains legible: *Log.* Below that heading, the rest of the writing has been greyed out by the copier until the page carries only indistinct blocks and traces instead of readable words." },
  { id: "fd-d05", stretch: "st-camp", w: 1, req: [], line: "In the Survey Cut you find a roll of black tape, like electrician's tape, and beside it a battery with its label peeled off. They look like the odds and ends of someone's kit." },
  { id: "fd-d06", stretch: "st-camp", w: 1, req: [], line: "On the shelf in the Survey Cut, the cup from a thermos flask stands upside down. You turn it over. A brown ring has dried inside, as if a drink was left standing in it before it was put away." },
  { id: "fd-d07", stretch: "st-camp", w: 1, req: [], line: "Lying in the camp is a crossword torn out of a newspaper. It is half filled in with pencil, as if someone stopped partway through. The date has been torn off, so there is no telling which day's paper it came from." },
  { id: "fd-d08", stretch: "st-camp", w: 1, req: [], line: "On the frame of the cot in the Survey Cut, a strip of masking tape is stuck down, with DAY 1 written on it in marker. It looks like the first day of a stay, marked the way you might mark a calendar." },
  { id: "fd-d09", stretch: "st-camp", w: 1, req: [], line: "In the Survey Cut you find a box of matches and slide it open. Only three matches are left inside." },
  { id: "fd-d10", stretch: "st-camp", w: 6, req: ["b-6.1"], line: "Above the cot, twelve pencil strokes have been tallied on the surface. They are grouped in fives, so the spacing breaks the twelve into deliberate counts rather than one continuous row. Beneath the last stroke, a separate line has been drawn, straight enough to read as distinct from the tally marks above it." },
  { id: "fd-d11", stretch: "st-camp", w: 1, req: [], line: "In the camp, a paperback thriller lies face down, open at page 211, as if its reader put it down meaning to come back to it. You leave it as it is." },
  { id: "fd-d12", stretch: "st-camp", w: 1, req: [], line: "By the doorway of the Survey Cut, a fleece hat hangs on a nail, ready to be grabbed on the way out." },
  { id: "fd-e01", stretch: "st-stair", w: 3, req: [], line: "One step has lost a piece from its edge, exposing stone darker than the weathered outer surface. Through that darker interior runs a thread of material that looks like glass. The line catches differently from the stone around it, narrow and hard within the chipped face rather than spread across the surface." },
  { id: "fd-e02", stretch: "st-stair", w: 3, req: [], line: "At the landing’s edge lies a wax seal no larger than a coin. Its stamped face has been worn so flat that the impression is no longer distinct, leaving only the small disc and its softened surface. Beside it, the tally’s hand has cut a line into the landing stone.", told: "tl-seal" }, // side chamber
  { id: "fd-e03", stretch: "st-stair", w: 3, req: [], line: "Down the wall of the top flight runs a long polished band at the height of a long hand. The surrounding stone remains rougher, making the smoothed strip easy to follow along the stairs. It has the continuous sheen of repeated contact, as though the same hand passed there again and again." },
  { id: "fd-e04", stretch: "st-stair", w: 3, req: [], line: "At the first turn, a bronze nail has been driven into a crack in the stone. Its head is square, giving the small piece of metal a blunt geometry against the irregular split around it. The shaft disappears into the crack, while the square head remains exposed at the surface." },
  { id: "fd-e05", stretch: "st-stair", w: 3, req: [], line: "A small pencil tick crosses the rail. Beside it, the pencil continues into a short note, written plainly enough to read in full: *1.3 m. Rail for somebody tall.* You can compare the tick directly with the rail’s height; the measurement and the observation occupy the same narrow stretch." },
  { id: "fd-e06", stretch: "st-stair", w: 3, req: [], line: "On the top step, a thin flake of candle wax rests beside the print of a trainer’s sole. The wax has cooled into an irregular pale chip, while the tread beside it records the modern shoe in a broader pattern. The two traces touch the same step without overlapping." },
  { id: "fd-e07", stretch: "st-stair", w: 3, req: [], line: "At the head of the top flight, one ring is cut into the wall apart from the others. Its isolation is obvious before its depth is: there is clear stone around it. The groove itself is noticeably deeper than the other rings, holding a stronger dark line within the cut." },
  { id: "fd-e08", stretch: "st-stair", w: 4, req: [], line: "A groove has been worn around the edge of one step by a rope. The channel follows the corner where repeated pressure would bite hardest into the stone. Caught in that worn groove is a single blue thread, fine enough to sit inside it while still keeping its colour." },
  { id: "fd-e09", stretch: "st-stair", w: 3, req: [], line: "At head height on the wall of the top flight are eight small hollows, each about the size of a fingertip. Their arrangement is exact enough to count without touching them: four hollows, then a space, then four more. The gap divides the eight into two equal groups." },
  { id: "fd-e10", stretch: "st-stair", w: 3, req: [], line: "A folded page is wedged beneath one of the steps. When opened enough to read, it shows a drawing of the Stair, every step labelled *50 cm*. Under the drawing is a second note in the same practical hand: *built for legs longer than mine*. The measurements repeat all the way down the drawn flight." },
  { id: "fd-f01", stretch: "st-flight2", w: 4, req: [], line: "Beside the little door lies a square cut from a foam mat. Its edges are plainly trimmed rather than torn, making a pad just large enough to kneel on. Against the stone floor, the foam keeps its manufactured texture and slight give, positioned exactly where someone working at the low door would need their knees." },
  { id: "fd-f02", stretch: "st-flight2", w: 5, req: ["b-5.0"], line: "On the jamb of the little door, pencil has been used rather than a cut mark. The writing is small and close to the edge, but still legible. It reads exactly: *open. D9* The soft graphite sits on the jamb’s surface, separate from the harder marks elsewhere around the door." },
  { id: "fd-f03", stretch: "st-flight2", w: 4, req: [], line: "Along the wall of the second flight runs a straight black line at waist height. It is narrow and sharply placed, with the abrupt, even appearance of a chalk line snapped against the stone. The line holds the same level across the wall rather than following the rise of the steps." },
  { id: "fd-f04", stretch: "st-flight2", w: 5, req: [], line: "In the corner of the second landing stands a small clay lamp with a spout and a handle. Soot darkens the inside of the spout, concentrated where a flame would have been nearest the opening. You touch the lamp carefully enough to judge its temperature. The clay is cold." },
  { id: "fd-f05", stretch: "st-flight2", w: 5, req: [], line: "Across the dust on every step of the second flight runs the same long, shallow groove. It cuts through the loose dust rather than the stone beneath, continuing step after step down the flight. The breadth and persistence of the mark make it look as though something heavy was dragged down." },
  { id: "fd-f06", stretch: "st-flight2", w: 5, req: [], line: "Beneath the gap, square-edged chips of stone have been swept into a heap against the wall. Their fresh-looking angles distinguish them from loose dust and rounded debris. The pieces collect tightly at the base of the wall, gathered from the floor into one deliberate pile below the opening." },
  { id: "fd-f07", stretch: "st-flight2", w: 4, req: [], line: "One riser carries a ring cut into its face, but most of the incision has been worn away. What remains is less a groove than a shine in the stone, a circular trace polished where the cut once had depth. You can still follow enough of that sheen to recognise the ring." },
  { id: "fd-f08", stretch: "st-flight2", w: 5, req: [], line: "A dry leather thong lies curled on the floor. Threaded onto it is a bronze bead, the metal resting within the stiff curve of the leather rather than loose beside it. The thong has dried into its present shape, while the bead remains free enough on the strip to show the threading clearly." },
  { id: "fd-g01", stretch: "st-square", w: 6, req: [], line: "In a niche at about head height, beneath a patch of soot, stands a spouted clay lamp. The soot occupies the stone above while the lamp fits the recess below it. Directly underneath the niche, a small line has been cut in the tally’s hand, modest in scale beside the lamp and its darkened patch.", told: "tl-lamp" }, // side chamber
  { id: "fd-g02", stretch: "st-square", w: 6, req: [], line: "Against the square wall lies a small sandal fitted with hobnails. Its sole is short, and the metal studs break the surface in a regular roughness where they remain. Above the sandal, a line of marks has been made on the wall, high enough that you take in footwear and marks as separate details.", told: "tl-sandal" }, // side chamber
  { id: "fd-g03", stretch: "st-square", w: 6, req: [], line: "Seen from close enough to resolve the tooling, the square wall is covered with chisel cuts. Each cut is about a finger’s width long. They run row after row across the stone, and every small incision leans at the same angle, turning the whole worked face into a repeated pattern of strokes." },
  { id: "fd-g04", stretch: "st-square", w: 6, req: [], line: "An iron hobnail lies where it fell on the floor. Rust has spread from the metal into the surface beneath it, leaving a brown stain that fixes the nail’s position even more clearly than its small shape does. The stain is concentrated around the iron rather than scattered across the stone." },
  { id: "fd-g05", stretch: "st-square", w: 6, req: [], line: "At roughly a man’s height on the square wall, strokes have been scratched into the stone in counted groups. You can follow them by tens: ten strokes, then a gap, then the next ten. The repeated spaces divide the long series cleanly, turning what might first look like scoring into a deliberate count." },
  { id: "fd-g06", stretch: "st-square", w: 6, req: [], line: "A wooden peg has been driven into a crack in the stone. The wood is still recognisable along the exposed shaft, but the outer end is charred black. The burning stops before the peg enters the crack, leaving the darkened tip outside and the rest wedged firmly into the split." },
  { id: "fd-g07", stretch: "st-square", w: 6, req: [], line: "A broken sherd from a large jar lies with its curved surface exposed. Pressed into it is a stamped mark, but handling or abrasion has rubbed the impression almost smooth. Enough remains to show that a stamp was there, while the raised and recessed detail has been reduced nearly to the level of the pottery." },
  { id: "fd-g08", stretch: "st-square", w: 6, req: [], line: "A grey whetstone has been used until its middle is no longer flat. Repeated sharpening has worn a hollow through the centre, leaving the ends thicker than the part between them. The dip is broad and smooth, shaped by use rather than by a single break or chip." },
  { id: "fd-g09", stretch: "st-square", w: 6, req: [], line: "Where the square stone meets the round, the join is not simply a dry seam. Grey metal has been poured into a crack between the two forms, filling the irregular space and hardening there. It keys one block to the other, a metallic bridge set directly across the meeting of square and round stone." },
  { id: "fd-g10", stretch: "st-square", w: 6, req: [], line: "A cut line runs the full length of the gallery at knee height. It is dead level, refusing the small variations of the floor and the individual blocks around it. Once you align your eye with it, the incision carries straight along the wall as a single horizontal measure through the square-stone passage." },
];
