/**
 * SEALED (D-015): story content. Never shown to Dan outside the game.
 * Transcribed from docs/narrative/sealed/MVP_CONTENT.md §9; those files are authoritative.
 */

import type { Passage } from '../../core/story-types';

/** In source order: each stretch's table, then the 'Anywhere' four, then the 40 extra lines. Shown in order within a stretch. */
export const passages: Passage[] = [
  { id: "ps-m01", stretch: "st-mouth", req: [], line: "The rungs are cold beneath your hands. The ninth shifts loose in its bracket." },
  { id: "ps-m02", stretch: "st-mouth", req: [], line: "Looking up the shaft, the ladder rails draw together towards the daylight." },
  { id: "ps-m03", stretch: "st-mouth", req: [], line: "A steady draught passes your face on its way up the shaft. It smells of nothing." },
  { id: "ps-m04", stretch: "st-mouth", req: [], until: "seal-1-5", line: "At the ladder’s foot, a recess is cut into the shaft wall. Strokes run along its lip; a nail is fixed above it." },
  { id: "ps-m05", stretch: "st-mouth", req: [], line: "The passage bends left by such a slow degree that the turn is almost invisible." },
  { id: "ps-m06", stretch: "st-mouth", req: [], line: "The passage floor is furred with dust finer than flour. It rises round your boots and settles behind them." },
  { id: "ps-m07", stretch: "st-mouth", req: [], line: "The walls are so smooth that dust finds nowhere to cling." },
  { id: "ps-m08", stretch: "st-mouth", req: [], line: "A cable bracket is bolted to the shaft brick. The cable itself is gone." },
  { id: "ps-m09", stretch: "st-mouth", req: [], line: "Wear has hollowed the middle of the passage floor by a hand’s depth." },
  { id: "ps-m10", stretch: "st-mouth", req: [], line: "From here, the only sound is air moving up the shaft behind you." },
  { id: "ps-h01", stretch: "st-hall", req: [], until: "b-3.A", line: "The hall continues beyond the lamp’s reach. The air is colder in that direction." },
  { id: "ps-h02", stretch: "st-hall", req: [], until: "b-3.A", line: "At head height, an empty cup is cut into the wall. The flame’s mark is cut inside it." },
  { id: "ps-h03", stretch: "st-hall", req: [], until: "b-3.A", line: "Another cup follows, then another, each a few paces from the last. All are empty." },
  { id: "ps-h04", stretch: "st-hall", req: [], line: "Dozens of rings cover the wall at shoulder height, their edges softened by wear." },
  { id: "ps-h05", stretch: "st-hall", req: [], until: "b-3.A", line: "As far as the lamp shows, the floor is a single sheet of stone without a join." },
  { id: "ps-h06", stretch: "st-hall", req: [], until: "b-3.A", line: "From this far down the hall, the lamp on its ledge is small. Its flame does not flicker." },
  { id: "ps-h07", stretch: "st-hall", req: [], until: "b-3.A", line: "The ceiling rises beyond the lamp’s reach; the light fails before it finds the curve." },
  { id: "ps-h08", stretch: "st-hall", req: [], line: "The marks continue above the height of your reach." },
  { id: "ps-h09", stretch: "st-hall", req: [], until: "b-3.A", line: "The lintel stands on the side wall. Beneath it is solid stone, with a blank beside its two marks." },
  { id: "ps-h10", stretch: "st-hall", req: [], until: "b-3.A", line: "At the far end, darkness takes the hall well before the great door." },
  { id: "ps-h11", stretch: "st-hall", req: [], line: "The hall smells of dry stone, with salt faint beneath it." },
  { id: "ps-h12", stretch: "st-hall", req: ["b-3.A"], line: "Flames burn in the cups along both walls, each exactly the height of the next." },
  { id: "ps-h13", stretch: "st-hall", req: ["b-3.A"], line: "Lamplight puts a small shadow into every cut on the walls." },
  { id: "ps-h14", stretch: "st-hall", req: ["b-3.A"], line: "The lamps continue round the corner towards the salt." },
  { id: "ps-h15", stretch: "st-hall", req: ["b-3.A"], line: "Each wall-cup casts a small half-moon of light onto the floor, one after another." },
  { id: "ps-h16", stretch: "st-hall", req: ["b-3.A"], line: "The stone below the lintel is gone. Through the opening, the landing is already lit." },
  { id: "ps-h17", stretch: "st-hall", req: ["b-3.A"], until: "b-7.C", line: "The flames stand straight even while the draught passes along the hall." },
  { id: "ps-h18", stretch: "st-hall", req: ["b-3.A"], line: "With the hall lit, a paler track appears worn down the centre of the floor." },
  { id: "ps-h19", stretch: "st-hall", req: ["b-3.A"], line: "The great door takes up the wall at the far end. The lamps stop before reaching it." },
  { id: "ps-h20", stretch: "st-hall", req: ["b-3.A"], line: "Now the light reaches the ceiling. Marks are cut there too, with rings among them." },
  { id: "ps-h21", stretch: "st-hall", req: ["b-3.A"], line: "Every wall-cup burns with the same coloured flame as the clay lamp. None contains oil." },
  { id: "ps-h22", stretch: "st-hall", req: [], line: "The ledge is part of the wall itself, cut from the same stone without a join." },
  { id: "ps-c01", stretch: "st-salt", req: [], line: "At the corner, two smooth troughs dip into the floor a stride apart, each hollowed like a basin." },
  { id: "ps-c02", stretch: "st-salt", req: [], line: "The polished patch at the corner catches the light; the rest of the wall stays matt." },
  { id: "ps-c03", stretch: "st-salt", req: [], line: "Beyond the turn, the smell of salt strengthens." },
  { id: "ps-c04", stretch: "st-salt", req: [], line: "Here the floor itself is salt, packed hard and grey. It creaks under your weight." },
  { id: "ps-c05", stretch: "st-salt", req: [], line: "Grey and white bands run through the salt face." },
  { id: "ps-c06", stretch: "st-salt", req: [], line: "The tally follows the wall at about the height of a man’s chest." },
  { id: "ps-c07", stretch: "st-salt", req: [], line: "White salt has furred the lowest cuts of the tally." },
  { id: "ps-c08", stretch: "st-salt", req: [], line: "Her sheets remain tucked in the crack. The top one has begun to curl at a corner." },
  { id: "ps-c09", stretch: "st-salt", req: [], line: "The split has been packed tight: stone against stone, every gap worked full of salt." },
  { id: "ps-c10", stretch: "st-salt", req: ["seal-1-1"], line: "Small pictures interrupt the tally’s marks: a lamb, a loaf, a long-legged bird." },
  { id: "ps-c11", stretch: "st-salt", req: [], line: "The roof is low enough to feel close. The salt overhead has a dull sheen." },
  { id: "ps-c12", stretch: "st-salt", req: [], line: "Where cut stone meets salt, the boundary is straight as a rule." },
  { id: "ps-c13", stretch: "st-salt", req: [], line: "Fine salt dust has drifted against the wall, granular as sugar." },
  { id: "ps-c14", stretch: "st-salt", req: [], line: "Short, slanting pick-scars score the salt face." },
  { id: "ps-c15", stretch: "st-salt", req: ["b-4.A"], line: "The tally disappears beneath a crust of salt and emerges again on the far side." }, // NOTE: from w4 in the source; req b-4.A (the crust first seen) stands in
  { id: "ps-c16", stretch: "st-salt", req: [], line: "Beyond the split, the gallery narrows until a man with both arms out could span it." },
  { id: "ps-c17", stretch: "st-salt", req: [], line: "Every so often the salt gives a small tick, like a stove cooling." },
  { id: "ps-c18", stretch: "st-salt", req: ["b-3.A"], line: "Light from the corner brings out the bands in the salt all the way to the top of the face." },
  { id: "ps-c19", stretch: "st-salt", req: ["b-2.A"], line: "The lone ring above the tally takes the light before the cuts around it do." },
  { id: "ps-c20", stretch: "st-salt", req: [], line: "A hollow has been worn into the floor in front of the tally, where someone stood to read." },
  { id: "ps-s01", stretch: "st-camp", req: [], line: "Her camp smells of paraffin and paper." },
  { id: "ps-s02", stretch: "st-camp", req: [], line: "The cot canvas has sagged into the shape of the person who slept there." },
  { id: "ps-s03", stretch: "st-camp", req: [], line: "One bootlace trails from beneath the cot, untied at the end." },
  { id: "ps-s04", stretch: "st-camp", req: [], line: "A single nail remains in the wall above the cot. Nothing hangs from it." },
  { id: "ps-s05", stretch: "st-camp", req: [], line: "Pencilled sums cover the wall by the doorway, crossed through one after another." },
  { id: "ps-s06", stretch: "st-camp", req: [], line: "Tooth marks run the length of the notebook’s pencil." },
  { id: "ps-s07", stretch: "st-camp", req: [], line: "The chamber has the hall’s rounded shape, but here the ceiling is low enough to touch." },
  { id: "ps-s08", stretch: "st-camp", req: [], line: "A folding chair stands against the wall, one leg bound with tape." },
  { id: "ps-s09", stretch: "st-camp", req: ["b-2.B"], line: "Dust covers the shelf except for one clean forearm-long stripe." },
  { id: "ps-s10", stretch: "st-camp", req: [], line: "A pair of socks hangs from a string across the corner, dried stiff as card." },
  { id: "ps-s11", stretch: "st-camp", req: [], line: "Her belongings are stacked along the wall in squared-off piles." },
  { id: "ps-s12", stretch: "st-camp", req: [], line: "An upturned plastic crate serves as a table, its top marked by rings from mugs." },
  { id: "ps-t01", stretch: "st-stair", req: [], line: "The landing has no rail along its edge. The first step is a stride below it." },
  { id: "ps-t02", stretch: "st-stair", req: [], line: "The treads are so deep that you could lie down on one." },
  { id: "ps-t03", stretch: "st-stair", req: [], line: "Use has worn the middle of each step pale." },
  { id: "ps-t04", stretch: "st-stair", req: [], line: "The rail is cut from the wall itself and reaches your chest." },
  { id: "ps-t05", stretch: "st-stair", req: [], line: "The stair lamps descend ahead, one every few steps." },
  { id: "ps-t06", stretch: "st-stair", req: ["b-4.1"], line: "After the first turn, the hall’s light is behind you. The stair’s own lamps continue below." }, // NOTE: from w4 in the source; req b-4.1 (down to the first turn) stands in
  { id: "ps-t07", stretch: "st-stair", req: [], line: "Rings are cut into the Stair wall too, at the eye-height of a tall man." },
  { id: "ps-t08", stretch: "st-stair", req: [], line: "Air rises slowly up the Stair, a little warmer than the hall behind you." },
  { id: "ps-t09", stretch: "st-stair", req: [], line: "A chip is missing from one step. The piece still lies on the tread below." },
  { id: "ps-t10", stretch: "st-stair", req: [], line: "Marks cover the Stair walls above and beyond the lamps." },
  { id: "ps-t11", stretch: "st-stair", req: [], line: "Seen from the landing, the top flight appears shorter than it is." },
  { id: "ps-t12", stretch: "st-stair", req: [], until: "seal-4-1", line: "At the first turn, beside the rail, a niche waits with an empty count." },
  { id: "ps-t13", stretch: "st-stair", req: [], line: "The top of the rail is polished darker than the wall around it." },
  { id: "ps-t14", stretch: "st-stair", req: ["b-4.1"], line: "The stair lamps throw light onto the underside of the flight above." }, // NOTE: from w4 in the source; req b-4.1 stands in
  { id: "ps-t15", stretch: "st-stair", req: [], line: "Grit crunches beneath your boot on one step. The next has been swept clean." },
  { id: "ps-t16", stretch: "st-stair", req: [], line: "At the first turn, the wall swells around the rail like a knuckle." },
  { id: "ps-t17", stretch: "st-stair", req: [], line: "Two lamps stand at the turn, one on each side, like gateposts." },
  { id: "ps-t18", stretch: "st-stair", req: [], until: "b-4.1", line: "From the first turn the second flight falls away, with a small door set into it." },
  { id: "ps-t19", stretch: "st-stair", req: [], line: "A long hand could lie along this rail without bending at the wrist." },
  { id: "ps-t20", stretch: "st-stair", req: [], line: "There are no joins between the steps. The entire flight is one piece of stone." },
  { id: "ps-f01", stretch: "st-flight2", req: [], line: "The second flight falls more steeply than the first." },
  { id: "ps-f02", stretch: "st-flight2", req: [], line: "A finger’s width of darkness shows along one edge of the little door." },
  { id: "ps-f03", stretch: "st-flight2", req: [], until: "seal-5-1", line: "Beneath the second turn is the recess with its count." },
  { id: "ps-f04", stretch: "st-flight2", req: [], line: "The lamps on the second flight stand farther apart." },
  { id: "ps-f05", stretch: "st-flight2", req: [], line: "At the second turn, the stone pales almost to cream." },
  { id: "ps-f06", stretch: "st-flight2", req: ["b-5.B"], line: "At the gap, the rounded stone has been hacked back rough with smaller tools." },
  { id: "ps-f07", stretch: "st-flight2", req: ["pl-w5-second-landing"], line: "Wear curves across the second landing’s floor towards the low doorway." }, // NOTE: from w5 in the source; req pl-w5-second-landing stands in
  { id: "ps-f08", stretch: "st-flight2", req: ["pl-w5-second-landing"], line: "The lamps on the second landing sit lower in the wall than those on the Stair." },
  { id: "ps-f09", stretch: "st-flight2", req: [], line: "Here the rings are smaller and more closely packed." },
  { id: "ps-f10", stretch: "st-flight2", req: [], line: "A ring is cut into the riser of one step, too low for anyone standing to read." },
  { id: "ps-f11", stretch: "st-flight2", req: ["b-6.A"], line: "Below the second landing, the Stair continues. A lintel spans it, with nothing but stone underneath." }, // NOTE: from w6 in the source; req b-6.A (the week 6 opener) stands in
  { id: "ps-f12", stretch: "st-flight2", req: [], line: "For one stride, the rail on the second flight is broken away. The old break has worn smooth." },
  { id: "ps-f13", stretch: "st-flight2", req: ["pl-w5-second-landing"], line: "From the second landing, you can hear air moving somewhere far below." }, // NOTE: from w5 in the source; req pl-w5-second-landing stands in
  { id: "ps-f14", stretch: "st-flight2", req: ["pl-w5-second-landing"], line: "A small square stone lies on the landing. It is not made from the Stair’s stone. Someone carried it here." }, // NOTE: from w5 in the source; req pl-w5-second-landing stands in
  { id: "ps-f15", stretch: "st-flight2", req: ["pl-w5-second-landing"], line: "The lamps on the landing throw your shadow back up the Stair." }, // NOTE: from w5 in the source; req pl-w5-second-landing stands in
  { id: "ps-f16", stretch: "st-flight2", req: [], line: "The second flight’s steps rise as high as those above, but their treads are narrower." },
  { id: "ps-g01", stretch: "st-square", req: [], line: "The square gallery runs dead straight, as though laid out with a rule." },
  { id: "ps-g02", stretch: "st-square", req: [], line: "Small chisel marks cover the walls in close, even rows." },
  { id: "ps-g03", stretch: "st-square", req: [], line: "The ceiling is flat—the only flat ceiling you have seen down here." },
  { id: "ps-g04", stretch: "st-square", req: [], line: "The square walls are bare except where the tally’s hand has cut into them." },
  { id: "ps-g05", stretch: "st-square", req: [], line: "Old hobnail impressions remain hardened in the dust of the square floor." },
  { id: "ps-g06", stretch: "st-square", req: [], line: "Old smoke lingers in the gallery’s smell." },
  { id: "ps-g07", stretch: "st-square", req: [], line: "At every ten paces, a short line is cut at the edge of the floor." },
  { id: "ps-g08", stretch: "st-square", req: [], line: "A square beam-slot has been cut into the wall. It is empty." },
  { id: "ps-g09", stretch: "st-square", req: [], line: "The square stone is darker than the rounded stone and crossed by cracks." },
  { id: "ps-g10", stretch: "st-square", req: [], line: "The corners of the gallery are sharp enough to cut a finger." },
  { id: "ps-g11", stretch: "st-square", req: [], line: "A ceiling crack has been plugged with a wedge of wood gone grey." },
  { id: "ps-g12", stretch: "st-square", req: [], line: "A faint line of soot runs down the middle of the ceiling, left where lights were carried." },
  { id: "ps-g13", stretch: "st-square", req: [], line: "The floor rises almost imperceptibly towards the centre, like a road built to shed water." },
  { id: "ps-g14", stretch: "st-square", req: [], line: "Dust deepens as the gallery goes on." },
  { id: "ps-g15", stretch: "st-square", req: [], line: "A pale rectangle on the wall marks where a board once hung. Four peg-holes remain." },
  { id: "ps-g16", stretch: "st-square", req: [], line: "Behind you the Stair is lit. Ahead, the square gallery runs into darkness." },
  { id: "ps-x01", stretch: "st-mouth", req: [], line: "From time to time a draught rises from below, strong enough to lift the dust." }, // NOTE: 'Anywhere' in the source (no stretch); st-mouth is a placeholder
  { id: "ps-x02", stretch: "st-salt", req: [], line: "It is quiet enough here for each footfall to sound separate." }, // NOTE: 'Anywhere' in the source (no stretch); st-salt is a placeholder
  { id: "ps-x03", stretch: "st-hall", req: [], until: "b-3.A", line: "Far behind, the lamp’s light still touches the wall." }, // NOTE: 'Anywhere' in the source (no stretch); st-hall is a placeholder
  { id: "ps-x04", stretch: "st-hall", req: [], line: "Dust turns slowly in the beam of light and hangs there without settling." }, // NOTE: 'Anywhere' in the source (no stretch); st-hall is a placeholder
  { id: "ps-m11", stretch: "st-mouth", req: [], line: "A maker’s stamp is pressed into the shaft brick, worn almost to a blur." },
  { id: "ps-m12", stretch: "st-mouth", req: [], line: "A bolt sits in the brickwork with a brown rust-stain running down beneath it." },
  { id: "ps-m13", stretch: "st-mouth", req: [], line: "Where the passage leaves the shaft, boots have scuffed the floor grey." },
  { id: "ps-m14", stretch: "st-mouth", req: [], line: "The passage is just wider than your reach; you cannot quite touch both walls at once." },
  { id: "ps-h23", stretch: "st-hall", req: [], until: "b-3.A", line: "The lamp lays an oval of light across the floor. Beyond it, the hall is dark." },
  { id: "ps-h24", stretch: "st-hall", req: [], line: "The wall beside the ledge is so densely cut that, at a distance, it resembles woven cloth." },
  { id: "ps-h25", stretch: "st-hall", req: [], line: "A hairline crack runs across the lip of one cup." },
  { id: "ps-h26", stretch: "st-hall", req: [], until: "b-3.A", line: "The hall floor feels cold even through your boots." },
  { id: "ps-h27", stretch: "st-hall", req: [], line: "Two rings have been cut so close that their curves touch." },
  { id: "ps-h28", stretch: "st-hall", req: [], until: "b-3.A", line: "Somewhere beyond the lamp’s reach, the far wall returns your footsteps a moment late." },
  { id: "ps-h29", stretch: "st-hall", req: [], until: "b-3.A", line: "Near the lintel, the marks are cut deeper than elsewhere on the wall." },
  { id: "ps-h30", stretch: "st-hall", req: ["b-3.A"], line: "The flames nearest the ledge lean, just perceptibly, towards it." },
  { id: "ps-c21", stretch: "st-salt", req: [], line: "The salt floor lies in shallow ridges, like sand left by a tide." },
  { id: "ps-c22", stretch: "st-salt", req: [], line: "A fist-sized lump of salt has fallen from the roof and remains where it struck the floor." },
  { id: "ps-c23", stretch: "st-salt", req: [], line: "The strip of cut stone carrying the tally stands a hand’s width proud of the surrounding salt." },
  { id: "ps-c24", stretch: "st-salt", req: [], line: "The gallery air is drier than the hall’s. Salt sits on your tongue." },
  { id: "ps-c25", stretch: "st-salt", req: [], line: "The tally rounds a corner of the wall without breaking its line." },
  { id: "ps-c26", stretch: "st-salt", req: [], line: "Faint pencil ticks sit beside some marks in the tally’s first stretch." },
  { id: "ps-c27", stretch: "st-salt", req: [], line: "A darker grey vein crosses the salt face on a slant." },
  { id: "ps-c28", stretch: "st-salt", req: [], line: "A boot-heel has left a hollow in the salt floor, with another close beside it." },
  { id: "ps-c29", stretch: "st-salt", req: [], line: "Fine salt grains have gathered in a little heap where the split meets the floor." },
  { id: "ps-c30", stretch: "st-salt", req: [], line: "Every visible cut of the tally is the same depth, from first to last." },
  { id: "ps-s13", stretch: "st-camp", req: [], line: "A mug sits on the floor by the cot. A dry brown ring remains at the bottom." },
  { id: "ps-s14", stretch: "st-camp", req: [], line: "The camp doorway is round-topped. A jacket hangs from a crack in it." },
  { id: "ps-s15", stretch: "st-camp", req: [], line: "Sheets of paper are everywhere, each held down by a small stone." },
  { id: "ps-s16", stretch: "st-camp", req: [], line: "The washing-up bowl is dry. The sponge inside has hardened." },
  { id: "ps-s17", stretch: "st-camp", req: [], line: "A rolled mat leans against the wall with its strap hanging open." },
  { id: "ps-s18", stretch: "st-camp", req: [], line: "FOOD is written on a cardboard box. Underneath, smaller: *mostly*." },
  { id: "ps-s19", stretch: "st-camp", req: [], line: "A plastic water bottle stands one-third full. The water is flat and clear." },
  { id: "ps-s20", stretch: "st-camp", req: [], line: "At the doorway, the smell of her camp thins and the stone smell returns." },
  { id: "ps-t21", stretch: "st-stair", req: [], line: "The stair lamps are set at the height of a tall man’s hand." },
  { id: "ps-t22", stretch: "st-stair", req: [], line: "A long crack follows one side of the flight, yet none of the steps has shifted." },
  { id: "ps-t23", stretch: "st-stair", req: [], line: "Use has rounded the edges of the steps; none is sharp now." },
  { id: "ps-t24", stretch: "st-stair", req: [], line: "Looking down from the landing, the lamps form a line that bends with the Stair at the turn." },
  { id: "ps-t25", stretch: "st-stair", req: [], line: "A ring is cut low into the face of one step, half erased by passing feet." },
  { id: "ps-g17", stretch: "st-square", req: [], line: "Among the even pick-marks, one cut is deeper: a blow that went wrong." },
  { id: "ps-g18", stretch: "st-square", req: [], line: "The square floor has been swept once. A clean strip follows one wall." },
  { id: "ps-g19", stretch: "st-square", req: [], line: "A grey stub of candle-grease rests on the lip of a crack." },
  { id: "ps-g20", stretch: "st-square", req: [], line: "The gallery walls lean inward very slightly as they rise." },
  { id: "ps-g21", stretch: "st-square", req: [], line: "Two chisel cuts cross each other on the square wall. No others do." },
];

/** The four 'Anywhere' lines (ps-x…): the source gives them no stretch; the stretch on each is a placeholder. At most once a day (§9.9). */
export const anywherePassages: string[] = ['ps-x01', 'ps-x02', 'ps-x03', 'ps-x04'];
