/**
 * SEALED (D-015): story content. Never shown to Dan outside the game.
 * Transcribed from docs/narrative/sealed/MVP_CONTENT.md §9; those files are authoritative.
 */

import type { Passage } from '../../core/story-types';

/** In source order: each stretch's table, then the 'Anywhere' four, then the 40 extra lines. Shown in order within a stretch. */
export const passages: Passage[] = [
  { id: "ps-m01", stretch: "st-mouth", req: [], line: "The rungs are cold, and the ninth one is loose in its bracket." },
  { id: "ps-m02", stretch: "st-mouth", req: [], line: "Up the shaft, the ladder's rails narrow and meet in the daylight." },
  { id: "ps-m03", stretch: "st-mouth", req: [], line: "The draught goes up the shaft past your face, steady, and smells of nothing." },
  { id: "ps-m04", stretch: "st-mouth", req: [], until: "seal-1-5", line: "In the shaft wall at the ladder's foot is a recess with a row of cut strokes on its lip, and a nail above it." },
  { id: "ps-m05", stretch: "st-mouth", req: [], line: "The passage curves off to the left, so slowly it hardly seems to." },
  { id: "ps-m06", stretch: "st-mouth", req: [], line: "Dust lies on the passage floor, finer than flour. It lifts round your boots and settles again." },
  { id: "ps-m07", stretch: "st-mouth", req: [], line: "The walls here are smooth enough that the dust does not stay on them." },
  { id: "ps-m08", stretch: "st-mouth", req: [], line: "A bracket for a cable is bolted into the shaft's brick, but there is no cable." },
  { id: "ps-m09", stretch: "st-mouth", req: [], line: "The passage floor dips a hand's depth down its middle, worn by feet." },
  { id: "ps-m10", stretch: "st-mouth", req: [], line: "From the passage, the only sound is the air going up behind you." },
  { id: "ps-h01", stretch: "st-hall", req: [], until: "b-3.A", line: "The hall goes on past where the light of the lamp on the ledge reaches, and the air is colder that way." },
  { id: "ps-h02", stretch: "st-hall", req: [], until: "b-3.A", line: "A cup is cut in the wall at head height, empty, with the flame's mark inside it." },
  { id: "ps-h03", stretch: "st-hall", req: [], until: "b-3.A", line: "Beyond it is another cup, and then another, a few paces apart, and all of them are empty." },
  { id: "ps-h04", stretch: "st-hall", req: [], line: "Rings are cut in the wall at shoulder height, dozens of them, worn soft at the edges." },
  { id: "ps-h05", stretch: "st-hall", req: [], until: "b-3.A", line: "The floor is one stone as far as the lamp on the ledge shows, with no joins in it." },
  { id: "ps-h06", stretch: "st-hall", req: [], until: "b-3.A", line: "From here the lamp on its ledge is small, and it does not flicker." },
  { id: "ps-h07", stretch: "st-hall", req: [], until: "b-3.A", line: "The ceiling curves over so high that the light of the lamp on the ledge gives out before it reaches it." },
  { id: "ps-h08", stretch: "st-hall", req: [], line: "The marks go on up the wall past where you can reach." },
  { id: "ps-h09", stretch: "st-hall", req: [], until: "b-3.A", line: "On the side wall stands the lintel, with only stone beneath it and the blank beside its two marks." },
  { id: "ps-h10", stretch: "st-hall", req: [], until: "b-3.A", line: "At the far end the light of the lamp on the ledge stops well short of the door." },
  { id: "ps-h11", stretch: "st-hall", req: [], line: "The hall smells of dry stone and, very faintly, of salt." },
  { id: "ps-h12", stretch: "st-hall", req: ["b-3.A"], line: "The cups burn along both walls, each flame the same height as the last." },
  { id: "ps-h13", stretch: "st-hall", req: ["b-3.A"], line: "In the lamplight every cut in the walls stands out in its own shadow." },
  { id: "ps-h14", stretch: "st-hall", req: ["b-3.A"], line: "The lamps go round the corner and on toward the salt." },
  { id: "ps-h15", stretch: "st-hall", req: ["b-3.A"], line: "The cups throw small half-moons of light on the floor, in a row." },
  { id: "ps-h16", stretch: "st-hall", req: ["b-3.A"], line: "The stone under the lintel is gone, and the landing beyond it is lit." },
  { id: "ps-h17", stretch: "st-hall", req: ["b-3.A"], until: "b-7.C", line: "The flames stand straight. The draught along the hall does not move them." },
  { id: "ps-h18", stretch: "st-hall", req: ["b-3.A"], line: "Lit, the hall's floor shows a paler path worn down its middle." },
  { id: "ps-h19", stretch: "st-hall", req: ["b-3.A"], line: "At the far end the great door fills the wall, and the lamps stop short of it." },
  { id: "ps-h20", stretch: "st-hall", req: ["b-3.A"], line: "The light reaches the ceiling now, and there are marks there too, with rings among them." },
  { id: "ps-h21", stretch: "st-hall", req: ["b-3.A"], line: "The flames in the cups are the colour of the clay lamp's, and there is no oil in any of them." },
  { id: "ps-h22", stretch: "st-hall", req: [], line: "The ledge is cut out of the wall itself, with no join." },
  { id: "ps-c01", stretch: "st-salt", req: [], line: "At the corner the floor dips twice, a stride apart, and the dips are smooth as a basin." },
  { id: "ps-c02", stretch: "st-salt", req: [], line: "The polished wall at the corner shines where the rest of the hall is matt." },
  { id: "ps-c03", stretch: "st-salt", req: [], line: "Past the turn, the smell of salt gets stronger." },
  { id: "ps-c04", stretch: "st-salt", req: [], line: "The gallery floor is salt here, packed hard and grey, and it creaks underfoot." },
  { id: "ps-c05", stretch: "st-salt", req: [], line: "The salt face is streaked in bands of grey and white." },
  { id: "ps-c06", stretch: "st-salt", req: [], line: "The tally runs along the wall at the height of a man's chest." },
  { id: "ps-c07", stretch: "st-salt", req: [], line: "The tally's lowest cuts are furred white." },
  { id: "ps-c08", stretch: "st-salt", req: [], line: "Her sheets are in the crack, and the top one is curling at the corner." },
  { id: "ps-c09", stretch: "st-salt", req: [], line: "The split is packed tight, stone against stone, salt in every gap." },
  { id: "ps-c10", stretch: "st-salt", req: ["seal-1-1"], line: "Between the tally's marks are small pictures: a lamb, a loaf, a bird with long legs." },
  { id: "ps-c11", stretch: "st-salt", req: [], line: "The roof is low here, and the salt overhead has a sheen on it." },
  { id: "ps-c12", stretch: "st-salt", req: [], line: "Where the cut stone meets the salt, the line between them is as straight as a rule." },
  { id: "ps-c13", stretch: "st-salt", req: [], line: "Salt dust has drifted against the wall, fine as sugar." },
  { id: "ps-c14", stretch: "st-salt", req: [], line: "The salt face is marked with pick scars, short and slanting." },
  { id: "ps-c15", stretch: "st-salt", req: ["b-4.A"], line: "The tally goes under a crust of salt and comes out the other side." }, // NOTE: from w4 in the source; req b-4.A (the crust first seen) stands in
  { id: "ps-c16", stretch: "st-salt", req: [], line: "Past the split the gallery narrows to the width of a man's arms held out." },
  { id: "ps-c17", stretch: "st-salt", req: [], line: "Now and then the salt ticks, like a stove cooling." },
  { id: "ps-c18", stretch: "st-salt", req: ["b-3.A"], line: "In the glow from the corner, the salt's bands show all the way up the face." },
  { id: "ps-c19", stretch: "st-salt", req: ["b-2.A"], line: "The lone ring over the tally catches the light before anything near it." },
  { id: "ps-c20", stretch: "st-salt", req: [], line: "In front of the tally a hollow is worn in the floor, where someone stood to read it." },
  { id: "ps-s01", stretch: "st-camp", req: [], line: "Her camp smells of paraffin and paper." },
  { id: "ps-s02", stretch: "st-camp", req: [], line: "The cot's canvas sags in the middle, in the shape of whoever slept on it." },
  { id: "ps-s03", stretch: "st-camp", req: [], line: "A bootlace hangs out from under the cot, untied at one end." },
  { id: "ps-s04", stretch: "st-camp", req: [], line: "On the wall above the cot is a nail with nothing on it." },
  { id: "ps-s05", stretch: "st-camp", req: [], line: "On the wall by the doorway are sums in pencil, crossed out." },
  { id: "ps-s06", stretch: "st-camp", req: [], line: "The notebook's pencil has tooth marks all along it." },
  { id: "ps-s07", stretch: "st-camp", req: [], line: "The chamber is rounded like the hall, but the ceiling is low enough to touch." },
  { id: "ps-s08", stretch: "st-camp", req: [], line: "A folding chair stands here with one leg wrapped in tape." },
  { id: "ps-s09", stretch: "st-camp", req: ["b-2.B"], line: "The shelf is dusty except for a clean stripe where something long used to lie." },
  { id: "ps-s10", stretch: "st-camp", req: [], line: "A pair of socks hangs on a string across the corner, stiff as card." },
  { id: "ps-s11", stretch: "st-camp", req: [], line: "Her things stand in piles along the wall, each pile squared off." },
  { id: "ps-s12", stretch: "st-camp", req: [], line: "A plastic crate is turned over for a table, with rings of mug stains on top." },
  { id: "ps-t01", stretch: "st-stair", req: [], line: "The landing has no rail at its edge. The drop to the first step is a stride." },
  { id: "ps-t02", stretch: "st-stair", req: [], line: "The treads are deep enough to lie down on." },
  { id: "ps-t03", stretch: "st-stair", req: [], line: "The steps are worn pale down the middle." },
  { id: "ps-t04", stretch: "st-stair", req: [], line: "The rail is cut out of the wall itself, at the height of your chest." },
  { id: "ps-t05", stretch: "st-stair", req: [], line: "The stair's lamps go down ahead of you, one every few steps." },
  { id: "ps-t06", stretch: "st-stair", req: ["b-4.1"], line: "Past the first turn the hall's light is behind you, and the stair's own lamps go on." }, // NOTE: from w4 in the source; req b-4.1 (down to the first turn) stands in
  { id: "ps-t07", stretch: "st-stair", req: [], line: "The stair wall has rings too, at the height of a tall man's eye." },
  { id: "ps-t08", stretch: "st-stair", req: [], line: "The air comes up the stair, slow, a little warmer than the hall's." },
  { id: "ps-t09", stretch: "st-stair", req: [], line: "One step has a chip out of its edge, and the chip still lies on the step below." },
  { id: "ps-t10", stretch: "st-stair", req: [], line: "The walls are cut with marks all the way up past the lamps." },
  { id: "ps-t11", stretch: "st-stair", req: [], line: "From the landing the top flight looks shorter than it is." },
  { id: "ps-t12", stretch: "st-stair", req: [], until: "seal-4-1", line: "At the first turn, beside the rail, is a niche with a count, and its strokes are empty." },
  { id: "ps-t13", stretch: "st-stair", req: [], line: "The rail's top is polished darker than the wall." },
  { id: "ps-t14", stretch: "st-stair", req: ["b-4.1"], line: "The stair's lamps light the underside of the flight above." }, // NOTE: from w4 in the source; req b-4.1 stands in
  { id: "ps-t15", stretch: "st-stair", req: [], line: "Grit on one step crunches under your boot, and the next is swept clean." },
  { id: "ps-t16", stretch: "st-stair", req: [], line: "At the first turn the wall bulges round the rail like a knuckle." },
  { id: "ps-t17", stretch: "st-stair", req: [], line: "Two lamps stand at the turn, one on either side, like the posts of a gate." },
  { id: "ps-t18", stretch: "st-stair", req: [], until: "b-4.1", line: "From the first turn, the second flight goes down, and there is a small door on it." },
  { id: "ps-t19", stretch: "st-stair", req: [], line: "A long hand could rest on this rail without bending." },
  { id: "ps-t20", stretch: "st-stair", req: [], line: "The steps have no joins. The whole flight is one stone." },
  { id: "ps-f01", stretch: "st-flight2", req: [], line: "The second flight is steeper than the first." },
  { id: "ps-f02", stretch: "st-flight2", req: [], line: "A finger's width of dark runs down one edge of the little door." },
  { id: "ps-f03", stretch: "st-flight2", req: [], until: "seal-5-1", line: "Under the second turn is the recess, with its count." },
  { id: "ps-f04", stretch: "st-flight2", req: [], line: "The lamps on the second flight are further apart." },
  { id: "ps-f05", stretch: "st-flight2", req: [], line: "At the second turn the stone goes paler, almost cream." },
  { id: "ps-f06", stretch: "st-flight2", req: ["b-5.B"], line: "At the gap the round stone has been cut back, rough, by smaller tools." },
  { id: "ps-f07", stretch: "st-flight2", req: ["pl-w5-second-landing"], line: "The second landing's floor is worn in a curve toward the low doorway." }, // NOTE: from w5 in the source; req pl-w5-second-landing stands in
  { id: "ps-f08", stretch: "st-flight2", req: ["pl-w5-second-landing"], line: "On the second landing the lamps are set lower in the wall than on the stair." },
  { id: "ps-f09", stretch: "st-flight2", req: [], line: "The rings here are smaller and closer together." },
  { id: "ps-f10", stretch: "st-flight2", req: [], line: "One step has a ring cut in its riser, where no one standing would read it." },
  { id: "ps-f11", stretch: "st-flight2", req: ["b-6.A"], line: "Below the second landing the stair goes on, and a lintel stands over it with only stone beneath." }, // NOTE: from w6 in the source; req b-6.A (the week 6 opener) stands in
  { id: "ps-f12", stretch: "st-flight2", req: [], line: "The rail on the second flight is broken off for a stride, and the break is old and smooth." },
  { id: "ps-f13", stretch: "st-flight2", req: ["pl-w5-second-landing"], line: "From the second landing you can hear air moving below, a long way down." }, // NOTE: from w5 in the source; req pl-w5-second-landing stands in
  { id: "ps-f14", stretch: "st-flight2", req: ["pl-w5-second-landing"], line: "A small square stone lies on the landing. It is not the stair's stone. Someone brought it in." }, // NOTE: from w5 in the source; req pl-w5-second-landing stands in
  { id: "ps-f15", stretch: "st-flight2", req: ["pl-w5-second-landing"], line: "The lamps on the second landing throw your shadow back up the stair." }, // NOTE: from w5 in the source; req pl-w5-second-landing stands in
  { id: "ps-f16", stretch: "st-flight2", req: [], line: "The second flight's steps are as high as the first's, and narrower." },
  { id: "ps-g01", stretch: "st-square", req: [], line: "The square gallery runs straight, as if someone drew it with a rule." },
  { id: "ps-g02", stretch: "st-square", req: [], line: "The chisel marks are small and close, row on row." },
  { id: "ps-g03", stretch: "st-square", req: [], line: "The ceiling is flat. It is the only flat ceiling down here." },
  { id: "ps-g04", stretch: "st-square", req: [], line: "The square walls are bare, except where the tally's hand has cut on them." },
  { id: "ps-g05", stretch: "st-square", req: [], line: "In the dust of the square floor, old and hard, are the marks of hobnails." },
  { id: "ps-g06", stretch: "st-square", req: [], line: "The gallery smells of old smoke." },
  { id: "ps-g07", stretch: "st-square", req: [], line: "Every ten paces a short line is cut at the edge of the floor." },
  { id: "ps-g08", stretch: "st-square", req: [], line: "A square beam-slot is cut in the wall, with nothing in it." },
  { id: "ps-g09", stretch: "st-square", req: [], line: "The square stone is darker than the round, and it has cracks in it." },
  { id: "ps-g10", stretch: "st-square", req: [], line: "The gallery's corners are sharp enough to cut a finger on." },
  { id: "ps-g11", stretch: "st-square", req: [], line: "A crack in the ceiling has been stopped with a wedge of wood gone grey." },
  { id: "ps-g12", stretch: "st-square", req: [], line: "Down the middle of the ceiling runs a faint line of soot, where lights were carried." },
  { id: "ps-g13", stretch: "st-square", req: [], line: "The floor rises very slightly toward the middle, the way a road does to shed water." },
  { id: "ps-g14", stretch: "st-square", req: [], line: "The dust gets thicker toward the far end." },
  { id: "ps-g15", stretch: "st-square", req: [], line: "A pale patch on the square wall shows where a board was fixed, and there are four holes for its pegs." },
  { id: "ps-g16", stretch: "st-square", req: [], line: "Behind you the stair is lit. Ahead, the square stone goes dark." },
  { id: "ps-x01", stretch: "st-mouth", req: [], line: "Now and then a draught comes up from below, enough to lift the dust." }, // NOTE: 'Anywhere' in the source (no stretch); st-mouth is a placeholder
  { id: "ps-x02", stretch: "st-salt", req: [], line: "It is quiet enough to hear your own boots." }, // NOTE: 'Anywhere' in the source (no stretch); st-salt is a placeholder
  { id: "ps-x03", stretch: "st-hall", req: [], until: "b-3.A", line: "Far behind you, the lamp's light still shows on the wall." }, // NOTE: 'Anywhere' in the source (no stretch); st-hall is a placeholder
  { id: "ps-x04", stretch: "st-hall", req: [], line: "Dust turns slowly in the light and does not settle." }, // NOTE: 'Anywhere' in the source (no stretch); st-hall is a placeholder
  { id: "ps-m11", stretch: "st-mouth", req: [], line: "The shaft's brick is stamped with a maker's mark, worn to a blur." },
  { id: "ps-m12", stretch: "st-mouth", req: [], line: "A bolt is set in the brick, and a brown rust stain runs down from it." },
  { id: "ps-m13", stretch: "st-mouth", req: [], line: "Where the passage leaves the shaft, the floor is scuffed grey by boots." },
  { id: "ps-m14", stretch: "st-mouth", req: [], line: "The passage is just too wide to touch both walls at once." },
  { id: "ps-h23", stretch: "st-hall", req: [], until: "b-3.A", line: "The lamp's light lies on the floor in an oval, and the rest is dark." },
  { id: "ps-h24", stretch: "st-hall", req: [], line: "The wall by the ledge is cut so densely it looks like woven cloth." },
  { id: "ps-h25", stretch: "st-hall", req: [], line: "One cup has a hairline crack across its lip." },
  { id: "ps-h26", stretch: "st-hall", req: [], until: "b-3.A", line: "The hall's floor is cold through your boots." },
  { id: "ps-h27", stretch: "st-hall", req: [], line: "Two rings are cut so close together that their curves touch." },
  { id: "ps-h28", stretch: "st-hall", req: [], until: "b-3.A", line: "Somewhere past the lamp's light, the hall's far wall gives back your footsteps late." },
  { id: "ps-h29", stretch: "st-hall", req: [], until: "b-3.A", line: "Near the lintel, the marks are cut deeper than anywhere else on the wall." },
  { id: "ps-h30", stretch: "st-hall", req: ["b-3.A"], line: "The flames in the cups nearest the ledge lean very slightly toward it." },
  { id: "ps-c21", stretch: "st-salt", req: [], line: "The salt floor is ridged, like sand after the tide." },
  { id: "ps-c22", stretch: "st-salt", req: [], line: "A lump of salt the size of a fist has fallen from the roof and lies where it fell." },
  { id: "ps-c23", stretch: "st-salt", req: [], line: "The cut stone band that carries the tally is a hand's width proud of the salt." },
  { id: "ps-c24", stretch: "st-salt", req: [], line: "The gallery's air is drier than the hall's, and tastes of salt." },
  { id: "ps-c25", stretch: "st-salt", req: [], line: "Where the tally turns a corner of the wall, its line does not break." },
  { id: "ps-c26", stretch: "st-salt", req: [], line: "Her pencil has ticked some marks on the tally's first stretch, very lightly." },
  { id: "ps-c27", stretch: "st-salt", req: [], line: "The salt face has a vein of darker grey running through it at a slant." },
  { id: "ps-c28", stretch: "st-salt", req: [], line: "In the salt floor is a dip shaped like a boot heel, and another beside it." },
  { id: "ps-c29", stretch: "st-salt", req: [], line: "In the corner where the split meets the floor lies a little heap of salt grains, fine as flour." },
  { id: "ps-c30", stretch: "st-salt", req: [], line: "The tally's cuts are all the same depth, from the first to the last you can see." },
  { id: "ps-s13", stretch: "st-camp", req: [], line: "A mug stands on the floor by the cot, with a dry brown ring at the bottom of it." },
  { id: "ps-s14", stretch: "st-camp", req: [], line: "The camp's doorway is round-topped, and she has hung a jacket from a crack in it." },
  { id: "ps-s15", stretch: "st-camp", req: [], line: "There is paper everywhere, weighted down with small stones." },
  { id: "ps-s16", stretch: "st-camp", req: [], line: "A washing-up bowl has dried out, and the sponge in it has gone hard." },
  { id: "ps-s17", stretch: "st-camp", req: [], line: "A rolled mat leans against the wall, its strap undone." },
  { id: "ps-s18", stretch: "st-camp", req: [], line: "On a cardboard box she has written FOOD, and under it, in smaller letters, *mostly*." },
  { id: "ps-s19", stretch: "st-camp", req: [], line: "A plastic water bottle stands a third full, and the water in it has gone flat and clear." },
  { id: "ps-s20", stretch: "st-camp", req: [], line: "By the door the smell of her camp gives way, and the air smells of stone again." },
  { id: "ps-t21", stretch: "st-stair", req: [], line: "The lamps on the stair are set at the height of a tall man's hand." },
  { id: "ps-t22", stretch: "st-stair", req: [], line: "A long crack runs down one side of the flight, and no step has moved." },
  { id: "ps-t23", stretch: "st-stair", req: [], line: "The edges of the steps are rounded by use, not sharp." },
  { id: "ps-t24", stretch: "st-stair", req: [], line: "When you look down the stair from the landing, the lamps make a line that bends at the turn." },
  { id: "ps-t25", stretch: "st-stair", req: [], line: "A ring is cut low on the face of a step, half worn away by feet." },
  { id: "ps-g17", stretch: "st-square", req: [], line: "One pick-mark in the square wall is deeper than the rest, where a blow went wrong." },
  { id: "ps-g18", stretch: "st-square", req: [], line: "The square floor has been swept once, and a clean strip runs along one wall." },
  { id: "ps-g19", stretch: "st-square", req: [], line: "A grey stub of candle-grease sits on the lip of a crack." },
  { id: "ps-g20", stretch: "st-square", req: [], line: "The gallery's walls lean in very slightly toward the top." },
  { id: "ps-g21", stretch: "st-square", req: [], line: "Two chisel marks cross each other, the only crossed marks on the wall." },
];

/** The four 'Anywhere' lines (ps-x…): the source gives them no stretch; the stretch on each is a placeholder. At most once a day (§9.9). */
export const anywherePassages: string[] = ['ps-x01', 'ps-x02', 'ps-x03', 'ps-x04'];
