/**
 * SEALED (D-015): story content. Never shown to Dan outside the game.
 * Transcribed from docs/narrative/sealed/MVP_CONTENT.md §11 and ARRIVALS_REGION1/2 weeks 1–7 (the "I can't start" rows); those files are authoritative.
 */

import type { Teaser } from '../../core/story-types';

/** §11 order within each week. The app shows the first whose condition holds, newest-written first within the week. The b-wN.tz rows are ARR1/ARR2's (they are the same 12 as §11 lists). */
export const teasers: Teaser[] = [
  { id: "b-w1.tz1", w: 1, req: [], until: "b-1.A", line: "Under the iron cap on the hillside is an old shaft. A ladder goes eleven metres down it, and the air that comes up is dry." },
  { id: "b-w1.tz2", w: 1, req: ["b-1.A"], until: "b-3.B", line: "In the Lamp Hall, the small clay lamp on the ledge has three carved symbols on its base." },
  { id: "tz-w1-a", w: 1, req: ["pl-w1-pick-niche"], until: "seal-1-2", line: "In the Salt Gallery, low in the salt wall, is a closed niche as long as your arm, with a row of small, empty notches along its lip." },
  { id: "tz-w1-b", w: 1, req: ["b-1.C"], until: "seal-2-1", line: "In the Box Room, the side chamber where someone camped, a tin box lies on the cot with a row of small notches across its lid." },
  { id: "tz-w1-c", w: 1, req: ["pl-w1-below-the-lamp"], until: "seal-1-3", line: "In the Lamp Hall, under the ledge where the lamp stands, is a small closed niche, and the stone round its mouth is darker than the rest." },
  { id: "b-w2.tz1", w: 2, req: [], until: "b-2.B", line: "In the Box Room, on the shelf, lies a rod of stone as long as your forearm, with one edge finer than a knife's." },
  { id: "b-w2.tz2", w: 2, req: ["b-2.B"], until: "b-3.A", line: "The stone rod is in your hand, and on the lintel in the Lamp Hall is a blank, an empty gap beside two symbols, the width of its edge." },
  { id: "tz-w2-a", w: 2, req: ["pl-w2-above-the-ring"], until: "seal-2-3", line: "In the Salt Gallery, above the lone ring, something pale lies far back in a crack in the salt." },
  { id: "tz-w2-b", w: 2, req: ["pl-w2-box-by-the-cot"], until: "seal-2-5", line: "In the Box Room, a tin mug stands upside down on a shoebox-sized box by the cot, on a slate with a row of notches." },
  { id: "tz-w2-c", w: 2, req: ["b-2.A"], until: "seal-2-2", line: "In the Salt Gallery is a long, narrow niche in the salt, the length of a stick, with a row of notches on it." },
  { id: "b-w3.tz1", w: 3, req: [], until: "b-3.A", line: "The stone rod is in your hand, and on the lintel in the Lamp Hall is a blank, an empty gap beside two symbols, the width of its edge." },
  { id: "b-w3.tz2", w: 3, req: ["b-3.A"], until: "b-3.B", line: "At the head of the Stair, beyond the lintel, is a closed niche, and lying on its lid is a small stone tablet with a door carved on it." },
  { id: "tz-w3-b", w: 3, req: ["b-4.C"], until: "b-3.B", line: "At the far end of the Lamp Hall stands the great door, and cold comes off its face." },
  { id: "tz-w3-c", w: 3, req: ["b-3.2"], until: "seal-3-5", line: "In the Box Room, where she lived, a box with a label in her handwriting on its side sits on a ledge, and a row of dark notches runs along the ledge's edge." },
  /* week 3: the top's niches seen before departure (D-160); shadowed by week 4's teasers from departure on */
  { id: "tz-w4-a", w: 3, req: ["b-3.5"], until: "seal-4-5", line: "Low in the salt wall of the Salt Gallery is a hollow the size of two cupped hands, with four small flat places pressed into its floor." },
  { id: "tz-w4-b", w: 3, req: ["b-3.2"], until: "seal-4-3", line: "In the Box Room, above her cot, is a recess closed by a slate with a row of notches, and a drawing pin is pushed into the crack beside it." },
  { id: "tz-w5-a", w: 3, req: ["b-3.6"], until: "seal-5-5", line: "In the Lamp Hall, under the front edge of the ledge where the lamp stands, is a row of notches, cut where no one standing would see it." },
  { id: "tz-w14-b", w: 3, req: ["b-3.5"], until: "seal-14-5", line: "In the Salt Gallery is a niche set deeper than any other, with a row of notches along its lip." },
  { id: "b-w4.tz1", w: 4, req: [], line: "Every carved record here was cut by the same carver, except two." },
  { id: "tz-w3-a", w: 4, req: ["b-3.C"], until: "seal-4-1", line: "At the Stair's first turn, beside the rail, is a closed niche with a row of notches." },
  { id: "tz-w4-c", w: 4, req: ["b-4.2"], until: "seal-5-1", line: "On the Stair, under the second turn, is a recess, an alcove with a row of notches of its own." },
  { id: "b-w5.tz1", w: 5, req: [], line: "Of all the carved lines here, one does not begin with the bar with a tick, the short bar with a small tick cut on it." },
  { id: "tz-w5-b", w: 5, req: ["b-5.B"], until: "b-6.A", line: "On the Stair, through a gap in the wall, you can see square-cut stone, and a long line carved on it." },
  { id: "tz-w5-c", w: 5, req: ["b-5.0"], line: "On the second flight of the Stair, every notch on the little door is full of light, yet the door does not open." },
  { id: "b-w6.tz1", w: 6, req: [], until: "b-6.A", line: "On the Stair's second landing, a low doorway leads off, and beyond it is square-cut stone." },
  { id: "b-w6.tz2", w: 6, req: ["b-6.2"], line: "In the square gallery, on the tablet in the niche by the join, a loaf is carved beside a symbol." },
  { id: "tz-w6-a", w: 6, req: ["pl-w6-square-gallery"], until: "seal-6-3", line: "In the square gallery, a shelf is cut into the wall at the height of your chest, with a row of notches on its lip." },
  { id: "tz-w6-b", w: 6, req: ["b-3.2"], until: "seal-6-5", line: "Across the cover of her folder, the one with HILL on its spine, lies a thin slate with a row of dark notches." },
  { id: "tz-w6-c", w: 6, req: ["b-6.A"], until: "b-6.B", line: "On the square gallery's wall is a second record, longer than the first, with a closed niche under it." },
  { id: "b-w7.tz1", w: 7, req: [], until: "b-7.3", line: "At the Stair's first turn, the rail cut from the wall has the shape of a hand in its stone." },
  { id: "b-w7.tz2", w: 7, req: ["b-7.A"], until: "b-8.A", line: "Past the second lintel, the Stair goes on down through light that was burning before you came." },
  /* story weeks 8–14 (STORY_JOB §8) */
  { id: "b-w8.tz1", w: 8, req: [], until: "b-8.A", line: "At the foot of the Stair, below the second lintel, there is water, and the light of the cups lies on it without moving." },
  { id: "b-w8.tz2", w: 8, req: ["b-8.B"], line: "In your copy of the tally, beside every plain, open hook, there is a row of small strokes." },
  { id: "tz-w8-a", w: 8, req: ["b-8.A"], until: "seal-8-1", line: "At the Water's edge, beside the Stair's last step, is a niche with a row of notches." },
  { id: "tz-w8-b", w: 8, req: ["pl-w8-channel"], until: "seal-8-5", line: "In the side of the channel that feeds the Water, just above the water, is a niche with a row of notches." },
  { id: "tz-w8-c", w: 8, req: ["b-8.A"], until: "b-8.C", line: "On the Water's far shore, where the steep stair comes down, a narrower way goes on down, and the air from it smells of powder." },
  { id: "b-w9.tz1", w: 9, req: [], until: "b-9.B", line: "In your copy of the tally, on the stretch her sheet dated Day 9 covers, there is a cross the size of a fingernail that is not on her sheet." },
  { id: "b-w9.tz2", w: 9, req: ["b-9.B"], line: "In the Reading Room, on a low bench, is a small tablet with a flame on it and a cut that does not close." },
  { id: "tz-w9-a", w: 9, req: ["pl-w9-benches"], until: "seal-9-3", line: "On a bench in the Reading Room, a row of notches runs along the edge, and something lies in a groove beside it." },
  { id: "tz-w9-b", w: 9, req: ["pl-w9-approach"], until: "seal-9-5", line: "Below the Water, beside the lintel that smells of powder, are two niches with rows of dark notches." },
  { id: "b-w10.tz1", w: 10, req: [], until: "b-10.A", line: "Below the Water, the narrow way ends at a lintel over solid stone, and the stone smells of powder." },
  { id: "b-w10.tz2", w: 10, req: ["b-10.C"], line: "In the blast room, one wall has been torn open in one piece." },
  { id: "tz-w10-a", w: 10, req: ["pl-w10-deep-end"], until: "b-10.B", line: "At the square gallery's deep end, a standing stone with a row of notches stands before a fall of stone." },
  { id: "tz-w10-b", w: 10, req: ["pl-w10-blast-floor"], until: "seal-10-5", line: "In the blast room, a shelf has a row of dark notches along its edge." },
  { id: "b-w11.tz1", w: 11, req: [], until: "b-11.A", line: "In the blast room, on the ledge beside the log, lies a bound book, open, with gold on its page." },
  { id: "b-w11.tz2", w: 11, req: ["b-11.A"], line: "Beside the book on the ledge, three symbols are cut into the stone, and one of them is the bar with a tick." },
  { id: "tz-w11-a", w: 11, req: ["pl-w11-cupboard"], until: "seal-11-1", line: "In the blast room, a cupboard with a stone door has the word POWDER scratched on it and crossed out." },
  { id: "tz-w11-b", w: 11, req: ["pl-w11-far-end"], until: "seal-12-1", line: "At the far end of the Water, beside two worn dips in the shore, is a niche with a row of notches." },
  { id: "b-w12.tz1", w: 12, req: [], until: "b-12.A", line: "In the blast room, under the ledge, stands a bucket with pencil writing inside its lid." },
  { id: "b-w12.tz2", w: 12, req: ["b-12.C"], line: "At the end of the side gallery is a door, shut, and stone chips lie at its foot on this side." },
  { id: "tz-w12-a", w: 12, req: ["pl-w10-blast-floor"], until: "seal-12-4", line: "At the back of the blast room, a box stamped with a company's name has a slate with notches across its lid." },
  { id: "b-w13.tz1", w: 13, req: [], until: "b-13.A", line: "At the end of the side gallery is a door, shut, and stone chips lie at its foot on this side." },
  { id: "b-w13.tz2", w: 13, req: ["b-13.A"], until: "b-13.B", line: "At the far end of the square gallery, a slope of fallen stone fills it from floor to ceiling." },
  { id: "tz-w13-a", w: 13, req: ["b-13.1"], until: "seal-13-3", line: "In the side gallery, near the shut door, is a recess with a row of notches." },
  { id: "tz-w13-b", w: 11, req: ["b-9.A"], until: "b-13.C", line: "In the Reading Room, one bench stands apart from the rest, with notches along its edge." },
  { id: "b-w14.tz0", w: 14, req: [], until: "pl-w14-meeting", line: "Behind the lifted fall in the square gallery, the lower gallery runs on, thirty paces and more, towards rounded stone." },
  { id: "b-w14.tz1", w: 14, req: ["b-14.A"], line: "At the head of the lower way, by the rubble that now stands aside, low on the rounded stone, is a blank the width of the rod, and beside it a diamond and the bar with a tick." },
  { id: "tz-w14-a", w: 14, req: ["b-13.B"], until: "seal-14-4", line: "In the square gallery, under the line above the mule-shoe's stone, is a row of dark notches." },
];
