/**
 * SEALED (D-015): story content. Never shown to Dan outside the game.
 * Transcribed from docs/narrative/sealed/MVP_CONTENT.md §11 and ARRIVALS_REGION1/2 weeks 1–7 (the "I can't start" rows); those files are authoritative.
 */

import type { Teaser } from '../../core/story-types';

/** §11 order within each week. The app shows the first whose condition holds, newest-written first within the week. The b-wN.tz rows are ARR1/ARR2's (they are the same 12 as §11 lists). */
export const teasers: Teaser[] = [
  { id: "b-w1.tz1", w: 1, req: [], until: "b-1.A", line: "Under the cap, the ladder continues down for eleven metres. You can see rung after rung dropping into the shaft, the distance made more severe by the narrow walls around it. From below comes air noticeably drier than the air above, rising past you through the opening." },
  { id: "b-w1.tz2", w: 1, req: ["b-1.A"], line: "The clay lamp on the ledge has three marks on its base, and it is warm. You cup one hand near it without touching. Heat gathers in your palm while the stone under your other hand stays cold." },
  { id: "tz-w1-a", w: 1, req: ["pl-w1-pick-niche"], until: "seal-1-2", line: "In the salt wall is a niche about the length of your arm. Along the lip, cut strokes run in a row. Their edges break the smooth boundary of the opening, each stroke set directly into the salt at the niche’s mouth." },
  { id: "tz-w1-b", w: 1, req: ["b-1.C"], until: "seal-2-1", line: "On her cot sits a tin box, its metal sides plain except for the lid. Across that lid runs a row of cut strokes. The marks have been made into the tin itself, shallow enough to keep the lid whole, but distinct against the flat manufactured surface." },
  { id: "tz-w1-c", w: 1, req: ["pl-w1-below-the-lamp"], until: "seal-1-3", line: "Beneath the lamp’s ledge, a small niche opens in the stone. The area immediately around its mouth is darker than the wall beyond it, forming a dusky border around the recess. You can see the change of colour follow the opening rather than spreading evenly across the ledge." },
  { id: "b-w2.tz1", w: 2, req: [], until: "b-2.B", line: "On the shelf in her camp lies a rod made of stone. One edge has been worked astonishingly fine, narrower than the edge of a knife. When you compare the rod’s blunt body with that thin side, the difference is severe: most of it is solid weight, one edge reduced to precision." },
  { id: "b-w2.tz2", w: 2, req: ["b-2.B"], until: "b-3.A", line: "The stone rod rests in your hand, its worked edge turned towards the lintel. On that lintel is a blank exactly the width of the rod’s edge. Holding one in front of the other makes the correspondence hard to ignore: narrow edge in your hand, narrow empty space in the stone." },
  { id: "tz-w2-a", w: 2, req: ["pl-w2-above-the-ring"], until: "seal-2-3", line: "Above the lone ring, a crack runs back into the salt. Far inside it lies something pale, too deep in the split to make out as more than a light shape. The ring remains below, complete and near; the pale thing sits beyond easy reach in the darkness of the crack." },
  { id: "tz-w2-b", w: 2, req: ["pl-w2-box-by-the-cot"], until: "seal-2-5", line: "In her camp, a tin mug has been turned upside down on top of a box. The box bears a count. Metal cup and counted surface are stacked together, the mug’s rim resting on the lid while the marks remain visible around it." },
  { id: "tz-w2-c", w: 2, req: ["b-2.A"], until: "seal-2-2", line: "A long, narrow niche has been cut into the salt, about the length of a stick. Its shape is more slit than hollow, extending sideways through the wall. On the niche is a count, the marks kept with the opening rather than elsewhere on the surrounding salt." },
  { id: "b-w3.tz1", w: 3, req: [], until: "b-3.A", line: "The stone rod rests in your hand, its worked edge turned towards the lintel. On that lintel is a blank exactly the width of the rod’s edge. Holding one in front of the other makes the correspondence hard to ignore: narrow edge in your hand, narrow empty space in the stone." },
  { id: "b-w3.tz2", w: 3, req: ["b-3.A"], line: "At the head of the stair, a lid is set into the stone. A doorway has been carved on its surface, small enough to belong wholly to the lid rather than open through it. The carved doorway faces you at the place where the stair reaches its upper end." },
  { id: "tz-w3-a", w: 3, req: ["b-3.C"], until: "seal-4-1", line: "At the first turn of the stair, you find a niche set beside the rail. A count has been placed with it, close enough to the recess that the two details read together. The rail passes alongside, giving you a fixed height from which to judge the niche’s position." },
  { id: "tz-w3-b", w: 3, req: ["pl-w3-far-end"], line: "At the far end of the hall, the great door occupies the wall ahead. Even before you reach it, cold comes off its face, distinct from the air around you. The nearer you stand to that broad surface, the more the door itself seems to be the source of the chill." },
  { id: "tz-w3-c", w: 3, req: ["b-3.B"], until: "seal-3-5", line: "On a ledge in her camp stands a box with a count on it. One side carries a label written in her hand, the familiar lettering set against the box rather than on a loose sheet. Count and label belong to the same object, visible from different faces." },
  { id: "b-w4.tz1", w: 4, req: [], line: "You compare record after record and the cutting settles into a pattern: nearly all of them share the same hand. The depth, spacing and turn of the strokes repeat. Two do not. Their cutting is different enough to separate them from the rest." },
  { id: "tz-w4-a", w: 4, req: ["pl-w4-hollow"], until: "seal-4-5", line: "Low in the salt is a shallow hollow. In its floor lie four small flat marks, all contained within the recess rather than on the wall outside it. Their low position brings them near the ground, where the hollow’s edge partly conceals its interior until you crouch." },
  { id: "tz-w4-b", w: 4, req: ["pl-w4-recess-above-the-cot"], until: "seal-4-3", line: "Above her cot is a recess cut into the wall, with a count beside it. A drawing pin sits next to the marks, tiny against the stone. The cot below gives the recess an exact place in the camp: overhead, counted, with the pin immediately alongside." },
  { id: "tz-w4-c", w: 4, req: ["b-4.1"], until: "seal-5-1", line: "Under the stair’s second turn is another recess. This one has a count of its own, separate from the counts elsewhere on the stair. The underside of the turn lowers the stone above it, making the recess sit in the compressed space beneath the change of direction." },
  { id: "b-w5.tz1", w: 5, req: [], line: "Among the lines here, one breaks the opening pattern. The others begin with the bar with a tick; this line does not. The difference comes at the very start rather than later in the record." },
  { id: "tz-w5-a", w: 5, req: ["pl-w5-ledge-lip"], until: "seal-5-5", line: "Under the lamp’s ledge is a count cut where an upright person would not naturally see it. You have to get low enough for the underside to come into view. The marks occupy that concealed face of the stone, directly beneath the ledge rather than on its front or top." },
  { id: "tz-w5-b", w: 5, req: ["b-5.B"], until: "b-6.A", line: "Through the gap, square stone is visible beyond the nearer surface. On it you can make out a record cut in the tally’s hand. The writing sits beyond the opening, not on the edge around you, its familiar strokes transferred onto a different kind of stone." },
  { id: "tz-w5-c", w: 5, req: ["b-5.0"], line: "On the second flight, the little door’s count is full. The marks have reached whatever complete state the count allows, yet when you test the door it does not open. The finished sequence remains beside a shut piece of stone, with no movement from the door itself." },
  { id: "b-w6.tz1", w: 6, req: [], until: "b-6.A", line: "Past the second landing, a low doorway opens ahead. Beyond its threshold the stone changes to square work, the blocks showing straight edges where the rounder construction gives way. You can see the difference through the opening before entering: low doorway first, square stone immediately beyond." },
  { id: "b-w6.tz2", w: 6, req: ["b-6.2"], line: "On the salt surface, a loaf has been carved beside a mark. The loaf is recognisable by its shape alone, worked into the same pale material as the mark next to it. They occupy one small panel of salt, image and mark paired without any words between them." },
  { id: "tz-w6-a", w: 6, req: ["pl-w6-wall-shelf"], until: "seal-6-3", line: "On the square wall is a shelf with a count cut near it. Along the same wall, a level line has been scratched so straight that it keeps its height across the stone. Shelf, count and line share the worked square surface, each distinct in depth and shape." },
  { id: "tz-w6-b", w: 6, req: ["pl-w6-folder"], until: "seal-6-5", line: "Under her cot lies a folder pushed into the low space beneath the frame. On its spine, in clear capital letters, is HILL. The word is visible without opening the folder, written along the narrow edge that faces out from under the cot." },
  { id: "tz-w6-c", w: 6, req: ["b-6.A"], until: "b-6.B", line: "Farther along the square wall is a second record in the tally’s hand. It is longer than the first, occupying more of the stone before it ends. Directly beneath it is a niche, so the longer record sits over an opening rather than over an uninterrupted stretch of wall." },
  { id: "b-w7.tz1", w: 7, req: [], until: "b-7.3", line: "At the first turn of the stair, the rail holds the shape of a hand. The contour sits where a hand would meet the rail, distinct from the straight lengths on either side. You can see the shape held in the material itself at the bend." },
  { id: "b-w7.tz2", w: 7, req: ["b-7.A"], line: "Beside the great door’s blank are two marks you have seen before. They are the same two marks from the lintel on the stair, repeated here next to the empty space. The correspondence is exact enough to set stair and great door side by side in your mind without altering either." },
];
